/*
 * Generation Date: Tue, 15 Nov 2011 13:53:16
 * Generated by:    CSC
 * Generated from:   Table: UPJTSRP
 * 
 * Copyright 2011 CSC, all rights reserved.
 *
 * This software is the proprietary information of CSC.
 * Use is subject to license terms.
*/
package com.sears.processing.dataaccess;

import javax.persistence.Entity;
import javax.persistence.Table;

import com.csc.qre.cics.fileacess.vsam.FileType;
import com.csc.qre.cics.fileacess.vsam.IndexedVsamFile;
import com.csc.qre.cics.fileacess.vsam.annotations.Vsam;
import com.csc.qre.cics.fileacess.vsam.annotations.VsamKsds;

/**
 * Provides access to the VSAM data objects
 *	
 */
@Entity
@Table(name="UPJTSRP")
@Vsam(name="UPJTSRP", type=FileType.KeySequenced, length=1000, fixedLength=true)
@VsamKsds(keyLength = 32)
public class UpjtsrpKsdsVsam extends IndexedVsamFile {

	public UpjtsrpKsdsVsam(String name) {
		super(name);
	}

}
