/*
 * Generation Date: Fri, 11 Nov 2011 12:30:20
 * Generated by:    CSC
 * Generated from:  IPSDRCFL
 * 
 * Copyright 2010 CSC, all rights reserved.
 *
 * This software is the proprietary information of CSC.
 * Use is subject to license terms.
*/
 
package com.sears.processing.code.model;

import com.quipoz.framework.datatype.*;
import com.quipoz.COBOLFramework.datatype.ExternalData;
import static com.quipoz.COBOLFramework.COBOLFunctions.*;
import com.quipoz.COBOLFramework.COBOLFunctions;

/**
 * DRCUnit.
 *	
 * @author  CSC
 * @version $Revision: #1 $
 */
public class DRCUnit extends ExternalData {

    /**
     * serialVersionUID required as class is serializable.
     */
    private static final long serialVersionUID = 1L;

  //*******************************
  //Attribute Declarations
  //*******************************
  
  	public FixedLengthStringData ipsdrcflRec = new FixedLengthStringData(80);
  	public FixedLengthStringData ipsdrcflKey = new FixedLengthStringData(7).isAPartOf(ipsdrcflRec, 0);
  	public FixedLengthStringData ipsdrcflSvcUnNo = new FixedLengthStringData(7).isAPartOf(ipsdrcflKey, 0);
  	public FixedLengthStringData ipsdrcflDrcUnNo = new FixedLengthStringData(7).isAPartOf(ipsdrcflRec, 7);
  	public FixedLengthStringData filler = new FixedLengthStringData(66).isAPartOf(ipsdrcflRec, 14, FILLER);


    /**
     * initialize all variables in the class.
     */
	public void initialize() {
		COBOLFunctions.initialize(ipsdrcflRec);
	}	

	
    /**
     * Retrieves the entire copybook as if it was a single string.
     * @return single FixedLengthString
     */
	public FixedLengthStringData getBaseString() {
  		if (baseString == null) {
   			baseString = new FixedLengthStringData(ipsdrcflRec.getLength());
    		ipsdrcflRec.isAPartOf(baseString, true);
   			baseString.resetIsAPartOfOffset();
  		}
  		return baseString;
	}


}