/*
 * Generation Date: Fri, 11 Nov 2011 12:30:20
 * Generated by:    CSC
 * Generated from:  IPSIQCFL
 * 
 * Copyright 2010 CSC, all rights reserved.
 *
 * This software is the proprietary information of CSC.
 * Use is subject to license terms.
*/
 
package com.sears.processing.code.model;

import com.quipoz.framework.datatype.*;
import com.quipoz.COBOLFramework.datatype.ExternalData;
import static com.quipoz.COBOLFramework.COBOLFunctions.*;
import com.quipoz.COBOLFramework.COBOLFunctions;

/**
 * InquiryCommunity.
 *	
 * @author  CSC
 * @version $Revision: #1 $
 */
public class InquiryCommunity extends ExternalData {

    /**
     * serialVersionUID required as class is serializable.
     */
    private static final long serialVersionUID = 1L;

  //*******************************
  //Attribute Declarations
  //*******************************
  
  	public FixedLengthStringData ipsiqcflRecord = new FixedLengthStringData(46);
  	public FixedLengthStringData ipsiqcflKey = new FixedLengthStringData(1).isAPartOf(ipsiqcflRecord, 0);
  	public FixedLengthStringData ipsiqcflInqCmyCd = new FixedLengthStringData(1).isAPartOf(ipsiqcflKey, 0);
  	public FixedLengthStringData ipsiqcflInqCmyNm = new FixedLengthStringData(35).isAPartOf(ipsiqcflRecord, 1);
  	public FixedLengthStringData ipsiqcflValidTargetFl = new FixedLengthStringData(1).isAPartOf(ipsiqcflRecord, 36);
  	public FixedLengthStringData filler = new FixedLengthStringData(9).isAPartOf(ipsiqcflRecord, 37, FILLER);


    /**
     * initialize all variables in the class.
     */
	public void initialize() {
		COBOLFunctions.initialize(ipsiqcflRecord);
	}	

	
    /**
     * Retrieves the entire copybook as if it was a single string.
     * @return single FixedLengthString
     */
	public FixedLengthStringData getBaseString() {
  		if (baseString == null) {
   			baseString = new FixedLengthStringData(ipsiqcflRecord.getLength());
    		ipsiqcflRecord.isAPartOf(baseString, true);
   			baseString.resetIsAPartOfOffset();
  		}
  		return baseString;
	}


}