/*
 * Generation Date: Fri, 11 Nov 2011 12:30:21
 * Generated by:    CSC
 * Generated from:  PSXTUPIN
 * 
 * Copyright 2010 CSC, all rights reserved.
 *
 * This software is the proprietary information of CSC.
 * Use is subject to license terms.
*/
 
package com.sears.processing.code.model;

import com.quipoz.framework.datatype.*;
import com.quipoz.COBOLFramework.datatype.ExternalData;
import static com.quipoz.COBOLFramework.COBOLFunctions.*;
import com.quipoz.COBOLFramework.COBOLFunctions;

/**
 * NewUnitPrinterDefaultValueSetup.
 *	
 * @author  CSC
 * @version $Revision: #1 $
 */
public class NewUnitPrinterDefaultValueSetup extends ExternalData {

    /**
     * serialVersionUID required as class is serializable.
     */
    private static final long serialVersionUID = 1L;

  //*******************************
  //Attribute Declarations
  //*******************************
  
  	public FixedLengthStringData psxtupinTbl = new FixedLengthStringData(434);
  	public FixedLengthStringData psxtupinIns = new FixedLengthStringData(430).isAPartOf(psxtupinTbl, 0);
  	public FixedLengthStringData filler = new FixedLengthStringData(43).isAPartOf(psxtupinIns, 0, FILLER).init("SO1Sears Onsite Printer                    ");
  	public FixedLengthStringData filler1 = new FixedLengthStringData(43).isAPartOf(psxtupinIns, 43, FILLER).init("AO1A&E Onsite Printer                      ");
  	public FixedLengthStringData filler2 = new FixedLengthStringData(43).isAPartOf(psxtupinIns, 86, FILLER).init("SS1Sears Inshop Printer                    ");
  	public FixedLengthStringData filler3 = new FixedLengthStringData(43).isAPartOf(psxtupinIns, 129, FILLER).init("AS1A&E Inshop Printer                      ");
  	public FixedLengthStringData filler4 = new FixedLengthStringData(43).isAPartOf(psxtupinIns, 172, FILLER).init("SS2Sears Inshop Printer 2                  ");
  	public FixedLengthStringData filler5 = new FixedLengthStringData(43).isAPartOf(psxtupinIns, 215, FILLER).init("SS3Sears Inshop Printer 3                  ");
  	public FixedLengthStringData filler6 = new FixedLengthStringData(43).isAPartOf(psxtupinIns, 258, FILLER).init("SS4Sears Inshop Printer 4                  ");
  	public FixedLengthStringData filler7 = new FixedLengthStringData(43).isAPartOf(psxtupinIns, 301, FILLER).init("AS2A&E Inshop Printer 2                    ");
  	public FixedLengthStringData filler8 = new FixedLengthStringData(43).isAPartOf(psxtupinIns, 344, FILLER).init("AS3A&E Inshop Printer 3                    ");
  	public FixedLengthStringData filler9 = new FixedLengthStringData(43).isAPartOf(psxtupinIns, 387, FILLER).init("SR1Sears Report Printer                    ");
  	public FixedLengthStringData psxtupinWsTbl = new FixedLengthStringData(430).isAPartOf(psxtupinIns, 0, REDEFINE);
  	public FixedLengthStringData[] psxtupinWsTbl1 = FLSArrayPartOfStructure(10, 43, psxtupinWsTbl, 0);
  	public FixedLengthStringData[] wsBusOrgCd = FLSDArrayPartOfArrayStructure(1, psxtupinWsTbl1, 0);
  	public FixedLengthStringData[] wsPrnPusCd = FLSDArrayPartOfArrayStructure(1, psxtupinWsTbl1, 1);
  	public FixedLengthStringData[] wsPrnSeqNo = FLSDArrayPartOfArrayStructure(1, psxtupinWsTbl1, 2);
  	public ZonedDecimalData[] wsPrnSeqNoN = ZDArrayPartOfArrayStructure(1, 0, wsPrnSeqNo, 0, REDEFINE, UNSIGNED_TRUE);
  	public FixedLengthStringData[] wsPrnDs = FLSDArrayPartOfArrayStructure(40, psxtupinWsTbl1, 3);
  	public BinaryData psxtupinSub = new BinaryData(4, 0).isAPartOf(psxtupinTbl, 430);
  	public BinaryData psxtupinEntryQt = new BinaryData(4, 0).isAPartOf(psxtupinTbl, 432).init(10);


    /**
     * initialize all variables in the class.
     */
	public void initialize() {
		COBOLFunctions.initialize(psxtupinTbl);
	}	

	
    /**
     * Retrieves the entire copybook as if it was a single string.
     * @return single FixedLengthString
     */
	public FixedLengthStringData getBaseString() {
  		if (baseString == null) {
   			baseString = new FixedLengthStringData(psxtupinTbl.getLength());
    		psxtupinTbl.isAPartOf(baseString, true);
   			baseString.resetIsAPartOfOffset();
  		}
  		return baseString;
	}


}