/*
 * Generation Date: Fri, 11 Nov 2011 12:30:20
 * Generated by:    CSC
 * Generated from:  NPJXTXY
 * 
 * Copyright 2010 CSC, all rights reserved.
 *
 * This software is the proprietary information of CSC.
 * Use is subject to license terms.
*/
 
package com.sears.processing.code.model;

import com.quipoz.framework.datatype.*;
import com.quipoz.COBOLFramework.datatype.ExternalData;
import static com.quipoz.COBOLFramework.COBOLFunctions.*;
import com.quipoz.COBOLFramework.COBOLFunctions;

/**
 * NPGStatesProvices.
 *	
 * @author  CSC
 * @version $Revision: #1 $
 */
public class NPGStatesProvices extends ExternalData {

    /**
     * serialVersionUID required as class is serializable.
     */
    private static final long serialVersionUID = 1L;

  //*******************************
  //Attribute Declarations
  //*******************************
  
  	public FixedLengthStringData dclnpjxtxy = new FixedLengthStringData(110);
  	public FixedLengthStringData xyStPrCode = new FixedLengthStringData(2).isAPartOf(dclnpjxtxy, 0);
  	public FixedLengthStringData xyStPrName = new FixedLengthStringData(25).isAPartOf(dclnpjxtxy, 2);
  	public FixedLengthStringData xyTelAreaCode = new FixedLengthStringData(3).isAPartOf(dclnpjxtxy, 27);
  	public PackedDecimalData xyTimeZoneFacto = new PackedDecimalData(3, 1).isAPartOf(dclnpjxtxy, 30);
  	public PackedDecimalData xyRelTaxCdePos = new PackedDecimalData(2, 0).isAPartOf(dclnpjxtxy, 32);
  	public FixedLengthStringData xyTaxExCertReq = new FixedLengthStringData(1).isAPartOf(dclnpjxtxy, 34);
  	public FixedLengthStringData xyStSolicit = new FixedLengthStringData(1).isAPartOf(dclnpjxtxy, 35);
  	public FixedLengthStringData xyEstimateReq = new FixedLengthStringData(1).isAPartOf(dclnpjxtxy, 36);
  	public FixedLengthStringData xySpTaxInd = new FixedLengthStringData(1).isAPartOf(dclnpjxtxy, 37);
  	public FixedLengthStringData xyCountryCode = new FixedLengthStringData(1).isAPartOf(dclnpjxtxy, 38);
  	public FixedLengthStringData xyCovNonSSdt1 = new FixedLengthStringData(10).isAPartOf(dclnpjxtxy, 39);
  	public FixedLengthStringData xyCovNonSItm1 = new FixedLengthStringData(1).isAPartOf(dclnpjxtxy, 49);
  	public FixedLengthStringData xyCovNonSSdt2 = new FixedLengthStringData(10).isAPartOf(dclnpjxtxy, 50);
  	public FixedLengthStringData xyCovNonSItm2 = new FixedLengthStringData(1).isAPartOf(dclnpjxtxy, 60);
  	public FixedLengthStringData curOblCd = new FixedLengthStringData(3).isAPartOf(dclnpjxtxy, 61);
  	public FixedLengthStringData futOblCd = new FixedLengthStringData(3).isAPartOf(dclnpjxtxy, 64);
  	public FixedLengthStringData futOblEffDt = new FixedLengthStringData(10).isAPartOf(dclnpjxtxy, 67);
  	public FixedLengthStringData lstModId = new FixedLengthStringData(7).isAPartOf(dclnpjxtxy, 77);
  	public FixedLengthStringData lstModTs = new FixedLengthStringData(26).isAPartOf(dclnpjxtxy, 84);


    /**
     * initialize all variables in the class.
     */
	public void initialize() {
		COBOLFunctions.initialize(dclnpjxtxy);
	}	

	
    /**
     * Retrieves the entire copybook as if it was a single string.
     * @return single FixedLengthString
     */
	public FixedLengthStringData getBaseString() {
  		if (baseString == null) {
   			baseString = new FixedLengthStringData(dclnpjxtxy.getLength());
    		dclnpjxtxy.isAPartOf(baseString, true);
   			baseString.resetIsAPartOfOffset();
  		}
  		return baseString;
	}


}