/*
 * Generation Date: Fri, 11 Nov 2011 12:30:20
 * Generated by:    CSC
 * Generated from:  NPJXTXU
 * 
 * Copyright 2010 CSC, all rights reserved.
 *
 * This software is the proprietary information of CSC.
 * Use is subject to license terms.
*/
 
package com.sears.processing.code.model;

import com.quipoz.framework.datatype.*;
import com.quipoz.COBOLFramework.datatype.ExternalData;
import static com.quipoz.COBOLFramework.COBOLFunctions.*;
import com.quipoz.COBOLFramework.COBOLFunctions;

/**
 * NPJServiceUnits.
 *	
 * @author  CSC
 * @version $Revision: #1 $
 */
public class NPJServiceUnits extends ExternalData {

    /**
     * serialVersionUID required as class is serializable.
     */
    private static final long serialVersionUID = 1L;

  //*******************************
  //Attribute Declarations
  //*******************************
  
  	public FixedLengthStringData dclnpjxtxu = new FixedLengthStringData(280);
  	public FixedLengthStringData xuSuNo = new FixedLengthStringData(7).isAPartOf(dclnpjxtxu, 0);
  	public FixedLengthStringData xuSuName = new FixedLengthStringData(27).isAPartOf(dclnpjxtxu, 7);
  	public FixedLengthStringData xuSuAddrL1 = new FixedLengthStringData(30).isAPartOf(dclnpjxtxu, 34);
  	public FixedLengthStringData xuSuAddrL2 = new FixedLengthStringData(30).isAPartOf(dclnpjxtxu, 64);
  	public FixedLengthStringData xuSuCity = new FixedLengthStringData(20).isAPartOf(dclnpjxtxu, 94);
  	public FixedLengthStringData xuSuStateProv = new FixedLengthStringData(2).isAPartOf(dclnpjxtxu, 114);
  	public FixedLengthStringData xuSuZipPc = new FixedLengthStringData(6).isAPartOf(dclnpjxtxu, 116);
  	public FixedLengthStringData xuSuZip8 = new FixedLengthStringData(8).isAPartOf(dclnpjxtxu, 122);
  	public FixedLengthStringData xuSuTelNo = new FixedLengthStringData(10).isAPartOf(dclnpjxtxu, 130);
  	public FixedLengthStringData xuSuPoTelNo = new FixedLengthStringData(10).isAPartOf(dclnpjxtxu, 140);
  	public FixedLengthStringData xuSuStrTelNo = new FixedLengthStringData(10).isAPartOf(dclnpjxtxu, 150);
  	public FixedLengthStringData xuSuInbdTsrTel = new FixedLengthStringData(10).isAPartOf(dclnpjxtxu, 160);
  	public FixedLengthStringData xuSuSStoreNo = new FixedLengthStringData(7).isAPartOf(dclnpjxtxu, 170);
  	public FixedLengthStringData xuSuMrktingInd = new FixedLengthStringData(1).isAPartOf(dclnpjxtxu, 177);
  	public FixedLengthStringData xuSuLocSvceInd = new FixedLengthStringData(1).isAPartOf(dclnpjxtxu, 178);
  	public FixedLengthStringData xuSuCloseDate = new FixedLengthStringData(10).isAPartOf(dclnpjxtxu, 179);
  	public FixedLengthStringData xuSuLangCode = new FixedLengthStringData(1).isAPartOf(dclnpjxtxu, 189);
  	public FixedLengthStringData xuRegionNo = new FixedLengthStringData(7).isAPartOf(dclnpjxtxu, 190);
  	public FixedLengthStringData xuOperateDays = new FixedLengthStringData(7).isAPartOf(dclnpjxtxu, 197);
  	public PackedDecimalData xuOperateHrFr = new PackedDecimalData(4, 0).isAPartOf(dclnpjxtxu, 204);
  	public PackedDecimalData xuOperateHrTo = new PackedDecimalData(4, 0).isAPartOf(dclnpjxtxu, 207);
  	public FixedLengthStringData xuUnitConverted = new FixedLengthStringData(1).isAPartOf(dclnpjxtxu, 210);
  	public PackedDecimalData xuBasicCharge = new PackedDecimalData(5, 2).isAPartOf(dclnpjxtxu, 211);
  	public PackedDecimalData xuPriceLevel = new PackedDecimalData(3, 0).isAPartOf(dclnpjxtxu, 214);
  	public FixedLengthStringData xuLeadReposit = new FixedLengthStringData(1).isAPartOf(dclnpjxtxu, 216);
  	public FixedLengthStringData xuCicsTdqOtc = new FixedLengthStringData(4).isAPartOf(dclnpjxtxu, 217);
  	public FixedLengthStringData xuCicsTdqOs = new FixedLengthStringData(4).isAPartOf(dclnpjxtxu, 221);
  	public FixedLengthStringData xuCicsTdqRpt = new FixedLengthStringData(4).isAPartOf(dclnpjxtxu, 225);
  	public FixedLengthStringData xuStRegisterNo = new FixedLengthStringData(12).isAPartOf(dclnpjxtxu, 229);
  	public FixedLengthStringData xuPartsDepot = new FixedLengthStringData(4).isAPartOf(dclnpjxtxu, 241);
  	public FixedLengthStringData xuSacInd = new FixedLengthStringData(1).isAPartOf(dclnpjxtxu, 245);
  	public FixedLengthStringData xuSacStatsInd = new FixedLengthStringData(1).isAPartOf(dclnpjxtxu, 246);
  	public FixedLengthStringData xuCicsTdqRpt2 = new FixedLengthStringData(4).isAPartOf(dclnpjxtxu, 247);
  	public PackedDecimalData xuAvgTechAm = new PackedDecimalData(5, 2).isAPartOf(dclnpjxtxu, 251);
  	public FixedLengthStringData xuPmCheckInd = new FixedLengthStringData(1).isAPartOf(dclnpjxtxu, 254);
  	public FixedLengthStringData xuMsaInd = new FixedLengthStringData(1).isAPartOf(dclnpjxtxu, 255);
  	public FixedLengthStringData osSvcOrdPrnNo = new FixedLengthStringData(8).isAPartOf(dclnpjxtxu, 256);
  	public FixedLengthStringData isSvcOrdPrnNo = new FixedLengthStringData(8).isAPartOf(dclnpjxtxu, 264);
  	public FixedLengthStringData rptPrnNo = new FixedLengthStringData(8).isAPartOf(dclnpjxtxu, 272);


    /**
     * initialize all variables in the class.
     */
	public void initialize() {
		COBOLFunctions.initialize(dclnpjxtxu);
	}	

	
    /**
     * Retrieves the entire copybook as if it was a single string.
     * @return single FixedLengthString
     */
	public FixedLengthStringData getBaseString() {
  		if (baseString == null) {
   			baseString = new FixedLengthStringData(dclnpjxtxu.getLength());
    		dclnpjxtxu.isAPartOf(baseString, true);
   			baseString.resetIsAPartOfOffset();
  		}
  		return baseString;
	}


}