/*
 * Generation Date: Fri, 11 Nov 2011 12:30:23
 * Generated by:    CSC
 * Generated from:  NPS221.BMS Record: NPS221
 * 
 * Copyright 2011 CSC, all rights reserved.
 *
 * This software is the proprietary information of CSC.
 * Use is subject to license terms.
*/
package com.sears.processing.code.model;

import com.quipoz.framework.datatype.*;
import com.csc.qre.bms.screen.BmsVarModel;
import com.csc.qre.bms.screen.annotations.BmsScreen;
import com.csc.qre.bms.screen.annotations.BmsScreenField;
import com.csc.qre.bms.screen.Color;

/**
 * Nps221ScreenVars acts as the container for passing data 
 * between the screen and the backend business logic
 *	
 * @author  CSC
 * @version $Revision: #1 $
 */
@BmsScreen(group="NPS221$", name="NPS221", view="Nps221Form.jsp")
public class Nps221ScreenVars extends BmsVarModel {

    public FixedLengthStringData nps221Record = new FixedLengthStringData(961);

	
    public BinaryData nps2101Length  = new BinaryData(4,0).isAPartOf(nps221Record, 12);
	
    public FixedLengthStringData nps2101FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 14);

    @BmsScreenField(name="NPS2101", readonly=true, autoskip=true)	
    public FixedLengthStringData nps2101  = new FixedLengthStringData(2).isAPartOf(nps221Record, 15);
	
    public BinaryData nps2102Length  = new BinaryData(4,0).isAPartOf(nps221Record, 17);
	
    public FixedLengthStringData nps2102FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 19);

    @BmsScreenField(name="NPS2102", readonly=true, autoskip=true)	
    public FixedLengthStringData nps2102  = new FixedLengthStringData(8).isAPartOf(nps221Record, 20);
	
    public BinaryData nps2103Length  = new BinaryData(4,0).isAPartOf(nps221Record, 28);
	
    public FixedLengthStringData nps2103FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 30);

    @BmsScreenField(name="NPS2103", readonly=true, autoskip=true)	
    public FixedLengthStringData nps2103  = new FixedLengthStringData(7).isAPartOf(nps221Record, 31);
	
    public BinaryData nps2104Length  = new BinaryData(4,0).isAPartOf(nps221Record, 38);
	
    public FixedLengthStringData nps2104FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 40);

    @BmsScreenField(name="NPS2104", readonly=false, autofocus=true)	
    public FixedLengthStringData nps2104  = new FixedLengthStringData(27).isAPartOf(nps221Record, 41);
	
    public BinaryData nps2105Length  = new BinaryData(4,0).isAPartOf(nps221Record, 68);
	
    public FixedLengthStringData nps2105FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 70);

    @BmsScreenField(name="NPS2105", readonly=false)	
    public FixedLengthStringData nps2105  = new FixedLengthStringData(64).isAPartOf(nps221Record, 71);
	
    public BinaryData nps2106Length  = new BinaryData(4,0).isAPartOf(nps221Record, 135);
	
    public FixedLengthStringData nps2106FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 137);

    @BmsScreenField(name="NPS2106", readonly=false)	
    public FixedLengthStringData nps2106  = new FixedLengthStringData(3).isAPartOf(nps221Record, 138);
	
    public BinaryData nps2107Length  = new BinaryData(4,0).isAPartOf(nps221Record, 141);
	
    public FixedLengthStringData nps2107FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 143);

    @BmsScreenField(name="NPS2107", readonly=false)	
    public FixedLengthStringData nps2107  = new FixedLengthStringData(3).isAPartOf(nps221Record, 144);
	
    public BinaryData nps2108Length  = new BinaryData(4,0).isAPartOf(nps221Record, 147);
	
    public FixedLengthStringData nps2108FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 149);

    @BmsScreenField(name="NPS2108", readonly=false)	
    public FixedLengthStringData nps2108  = new FixedLengthStringData(4).isAPartOf(nps221Record, 150);
	
    public BinaryData nps2109Length  = new BinaryData(4,0).isAPartOf(nps221Record, 154);
	
    public FixedLengthStringData nps2109FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 156);

    @BmsScreenField(name="NPS2109", readonly=false)	
    public FixedLengthStringData nps2109  = new FixedLengthStringData(60).isAPartOf(nps221Record, 157);
	
    public BinaryData nps2110Length  = new BinaryData(4,0).isAPartOf(nps221Record, 217);
	
    public FixedLengthStringData nps2110FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 219);

    @BmsScreenField(name="NPS2110", readonly=false)	
    public FixedLengthStringData nps2110  = new FixedLengthStringData(60).isAPartOf(nps221Record, 220);
	
    public BinaryData nps2111Length  = new BinaryData(4,0).isAPartOf(nps221Record, 280);
	
    public FixedLengthStringData nps2111FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 282);

    @BmsScreenField(name="NPS2111", readonly=false)	
    public FixedLengthStringData nps2111  = new FixedLengthStringData(2).isAPartOf(nps221Record, 283);
	
    public BinaryData nps2112Length  = new BinaryData(4,0).isAPartOf(nps221Record, 285);
	
    public FixedLengthStringData nps2112FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 287);

    @BmsScreenField(name="NPS2112", readonly=false)	
    public FixedLengthStringData nps2112  = new FixedLengthStringData(2).isAPartOf(nps221Record, 288);
	
    public BinaryData nps2113Length  = new BinaryData(4,0).isAPartOf(nps221Record, 290);
	
    public FixedLengthStringData nps2113FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 292);

    @BmsScreenField(name="NPS2113", readonly=false)	
    public FixedLengthStringData nps2113  = new FixedLengthStringData(4).isAPartOf(nps221Record, 293);
	
    public BinaryData nps2114Length  = new BinaryData(4,0).isAPartOf(nps221Record, 297);
	
    public FixedLengthStringData nps2114FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 299);

    @BmsScreenField(name="NPS2114", readonly=false)	
    public FixedLengthStringData nps2114  = new FixedLengthStringData(2).isAPartOf(nps221Record, 300);
	
    public BinaryData nps2115Length  = new BinaryData(4,0).isAPartOf(nps221Record, 302);
	
    public FixedLengthStringData nps2115FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 304);

    @BmsScreenField(name="NPS2115", readonly=false)	
    public FixedLengthStringData nps2115  = new FixedLengthStringData(2).isAPartOf(nps221Record, 305);
	
    public BinaryData nps2116Length  = new BinaryData(4,0).isAPartOf(nps221Record, 307);
	
    public FixedLengthStringData nps2116FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 309);

    @BmsScreenField(name="NPS2116", readonly=false)	
    public FixedLengthStringData nps2116  = new FixedLengthStringData(4).isAPartOf(nps221Record, 310);
	
    public BinaryData nps2117Length  = new BinaryData(4,0).isAPartOf(nps221Record, 314);
	
    public FixedLengthStringData nps2117FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 316);

    @BmsScreenField(name="NPS2117", readonly=false)	
    public FixedLengthStringData nps2117  = new FixedLengthStringData(5).isAPartOf(nps221Record, 317);
	
    public BinaryData nps2118Length  = new BinaryData(4,0).isAPartOf(nps221Record, 322);
	
    public FixedLengthStringData nps2118FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 324);

    @BmsScreenField(name="NPS2118", readonly=false)	
    public FixedLengthStringData nps2118  = new FixedLengthStringData(5).isAPartOf(nps221Record, 325);
	
    public BinaryData nps2119Length  = new BinaryData(4,0).isAPartOf(nps221Record, 330);
	
    public FixedLengthStringData nps2119FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 332);

    @BmsScreenField(name="NPS2119", readonly=false)	
    public FixedLengthStringData nps2119  = new FixedLengthStringData(5).isAPartOf(nps221Record, 333);
	
    public BinaryData nps2120Length  = new BinaryData(4,0).isAPartOf(nps221Record, 338);
	
    public FixedLengthStringData nps2120FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 340);

    @BmsScreenField(name="NPS2120", readonly=false)	
    public FixedLengthStringData nps2120  = new FixedLengthStringData(5).isAPartOf(nps221Record, 341);
	
    public BinaryData nps2121Length  = new BinaryData(4,0).isAPartOf(nps221Record, 346);
	
    public FixedLengthStringData nps2121FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 348);

    @BmsScreenField(name="NPS2121", readonly=false)	
    public FixedLengthStringData nps2121  = new FixedLengthStringData(5).isAPartOf(nps221Record, 349);
	
    public BinaryData nps2122Length  = new BinaryData(4,0).isAPartOf(nps221Record, 354);
	
    public FixedLengthStringData nps2122FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 356);

    @BmsScreenField(name="NPS2122", readonly=false)	
    public FixedLengthStringData nps2122  = new FixedLengthStringData(2).isAPartOf(nps221Record, 357);
	
    public BinaryData nps2123Length  = new BinaryData(4,0).isAPartOf(nps221Record, 359);
	
    public FixedLengthStringData nps2123FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 361);

    @BmsScreenField(name="NPS2123", readonly=false)	
    public FixedLengthStringData nps2123  = new FixedLengthStringData(1).isAPartOf(nps221Record, 362);
	
    public BinaryData nps2124Length  = new BinaryData(4,0).isAPartOf(nps221Record, 363);
	
    public FixedLengthStringData nps2124FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 365);

    @BmsScreenField(name="NPS2124", readonly=true, autoskip=true)	
    public FixedLengthStringData nps2124  = new FixedLengthStringData(3).isAPartOf(nps221Record, 366);
	
    public BinaryData nps2125Length  = new BinaryData(4,0).isAPartOf(nps221Record, 369);
	
    public FixedLengthStringData nps2125FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 371);

    @BmsScreenField(name="NPS2125", readonly=false)	
    public FixedLengthStringData nps2125  = new FixedLengthStringData(2).isAPartOf(nps221Record, 372);
	
    public BinaryData nps2126Length  = new BinaryData(4,0).isAPartOf(nps221Record, 374);
	
    public FixedLengthStringData nps2126FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 376);

    @BmsScreenField(name="NPS2126", readonly=false)	
    public FixedLengthStringData nps2126  = new FixedLengthStringData(2).isAPartOf(nps221Record, 377);
	
    public BinaryData nps2127Length  = new BinaryData(4,0).isAPartOf(nps221Record, 379);
	
    public FixedLengthStringData nps2127FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 381);

    @BmsScreenField(name="NPS2127", readonly=false)	
    public FixedLengthStringData nps2127  = new FixedLengthStringData(1).isAPartOf(nps221Record, 382);
	
    public BinaryData nps2128Length  = new BinaryData(4,0).isAPartOf(nps221Record, 383);
	
    public FixedLengthStringData nps2128FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 385);

    @BmsScreenField(name="NPS2128", readonly=false)	
    public FixedLengthStringData nps2128  = new FixedLengthStringData(2).isAPartOf(nps221Record, 386);
	
    public BinaryData nps2129Length  = new BinaryData(4,0).isAPartOf(nps221Record, 388);
	
    public FixedLengthStringData nps2129FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 390);

    @BmsScreenField(name="NPS2129", readonly=false)	
    public FixedLengthStringData nps2129  = new FixedLengthStringData(2).isAPartOf(nps221Record, 391);
	
    public BinaryData nps2130Length  = new BinaryData(4,0).isAPartOf(nps221Record, 393);
	
    public FixedLengthStringData nps2130FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 395);

    @BmsScreenField(name="NPS2130", readonly=false)	
    public FixedLengthStringData nps2130  = new FixedLengthStringData(1).isAPartOf(nps221Record, 396);
	
    public BinaryData nps2131Length  = new BinaryData(4,0).isAPartOf(nps221Record, 397);
	
    public FixedLengthStringData nps2131FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 399);

    @BmsScreenField(name="NPS2131", readonly=false)	
    public FixedLengthStringData nps2131  = new FixedLengthStringData(2).isAPartOf(nps221Record, 400);
	
    public BinaryData nps2132Length  = new BinaryData(4,0).isAPartOf(nps221Record, 402);
	
    public FixedLengthStringData nps2132FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 404);

    @BmsScreenField(name="NPS2132", readonly=false)	
    public FixedLengthStringData nps2132  = new FixedLengthStringData(2).isAPartOf(nps221Record, 405);
	
    public BinaryData nps2133Length  = new BinaryData(4,0).isAPartOf(nps221Record, 407);
	
    public FixedLengthStringData nps2133FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 409);

    @BmsScreenField(name="NPS2133", readonly=false)	
    public FixedLengthStringData nps2133  = new FixedLengthStringData(1).isAPartOf(nps221Record, 410);
	
    public BinaryData nps2134Length  = new BinaryData(4,0).isAPartOf(nps221Record, 411);
	
    public FixedLengthStringData nps2134FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 413);

    @BmsScreenField(name="NPS2134", readonly=false)	
    public FixedLengthStringData nps2134  = new FixedLengthStringData(2).isAPartOf(nps221Record, 414);
	
    public BinaryData nps2135Length  = new BinaryData(4,0).isAPartOf(nps221Record, 416);
	
    public FixedLengthStringData nps2135FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 418);

    @BmsScreenField(name="NPS2135", readonly=false)	
    public FixedLengthStringData nps2135  = new FixedLengthStringData(2).isAPartOf(nps221Record, 419);
	
    public BinaryData nps2136Length  = new BinaryData(4,0).isAPartOf(nps221Record, 421);
	
    public FixedLengthStringData nps2136FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 423);

    @BmsScreenField(name="NPS2136", readonly=false)	
    public FixedLengthStringData nps2136  = new FixedLengthStringData(1).isAPartOf(nps221Record, 424);
	
    public BinaryData nps2137Length  = new BinaryData(4,0).isAPartOf(nps221Record, 425);
	
    public FixedLengthStringData nps2137FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 427);

    @BmsScreenField(name="NPS2137", readonly=true, autoskip=true)	
    public FixedLengthStringData nps2137  = new FixedLengthStringData(3).isAPartOf(nps221Record, 428);
	
    public BinaryData nps2138Length  = new BinaryData(4,0).isAPartOf(nps221Record, 431);
	
    public FixedLengthStringData nps2138FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 433);

    @BmsScreenField(name="NPS2138", readonly=false)	
    public FixedLengthStringData nps2138  = new FixedLengthStringData(2).isAPartOf(nps221Record, 434);
	
    public BinaryData nps2139Length  = new BinaryData(4,0).isAPartOf(nps221Record, 436);
	
    public FixedLengthStringData nps2139FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 438);

    @BmsScreenField(name="NPS2139", readonly=false)	
    public FixedLengthStringData nps2139  = new FixedLengthStringData(2).isAPartOf(nps221Record, 439);
	
    public BinaryData nps2140Length  = new BinaryData(4,0).isAPartOf(nps221Record, 441);
	
    public FixedLengthStringData nps2140FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 443);

    @BmsScreenField(name="NPS2140", readonly=false)	
    public FixedLengthStringData nps2140  = new FixedLengthStringData(1).isAPartOf(nps221Record, 444);
	
    public BinaryData nps2141Length  = new BinaryData(4,0).isAPartOf(nps221Record, 445);
	
    public FixedLengthStringData nps2141FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 447);

    @BmsScreenField(name="NPS2141", readonly=false)	
    public FixedLengthStringData nps2141  = new FixedLengthStringData(2).isAPartOf(nps221Record, 448);
	
    public BinaryData nps2142Length  = new BinaryData(4,0).isAPartOf(nps221Record, 450);
	
    public FixedLengthStringData nps2142FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 452);

    @BmsScreenField(name="NPS2142", readonly=false)	
    public FixedLengthStringData nps2142  = new FixedLengthStringData(2).isAPartOf(nps221Record, 453);
	
    public BinaryData nps2143Length  = new BinaryData(4,0).isAPartOf(nps221Record, 455);
	
    public FixedLengthStringData nps2143FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 457);

    @BmsScreenField(name="NPS2143", readonly=false)	
    public FixedLengthStringData nps2143  = new FixedLengthStringData(1).isAPartOf(nps221Record, 458);
	
    public BinaryData nps2144Length  = new BinaryData(4,0).isAPartOf(nps221Record, 459);
	
    public FixedLengthStringData nps2144FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 461);

    @BmsScreenField(name="NPS2144", readonly=false)	
    public FixedLengthStringData nps2144  = new FixedLengthStringData(2).isAPartOf(nps221Record, 462);
	
    public BinaryData nps2145Length  = new BinaryData(4,0).isAPartOf(nps221Record, 464);
	
    public FixedLengthStringData nps2145FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 466);

    @BmsScreenField(name="NPS2145", readonly=false)	
    public FixedLengthStringData nps2145  = new FixedLengthStringData(2).isAPartOf(nps221Record, 467);
	
    public BinaryData nps2146Length  = new BinaryData(4,0).isAPartOf(nps221Record, 469);
	
    public FixedLengthStringData nps2146FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 471);

    @BmsScreenField(name="NPS2146", readonly=false)	
    public FixedLengthStringData nps2146  = new FixedLengthStringData(1).isAPartOf(nps221Record, 472);
	
    public BinaryData nps2147Length  = new BinaryData(4,0).isAPartOf(nps221Record, 473);
	
    public FixedLengthStringData nps2147FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 475);

    @BmsScreenField(name="NPS2147", readonly=false)	
    public FixedLengthStringData nps2147  = new FixedLengthStringData(2).isAPartOf(nps221Record, 476);
	
    public BinaryData nps2148Length  = new BinaryData(4,0).isAPartOf(nps221Record, 478);
	
    public FixedLengthStringData nps2148FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 480);

    @BmsScreenField(name="NPS2148", readonly=false)	
    public FixedLengthStringData nps2148  = new FixedLengthStringData(2).isAPartOf(nps221Record, 481);
	
    public BinaryData nps2149Length  = new BinaryData(4,0).isAPartOf(nps221Record, 483);
	
    public FixedLengthStringData nps2149FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 485);

    @BmsScreenField(name="NPS2149", readonly=false)	
    public FixedLengthStringData nps2149  = new FixedLengthStringData(1).isAPartOf(nps221Record, 486);
	
    public BinaryData nps2150Length  = new BinaryData(4,0).isAPartOf(nps221Record, 487);
	
    public FixedLengthStringData nps2150FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 489);

    @BmsScreenField(name="NPS2150", readonly=true, autoskip=true)	
    public FixedLengthStringData nps2150  = new FixedLengthStringData(3).isAPartOf(nps221Record, 490);
	
    public BinaryData nps2151Length  = new BinaryData(4,0).isAPartOf(nps221Record, 493);
	
    public FixedLengthStringData nps2151FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 495);

    @BmsScreenField(name="NPS2151", readonly=false)	
    public FixedLengthStringData nps2151  = new FixedLengthStringData(2).isAPartOf(nps221Record, 496);
	
    public BinaryData nps2152Length  = new BinaryData(4,0).isAPartOf(nps221Record, 498);
	
    public FixedLengthStringData nps2152FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 500);

    @BmsScreenField(name="NPS2152", readonly=false)	
    public FixedLengthStringData nps2152  = new FixedLengthStringData(2).isAPartOf(nps221Record, 501);
	
    public BinaryData nps2153Length  = new BinaryData(4,0).isAPartOf(nps221Record, 503);
	
    public FixedLengthStringData nps2153FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 505);

    @BmsScreenField(name="NPS2153", readonly=false)	
    public FixedLengthStringData nps2153  = new FixedLengthStringData(1).isAPartOf(nps221Record, 506);
	
    public BinaryData nps2154Length  = new BinaryData(4,0).isAPartOf(nps221Record, 507);
	
    public FixedLengthStringData nps2154FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 509);

    @BmsScreenField(name="NPS2154", readonly=false)	
    public FixedLengthStringData nps2154  = new FixedLengthStringData(2).isAPartOf(nps221Record, 510);
	
    public BinaryData nps2155Length  = new BinaryData(4,0).isAPartOf(nps221Record, 512);
	
    public FixedLengthStringData nps2155FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 514);

    @BmsScreenField(name="NPS2155", readonly=false)	
    public FixedLengthStringData nps2155  = new FixedLengthStringData(2).isAPartOf(nps221Record, 515);
	
    public BinaryData nps2156Length  = new BinaryData(4,0).isAPartOf(nps221Record, 517);
	
    public FixedLengthStringData nps2156FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 519);

    @BmsScreenField(name="NPS2156", readonly=false)	
    public FixedLengthStringData nps2156  = new FixedLengthStringData(1).isAPartOf(nps221Record, 520);
	
    public BinaryData nps2157Length  = new BinaryData(4,0).isAPartOf(nps221Record, 521);
	
    public FixedLengthStringData nps2157FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 523);

    @BmsScreenField(name="NPS2157", readonly=false)	
    public FixedLengthStringData nps2157  = new FixedLengthStringData(2).isAPartOf(nps221Record, 524);
	
    public BinaryData nps2158Length  = new BinaryData(4,0).isAPartOf(nps221Record, 526);
	
    public FixedLengthStringData nps2158FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 528);

    @BmsScreenField(name="NPS2158", readonly=false)	
    public FixedLengthStringData nps2158  = new FixedLengthStringData(2).isAPartOf(nps221Record, 529);
	
    public BinaryData nps2159Length  = new BinaryData(4,0).isAPartOf(nps221Record, 531);
	
    public FixedLengthStringData nps2159FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 533);

    @BmsScreenField(name="NPS2159", readonly=false)	
    public FixedLengthStringData nps2159  = new FixedLengthStringData(1).isAPartOf(nps221Record, 534);
	
    public BinaryData nps2160Length  = new BinaryData(4,0).isAPartOf(nps221Record, 535);
	
    public FixedLengthStringData nps2160FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 537);

    @BmsScreenField(name="NPS2160", readonly=false)	
    public FixedLengthStringData nps2160  = new FixedLengthStringData(2).isAPartOf(nps221Record, 538);
	
    public BinaryData nps2161Length  = new BinaryData(4,0).isAPartOf(nps221Record, 540);
	
    public FixedLengthStringData nps2161FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 542);

    @BmsScreenField(name="NPS2161", readonly=false)	
    public FixedLengthStringData nps2161  = new FixedLengthStringData(2).isAPartOf(nps221Record, 543);
	
    public BinaryData nps2162Length  = new BinaryData(4,0).isAPartOf(nps221Record, 545);
	
    public FixedLengthStringData nps2162FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 547);

    @BmsScreenField(name="NPS2162", readonly=false)	
    public FixedLengthStringData nps2162  = new FixedLengthStringData(1).isAPartOf(nps221Record, 548);
	
    public BinaryData nps2163Length  = new BinaryData(4,0).isAPartOf(nps221Record, 549);
	
    public FixedLengthStringData nps2163FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 551);

    @BmsScreenField(name="NPS2163", readonly=true, autoskip=true)	
    public FixedLengthStringData nps2163  = new FixedLengthStringData(3).isAPartOf(nps221Record, 552);
	
    public BinaryData nps2164Length  = new BinaryData(4,0).isAPartOf(nps221Record, 555);
	
    public FixedLengthStringData nps2164FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 557);

    @BmsScreenField(name="NPS2164", readonly=false)	
    public FixedLengthStringData nps2164  = new FixedLengthStringData(2).isAPartOf(nps221Record, 558);
	
    public BinaryData nps2165Length  = new BinaryData(4,0).isAPartOf(nps221Record, 560);
	
    public FixedLengthStringData nps2165FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 562);

    @BmsScreenField(name="NPS2165", readonly=false)	
    public FixedLengthStringData nps2165  = new FixedLengthStringData(2).isAPartOf(nps221Record, 563);
	
    public BinaryData nps2166Length  = new BinaryData(4,0).isAPartOf(nps221Record, 565);
	
    public FixedLengthStringData nps2166FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 567);

    @BmsScreenField(name="NPS2166", readonly=false)	
    public FixedLengthStringData nps2166  = new FixedLengthStringData(1).isAPartOf(nps221Record, 568);
	
    public BinaryData nps2167Length  = new BinaryData(4,0).isAPartOf(nps221Record, 569);
	
    public FixedLengthStringData nps2167FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 571);

    @BmsScreenField(name="NPS2167", readonly=false)	
    public FixedLengthStringData nps2167  = new FixedLengthStringData(2).isAPartOf(nps221Record, 572);
	
    public BinaryData nps2168Length  = new BinaryData(4,0).isAPartOf(nps221Record, 574);
	
    public FixedLengthStringData nps2168FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 576);

    @BmsScreenField(name="NPS2168", readonly=false)	
    public FixedLengthStringData nps2168  = new FixedLengthStringData(2).isAPartOf(nps221Record, 577);
	
    public BinaryData nps2169Length  = new BinaryData(4,0).isAPartOf(nps221Record, 579);
	
    public FixedLengthStringData nps2169FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 581);

    @BmsScreenField(name="NPS2169", readonly=false)	
    public FixedLengthStringData nps2169  = new FixedLengthStringData(1).isAPartOf(nps221Record, 582);
	
    public BinaryData nps2170Length  = new BinaryData(4,0).isAPartOf(nps221Record, 583);
	
    public FixedLengthStringData nps2170FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 585);

    @BmsScreenField(name="NPS2170", readonly=false)	
    public FixedLengthStringData nps2170  = new FixedLengthStringData(2).isAPartOf(nps221Record, 586);
	
    public BinaryData nps2171Length  = new BinaryData(4,0).isAPartOf(nps221Record, 588);
	
    public FixedLengthStringData nps2171FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 590);

    @BmsScreenField(name="NPS2171", readonly=false)	
    public FixedLengthStringData nps2171  = new FixedLengthStringData(2).isAPartOf(nps221Record, 591);
	
    public BinaryData nps2172Length  = new BinaryData(4,0).isAPartOf(nps221Record, 593);
	
    public FixedLengthStringData nps2172FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 595);

    @BmsScreenField(name="NPS2172", readonly=false)	
    public FixedLengthStringData nps2172  = new FixedLengthStringData(1).isAPartOf(nps221Record, 596);
	
    public BinaryData nps2173Length  = new BinaryData(4,0).isAPartOf(nps221Record, 597);
	
    public FixedLengthStringData nps2173FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 599);

    @BmsScreenField(name="NPS2173", readonly=false)	
    public FixedLengthStringData nps2173  = new FixedLengthStringData(2).isAPartOf(nps221Record, 600);
	
    public BinaryData nps2174Length  = new BinaryData(4,0).isAPartOf(nps221Record, 602);
	
    public FixedLengthStringData nps2174FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 604);

    @BmsScreenField(name="NPS2174", readonly=false)	
    public FixedLengthStringData nps2174  = new FixedLengthStringData(2).isAPartOf(nps221Record, 605);
	
    public BinaryData nps2175Length  = new BinaryData(4,0).isAPartOf(nps221Record, 607);
	
    public FixedLengthStringData nps2175FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 609);

    @BmsScreenField(name="NPS2175", readonly=false)	
    public FixedLengthStringData nps2175  = new FixedLengthStringData(1).isAPartOf(nps221Record, 610);
	
    public BinaryData nps2176Length  = new BinaryData(4,0).isAPartOf(nps221Record, 611);
	
    public FixedLengthStringData nps2176FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 613);

    @BmsScreenField(name="NPS2176", readonly=true, autoskip=true)	
    public FixedLengthStringData nps2176  = new FixedLengthStringData(3).isAPartOf(nps221Record, 614);
	
    public BinaryData nps2177Length  = new BinaryData(4,0).isAPartOf(nps221Record, 617);
	
    public FixedLengthStringData nps2177FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 619);

    @BmsScreenField(name="NPS2177", readonly=false)	
    public FixedLengthStringData nps2177  = new FixedLengthStringData(2).isAPartOf(nps221Record, 620);
	
    public BinaryData nps2178Length  = new BinaryData(4,0).isAPartOf(nps221Record, 622);
	
    public FixedLengthStringData nps2178FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 624);

    @BmsScreenField(name="NPS2178", readonly=false)	
    public FixedLengthStringData nps2178  = new FixedLengthStringData(2).isAPartOf(nps221Record, 625);
	
    public BinaryData nps2179Length  = new BinaryData(4,0).isAPartOf(nps221Record, 627);
	
    public FixedLengthStringData nps2179FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 629);

    @BmsScreenField(name="NPS2179", readonly=false)	
    public FixedLengthStringData nps2179  = new FixedLengthStringData(1).isAPartOf(nps221Record, 630);
	
    public BinaryData nps2180Length  = new BinaryData(4,0).isAPartOf(nps221Record, 631);
	
    public FixedLengthStringData nps2180FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 633);

    @BmsScreenField(name="NPS2180", readonly=false)	
    public FixedLengthStringData nps2180  = new FixedLengthStringData(2).isAPartOf(nps221Record, 634);
	
    public BinaryData nps2181Length  = new BinaryData(4,0).isAPartOf(nps221Record, 636);
	
    public FixedLengthStringData nps2181FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 638);

    @BmsScreenField(name="NPS2181", readonly=false)	
    public FixedLengthStringData nps2181  = new FixedLengthStringData(2).isAPartOf(nps221Record, 639);
	
    public BinaryData nps2182Length  = new BinaryData(4,0).isAPartOf(nps221Record, 641);
	
    public FixedLengthStringData nps2182FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 643);

    @BmsScreenField(name="NPS2182", readonly=false)	
    public FixedLengthStringData nps2182  = new FixedLengthStringData(1).isAPartOf(nps221Record, 644);
	
    public BinaryData nps2183Length  = new BinaryData(4,0).isAPartOf(nps221Record, 645);
	
    public FixedLengthStringData nps2183FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 647);

    @BmsScreenField(name="NPS2183", readonly=false)	
    public FixedLengthStringData nps2183  = new FixedLengthStringData(2).isAPartOf(nps221Record, 648);
	
    public BinaryData nps2184Length  = new BinaryData(4,0).isAPartOf(nps221Record, 650);
	
    public FixedLengthStringData nps2184FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 652);

    @BmsScreenField(name="NPS2184", readonly=false)	
    public FixedLengthStringData nps2184  = new FixedLengthStringData(2).isAPartOf(nps221Record, 653);
	
    public BinaryData nps2185Length  = new BinaryData(4,0).isAPartOf(nps221Record, 655);
	
    public FixedLengthStringData nps2185FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 657);

    @BmsScreenField(name="NPS2185", readonly=false)	
    public FixedLengthStringData nps2185  = new FixedLengthStringData(1).isAPartOf(nps221Record, 658);
	
    public BinaryData nps2186Length  = new BinaryData(4,0).isAPartOf(nps221Record, 659);
	
    public FixedLengthStringData nps2186FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 661);

    @BmsScreenField(name="NPS2186", readonly=false)	
    public FixedLengthStringData nps2186  = new FixedLengthStringData(2).isAPartOf(nps221Record, 662);
	
    public BinaryData nps2187Length  = new BinaryData(4,0).isAPartOf(nps221Record, 664);
	
    public FixedLengthStringData nps2187FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 666);

    @BmsScreenField(name="NPS2187", readonly=false)	
    public FixedLengthStringData nps2187  = new FixedLengthStringData(2).isAPartOf(nps221Record, 667);
	
    public BinaryData nps2188Length  = new BinaryData(4,0).isAPartOf(nps221Record, 669);
	
    public FixedLengthStringData nps2188FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 671);

    @BmsScreenField(name="NPS2188", readonly=false)	
    public FixedLengthStringData nps2188  = new FixedLengthStringData(1).isAPartOf(nps221Record, 672);
	
    public BinaryData nps2189Length  = new BinaryData(4,0).isAPartOf(nps221Record, 673);
	
    public FixedLengthStringData nps2189FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 675);

    @BmsScreenField(name="NPS2189", readonly=true, autoskip=true)	
    public FixedLengthStringData nps2189  = new FixedLengthStringData(3).isAPartOf(nps221Record, 676);
	
    public BinaryData nps2190Length  = new BinaryData(4,0).isAPartOf(nps221Record, 679);
	
    public FixedLengthStringData nps2190FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 681);

    @BmsScreenField(name="NPS2190", readonly=false)	
    public FixedLengthStringData nps2190  = new FixedLengthStringData(2).isAPartOf(nps221Record, 682);
	
    public BinaryData nps2191Length  = new BinaryData(4,0).isAPartOf(nps221Record, 684);
	
    public FixedLengthStringData nps2191FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 686);

    @BmsScreenField(name="NPS2191", readonly=false)	
    public FixedLengthStringData nps2191  = new FixedLengthStringData(2).isAPartOf(nps221Record, 687);
	
    public BinaryData nps2192Length  = new BinaryData(4,0).isAPartOf(nps221Record, 689);
	
    public FixedLengthStringData nps2192FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 691);

    @BmsScreenField(name="NPS2192", readonly=false)	
    public FixedLengthStringData nps2192  = new FixedLengthStringData(1).isAPartOf(nps221Record, 692);
	
    public BinaryData nps2193Length  = new BinaryData(4,0).isAPartOf(nps221Record, 693);
	
    public FixedLengthStringData nps2193FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 695);

    @BmsScreenField(name="NPS2193", readonly=false)	
    public FixedLengthStringData nps2193  = new FixedLengthStringData(2).isAPartOf(nps221Record, 696);
	
    public BinaryData nps2194Length  = new BinaryData(4,0).isAPartOf(nps221Record, 698);
	
    public FixedLengthStringData nps2194FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 700);

    @BmsScreenField(name="NPS2194", readonly=false)	
    public FixedLengthStringData nps2194  = new FixedLengthStringData(2).isAPartOf(nps221Record, 701);
	
    public BinaryData nps2195Length  = new BinaryData(4,0).isAPartOf(nps221Record, 703);
	
    public FixedLengthStringData nps2195FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 705);

    @BmsScreenField(name="NPS2195", readonly=false)	
    public FixedLengthStringData nps2195  = new FixedLengthStringData(1).isAPartOf(nps221Record, 706);
	
    public BinaryData nps2196Length  = new BinaryData(4,0).isAPartOf(nps221Record, 707);
	
    public FixedLengthStringData nps2196FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 709);

    @BmsScreenField(name="NPS2196", readonly=false)	
    public FixedLengthStringData nps2196  = new FixedLengthStringData(2).isAPartOf(nps221Record, 710);
	
    public BinaryData nps2197Length  = new BinaryData(4,0).isAPartOf(nps221Record, 712);
	
    public FixedLengthStringData nps2197FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 714);

    @BmsScreenField(name="NPS2197", readonly=false)	
    public FixedLengthStringData nps2197  = new FixedLengthStringData(2).isAPartOf(nps221Record, 715);
	
    public BinaryData nps2198Length  = new BinaryData(4,0).isAPartOf(nps221Record, 717);
	
    public FixedLengthStringData nps2198FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 719);

    @BmsScreenField(name="NPS2198", readonly=false)	
    public FixedLengthStringData nps2198  = new FixedLengthStringData(1).isAPartOf(nps221Record, 720);
	
    public BinaryData nps2199Length  = new BinaryData(4,0).isAPartOf(nps221Record, 721);
	
    public FixedLengthStringData nps2199FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 723);

    @BmsScreenField(name="NPS2199", readonly=false)	
    public FixedLengthStringData nps2199  = new FixedLengthStringData(2).isAPartOf(nps221Record, 724);
	
    public BinaryData nps2200Length  = new BinaryData(4,0).isAPartOf(nps221Record, 726);
	
    public FixedLengthStringData nps2200FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 728);

    @BmsScreenField(name="NPS2200", readonly=false)	
    public FixedLengthStringData nps2200  = new FixedLengthStringData(2).isAPartOf(nps221Record, 729);
	
    public BinaryData nps2201Length  = new BinaryData(4,0).isAPartOf(nps221Record, 731);
	
    public FixedLengthStringData nps2201FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 733);

    @BmsScreenField(name="NPS2201", readonly=false)	
    public FixedLengthStringData nps2201  = new FixedLengthStringData(1).isAPartOf(nps221Record, 734);
	
    public BinaryData nps2202Length  = new BinaryData(4,0).isAPartOf(nps221Record, 735);
	
    public FixedLengthStringData nps2202FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 737);

    @BmsScreenField(name="NPS2202", readonly=true, autoskip=true)	
    public FixedLengthStringData nps2202  = new FixedLengthStringData(3).isAPartOf(nps221Record, 738);
	
    public BinaryData nps2203Length  = new BinaryData(4,0).isAPartOf(nps221Record, 741);
	
    public FixedLengthStringData nps2203FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 743);

    @BmsScreenField(name="NPS2203", readonly=false)	
    public FixedLengthStringData nps2203  = new FixedLengthStringData(2).isAPartOf(nps221Record, 744);
	
    public BinaryData nps2204Length  = new BinaryData(4,0).isAPartOf(nps221Record, 746);
	
    public FixedLengthStringData nps2204FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 748);

    @BmsScreenField(name="NPS2204", readonly=false)	
    public FixedLengthStringData nps2204  = new FixedLengthStringData(2).isAPartOf(nps221Record, 749);
	
    public BinaryData nps2205Length  = new BinaryData(4,0).isAPartOf(nps221Record, 751);
	
    public FixedLengthStringData nps2205FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 753);

    @BmsScreenField(name="NPS2205", readonly=false)	
    public FixedLengthStringData nps2205  = new FixedLengthStringData(1).isAPartOf(nps221Record, 754);
	
    public BinaryData nps2206Length  = new BinaryData(4,0).isAPartOf(nps221Record, 755);
	
    public FixedLengthStringData nps2206FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 757);

    @BmsScreenField(name="NPS2206", readonly=false)	
    public FixedLengthStringData nps2206  = new FixedLengthStringData(2).isAPartOf(nps221Record, 758);
	
    public BinaryData nps2207Length  = new BinaryData(4,0).isAPartOf(nps221Record, 760);
	
    public FixedLengthStringData nps2207FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 762);

    @BmsScreenField(name="NPS2207", readonly=false)	
    public FixedLengthStringData nps2207  = new FixedLengthStringData(2).isAPartOf(nps221Record, 763);
	
    public BinaryData nps2208Length  = new BinaryData(4,0).isAPartOf(nps221Record, 765);
	
    public FixedLengthStringData nps2208FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 767);

    @BmsScreenField(name="NPS2208", readonly=false)	
    public FixedLengthStringData nps2208  = new FixedLengthStringData(1).isAPartOf(nps221Record, 768);
	
    public BinaryData nps2209Length  = new BinaryData(4,0).isAPartOf(nps221Record, 769);
	
    public FixedLengthStringData nps2209FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 771);

    @BmsScreenField(name="NPS2209", readonly=false)	
    public FixedLengthStringData nps2209  = new FixedLengthStringData(2).isAPartOf(nps221Record, 772);
	
    public BinaryData nps2210Length  = new BinaryData(4,0).isAPartOf(nps221Record, 774);
	
    public FixedLengthStringData nps2210FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 776);

    @BmsScreenField(name="NPS2210", readonly=false)	
    public FixedLengthStringData nps2210  = new FixedLengthStringData(2).isAPartOf(nps221Record, 777);
	
    public BinaryData nps2211Length  = new BinaryData(4,0).isAPartOf(nps221Record, 779);
	
    public FixedLengthStringData nps2211FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 781);

    @BmsScreenField(name="NPS2211", readonly=false)	
    public FixedLengthStringData nps2211  = new FixedLengthStringData(1).isAPartOf(nps221Record, 782);
	
    public BinaryData nps2212Length  = new BinaryData(4,0).isAPartOf(nps221Record, 783);
	
    public FixedLengthStringData nps2212FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 785);

    @BmsScreenField(name="NPS2212", readonly=false)	
    public FixedLengthStringData nps2212  = new FixedLengthStringData(2).isAPartOf(nps221Record, 786);
	
    public BinaryData nps2213Length  = new BinaryData(4,0).isAPartOf(nps221Record, 788);
	
    public FixedLengthStringData nps2213FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 790);

    @BmsScreenField(name="NPS2213", readonly=false)	
    public FixedLengthStringData nps2213  = new FixedLengthStringData(2).isAPartOf(nps221Record, 791);
	
    public BinaryData nps2214Length  = new BinaryData(4,0).isAPartOf(nps221Record, 793);
	
    public FixedLengthStringData nps2214FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 795);

    @BmsScreenField(name="NPS2214", readonly=false)	
    public FixedLengthStringData nps2214  = new FixedLengthStringData(1).isAPartOf(nps221Record, 796);
	
    public BinaryData nps2215Length  = new BinaryData(4,0).isAPartOf(nps221Record, 797);
	
    public FixedLengthStringData nps2215FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 799);

    @BmsScreenField(name="NPS2215", readonly=true, highlight=true, autoskip=true)	
    public FixedLengthStringData nps2215  = new FixedLengthStringData(79).isAPartOf(nps221Record, 800);
	
    public BinaryData nps2216Length  = new BinaryData(4,0).isAPartOf(nps221Record, 879);
	
    public FixedLengthStringData nps2216FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps221Record, 881);

    @BmsScreenField(name="NPS2216", readonly=true, highlight=true, autoskip=true)	
    public FixedLengthStringData nps2216  = new FixedLengthStringData(79).isAPartOf(nps221Record, 882);    

    /**
     * Retrieves the Screendata
     * @return single FixedLengthString
     */
	public FixedLengthStringData getScreenData() {
	   return nps221Record;
	}
}
