/*
 * Generation Date: Fri, 11 Nov 2011 12:30:23
 * Generated by:    CSC
 * Generated from:  NPS302.BMS Record: NPS302
 * 
 * Copyright 2011 CSC, all rights reserved.
 *
 * This software is the proprietary information of CSC.
 * Use is subject to license terms.
*/
package com.sears.processing.code.model;

import com.quipoz.framework.datatype.*;
import com.csc.qre.bms.screen.BmsVarModel;
import com.csc.qre.bms.screen.annotations.BmsScreen;
import com.csc.qre.bms.screen.annotations.BmsScreenField;
import com.csc.qre.bms.screen.Color;

/**
 * Nps302ScreenVars acts as the container for passing data 
 * between the screen and the backend business logic
 *	
 * @author  CSC
 * @version $Revision: #1 $
 */
@BmsScreen(group="NPS302$", name="NPS302", view="Nps302Form.jsp")
public class Nps302ScreenVars extends BmsVarModel {

    public FixedLengthStringData nps302Record = new FixedLengthStringData(202);

	
    public BinaryData nps3101Length  = new BinaryData(4,0).isAPartOf(nps302Record, 12);
	
    public FixedLengthStringData nps3101FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps302Record, 14);

    @BmsScreenField(name="NPS3101", readonly=true, autoskip=true)	
    public FixedLengthStringData nps3101  = new FixedLengthStringData(2).isAPartOf(nps302Record, 15);
	
    public BinaryData nps3102Length  = new BinaryData(4,0).isAPartOf(nps302Record, 17);
	
    public FixedLengthStringData nps3102FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps302Record, 19);

    @BmsScreenField(name="NPS3102", readonly=true, autoskip=true)	
    public FixedLengthStringData nps3102  = new FixedLengthStringData(8).isAPartOf(nps302Record, 20);
	
    public BinaryData nps3103Length  = new BinaryData(4,0).isAPartOf(nps302Record, 28);
	
    public FixedLengthStringData nps3103FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps302Record, 30);

    @BmsScreenField(name="NPS3103", readonly=false, autofocus=true)	
    public FixedLengthStringData nps3103  = new FixedLengthStringData(7).isAPartOf(nps302Record, 31);
	
    public BinaryData nps3104Length  = new BinaryData(4,0).isAPartOf(nps302Record, 38);
	
    public FixedLengthStringData nps3104FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps302Record, 40);

    @BmsScreenField(name="NPS3104", readonly=true, highlight=true, autoskip=true)	
    public FixedLengthStringData nps3104  = new FixedLengthStringData(79).isAPartOf(nps302Record, 41);
	
    public BinaryData nps3105Length  = new BinaryData(4,0).isAPartOf(nps302Record, 120);
	
    public FixedLengthStringData nps3105FlagAttr  = new FixedLengthStringData(1).isAPartOf(nps302Record, 122);

    @BmsScreenField(name="NPS3105", readonly=true, highlight=true, autoskip=true)	
    public FixedLengthStringData nps3105  = new FixedLengthStringData(79).isAPartOf(nps302Record, 123);    

    /**
     * Retrieves the Screendata
     * @return single FixedLengthString
     */
	public FixedLengthStringData getScreenData() {
	   return nps302Record;
	}
}
