/*
 * Generation Date: Fri, 11 Nov 2011 12:30:21
 * Generated by:    CSC
 * Generated from:  PD671SS
 * 
 * Copyright 2010 CSC, all rights reserved.
 *
 * This software is the proprietary information of CSC.
 * Use is subject to license terms.
*/
 
package com.sears.processing.code.model;

import com.quipoz.framework.datatype.*;
import com.quipoz.COBOLFramework.datatype.ExternalData;
import static com.quipoz.COBOLFramework.COBOLFunctions.*;
import com.quipoz.COBOLFramework.COBOLFunctions;

/**
 * NPS671ScreenTempArea.
 *	
 * @author  CSC
 * @version $Revision: #1 $
 */
public class NPS671ScreenTempArea extends ExternalData {

    /**
     * serialVersionUID required as class is serializable.
     */
    private static final long serialVersionUID = 1L;

  //*******************************
  //Attribute Declarations
  //*******************************
  
  	public FixedLengthStringData ssNps671Record = new FixedLengthStringData(241);
  	public FixedLengthStringData filler = new FixedLengthStringData(12).isAPartOf(ssNps671Record, 0, FILLER);
  	public FixedLengthStringData scaSsNps671PgmLevel = new FixedLengthStringData(3).isAPartOf(ssNps671Record, 12);
  	public BinaryData ssNps671PgmLevelLen = new BinaryData(4, 0).isAPartOf(scaSsNps671PgmLevel, 0);
  	public FixedLengthStringData ssNps671PgmLevelAttr = new FixedLengthStringData(1).isAPartOf(scaSsNps671PgmLevel, 2);
  	public FixedLengthStringData ssNps671PgmLevel = new FixedLengthStringData(2).isAPartOf(ssNps671Record, 15);
  	public FixedLengthStringData scaSsNps671TdScreenDate = new FixedLengthStringData(3).isAPartOf(ssNps671Record, 17);
  	public BinaryData ssNps671TdScreenDateLen = new BinaryData(4, 0).isAPartOf(scaSsNps671TdScreenDate, 0);
  	public FixedLengthStringData ssNps671TdScreenDateAttr = new FixedLengthStringData(1).isAPartOf(scaSsNps671TdScreenDate, 2);
  	public FixedLengthStringData ssNps671TdScreenDate = new FixedLengthStringData(8).isAPartOf(ssNps671Record, 20);
  	public FixedLengthStringData scaSsNps671SuNo = new FixedLengthStringData(3).isAPartOf(ssNps671Record, 28);
  	public BinaryData ssNps671SuNoLen = new BinaryData(4, 0).isAPartOf(scaSsNps671SuNo, 0);
  	public FixedLengthStringData ssNps671SuNoAttr = new FixedLengthStringData(1).isAPartOf(scaSsNps671SuNo, 2);
  	public FixedLengthStringData ssNps671SuNo = new FixedLengthStringData(7).isAPartOf(ssNps671Record, 31);
  	public FixedLengthStringData scaSsNps671SuName = new FixedLengthStringData(3).isAPartOf(ssNps671Record, 38);
  	public BinaryData ssNps671SuNameLen = new BinaryData(4, 0).isAPartOf(scaSsNps671SuName, 0);
  	public FixedLengthStringData ssNps671SuNameAttr = new FixedLengthStringData(1).isAPartOf(scaSsNps671SuName, 2);
  	public FixedLengthStringData ssNps671SuName = new FixedLengthStringData(27).isAPartOf(ssNps671Record, 41);
  	public FixedLengthStringData scaSsNps671SgnOnMsg = new FixedLengthStringData(3).isAPartOf(ssNps671Record, 68);
  	public BinaryData ssNps671SgnOnMsgLen = new BinaryData(4, 0).isAPartOf(scaSsNps671SgnOnMsg, 0);
  	public FixedLengthStringData ssNps671SgnOnMsgAttr = new FixedLengthStringData(1).isAPartOf(scaSsNps671SgnOnMsg, 2);
  	public FixedLengthStringData ssNps671SgnOnMsg = new FixedLengthStringData(2).isAPartOf(ssNps671Record, 71);
  	public FixedLengthStringData scaSsNps671RfStsCd = new FixedLengthStringData(3).isAPartOf(ssNps671Record, 73);
  	public BinaryData ssNps671RfStsCdLen = new BinaryData(4, 0).isAPartOf(scaSsNps671RfStsCd, 0);
  	public FixedLengthStringData ssNps671RfStsCdAttr = new FixedLengthStringData(1).isAPartOf(scaSsNps671RfStsCd, 2);
  	public FixedLengthStringData ssNps671RfStsCd = new FixedLengthStringData(1).isAPartOf(ssNps671Record, 76);
  	public FixedLengthStringData scaSsNps671Msg = new FixedLengthStringData(3).isAPartOf(ssNps671Record, 77);
  	public BinaryData ssNps671MsgLen = new BinaryData(4, 0).isAPartOf(scaSsNps671Msg, 0);
  	public FixedLengthStringData ssNps671MsgAttr = new FixedLengthStringData(1).isAPartOf(scaSsNps671Msg, 2);
  	public FixedLengthStringData ssNps671Msg = new FixedLengthStringData(79).isAPartOf(ssNps671Record, 80);
  	public FixedLengthStringData scaSsNps671Msg2 = new FixedLengthStringData(3).isAPartOf(ssNps671Record, 159);
  	public BinaryData ssNps671Msg2Len = new BinaryData(4, 0).isAPartOf(scaSsNps671Msg2, 0);
  	public FixedLengthStringData ssNps671Msg2Attr = new FixedLengthStringData(1).isAPartOf(scaSsNps671Msg2, 2);
  	public FixedLengthStringData ssNps671Msg2 = new FixedLengthStringData(79).isAPartOf(ssNps671Record, 162);


    /**
     * initialize all variables in the class.
     */
	public void initialize() {
		COBOLFunctions.initialize(ssNps671Record);
	}	

	
    /**
     * Retrieves the entire copybook as if it was a single string.
     * @return single FixedLengthString
     */
	public FixedLengthStringData getBaseString() {
  		if (baseString == null) {
   			baseString = new FixedLengthStringData(ssNps671Record.getLength());
    		ssNps671Record.isAPartOf(baseString, true);
   			baseString.resetIsAPartOfOffset();
  		}
  		return baseString;
	}


}