/*
 * Generation Date: Fri, 11 Nov 2011 12:30:21
 * Generated by:    CSC
 * Generated from:  NPSXTBU
 * 
 * Copyright 2010 CSC, all rights reserved.
 *
 * This software is the proprietary information of CSC.
 * Use is subject to license terms.
*/
 
package com.sears.processing.code.model;

import com.quipoz.framework.datatype.*;
import com.quipoz.COBOLFramework.datatype.ExternalData;
import static com.quipoz.COBOLFramework.COBOLFunctions.*;
import com.quipoz.COBOLFramework.COBOLFunctions;

/**
 * NPSBasUnits.
 *	
 * @author  CSC
 * @version $Revision: #1 $
 */
public class NPSBasUnits extends ExternalData {

    /**
     * serialVersionUID required as class is serializable.
     */
    private static final long serialVersionUID = 1L;

  //*******************************
  //Attribute Declarations
  //*******************************
  
  	public FixedLengthStringData dclnpsxtbu = new FixedLengthStringData(209);
  	public FixedLengthStringData unNo = new FixedLengthStringData(7).isAPartOf(dclnpsxtbu, 0);
  	public FixedLengthStringData unTypCd = new FixedLengthStringData(3).isAPartOf(dclnpsxtbu, 7);
  	public FixedLengthStringData unNm = new FixedLengthStringData(27).isAPartOf(dclnpsxtbu, 10);
  	public FixedLengthStringData unLn1Ad = new FixedLengthStringData(30).isAPartOf(dclnpsxtbu, 37);
  	public FixedLengthStringData unLn2Ad = new FixedLengthStringData(30).isAPartOf(dclnpsxtbu, 67);
  	public FixedLengthStringData unCtyNm = new FixedLengthStringData(20).isAPartOf(dclnpsxtbu, 97);
  	public FixedLengthStringData unSteCd = new FixedLengthStringData(2).isAPartOf(dclnpsxtbu, 117);
  	public FixedLengthStringData zipCd = new FixedLengthStringData(5).isAPartOf(dclnpsxtbu, 119);
  	public FixedLengthStringData zipSufCd = new FixedLengthStringData(4).isAPartOf(dclnpsxtbu, 124);
  	public FixedLengthStringData prtDptNo = new FixedLengthStringData(4).isAPartOf(dclnpsxtbu, 128);
  	public FixedLengthStringData fldNo = new FixedLengthStringData(7).isAPartOf(dclnpsxtbu, 132);
  	public FixedLengthStringData rgnNo = new FixedLengthStringData(7).isAPartOf(dclnpsxtbu, 139);
  	public FixedLengthStringData ctrSvcUnNo = new FixedLengthStringData(7).isAPartOf(dclnpsxtbu, 146);
  	public FixedLengthStringData altRprUnNo = new FixedLengthStringData(7).isAPartOf(dclnpsxtbu, 153);
  	public PackedDecimalData mktPrcLvlCd = new PackedDecimalData(3, 0).isAPartOf(dclnpsxtbu, 160);
  	public FixedLengthStringData mktUnInbPhnNo = new FixedLengthStringData(10).isAPartOf(dclnpsxtbu, 162);
  	public FixedLengthStringData taxGeoCd = new FixedLengthStringData(9).isAPartOf(dclnpsxtbu, 172);
  	public FixedLengthStringData bchUpdDt = new FixedLengthStringData(10).isAPartOf(dclnpsxtbu, 181);
  	public FixedLengthStringData taxCnyCd = new FixedLengthStringData(3).isAPartOf(dclnpsxtbu, 191);
  	public FixedLengthStringData inqCmyCd = new FixedLengthStringData(1).isAPartOf(dclnpsxtbu, 194);
  	public FixedLengthStringData rteUnNo = new FixedLengthStringData(7).isAPartOf(dclnpsxtbu, 195);
  	public FixedLengthStringData rfsUnNo = new FixedLengthStringData(7).isAPartOf(dclnpsxtbu, 202);


    /**
     * initialize all variables in the class.
     */
	public void initialize() {
		COBOLFunctions.initialize(dclnpsxtbu);
	}	

	
    /**
     * Retrieves the entire copybook as if it was a single string.
     * @return single FixedLengthString
     */
	public FixedLengthStringData getBaseString() {
  		if (baseString == null) {
   			baseString = new FixedLengthStringData(dclnpsxtbu.getLength());
    		dclnpsxtbu.isAPartOf(baseString, true);
   			baseString.resetIsAPartOfOffset();
  		}
  		return baseString;
	}


}