/*
 * Generation Date: Fri, 11 Nov 2011 12:30:21
 * Generated by:    CSC
 * Generated from:  NPSXTCI
 * 
 * Copyright 2010 CSC, all rights reserved.
 *
 * This software is the proprietary information of CSC.
 * Use is subject to license terms.
*/
 
package com.sears.processing.code.model;

import com.quipoz.framework.datatype.*;
import com.quipoz.COBOLFramework.datatype.ExternalData;
import static com.quipoz.COBOLFramework.COBOLFunctions.*;
import com.quipoz.COBOLFramework.COBOLFunctions;

/**
 * NPSCallLoad.
 *	
 * @author  CSC
 * @version $Revision: #1 $
 */
public class NPSCallLoad extends ExternalData {

    /**
     * serialVersionUID required as class is serializable.
     */
    private static final long serialVersionUID = 1L;

  //*******************************
  //Attribute Declarations
  //*******************************
  
  	public FixedLengthStringData dclnpsxtci = new FixedLengthStringData(44);
  	public FixedLengthStringData svcUnNo = new FixedLengthStringData(7).isAPartOf(dclnpsxtci, 0);
  	public FixedLengthStringData wrkAreCd = new FixedLengthStringData(3).isAPartOf(dclnpsxtci, 7);
  	public FixedLengthStringData calLdAreNm = new FixedLengthStringData(7).isAPartOf(dclnpsxtci, 10);
  	public FixedLengthStringData allDayFl = new FixedLengthStringData(1).isAPartOf(dclnpsxtci, 17);
  	public FixedLengthStringData prtTfrUnNo = new FixedLengthStringData(7).isAPartOf(dclnpsxtci, 18);
  	public FixedLengthStringData altFrmTm = new FixedLengthStringData(8).isAPartOf(dclnpsxtci, 25);
  	public FixedLengthStringData altToTm = new FixedLengthStringData(8).isAPartOf(dclnpsxtci, 33);
  	public FixedLengthStringData mnFl = new FixedLengthStringData(1).isAPartOf(dclnpsxtci, 41);
  	public FixedLengthStringData tirPrcSchNo = new FixedLengthStringData(2).isAPartOf(dclnpsxtci, 42);


    /**
     * initialize all variables in the class.
     */
	public void initialize() {
		COBOLFunctions.initialize(dclnpsxtci);
	}	

	
    /**
     * Retrieves the entire copybook as if it was a single string.
     * @return single FixedLengthString
     */
	public FixedLengthStringData getBaseString() {
  		if (baseString == null) {
   			baseString = new FixedLengthStringData(dclnpsxtci.getLength());
    		dclnpsxtci.isAPartOf(baseString, true);
   			baseString.resetIsAPartOfOffset();
  		}
  		return baseString;
	}


}