/*
 * Generation Date: Fri, 11 Nov 2011 12:30:21
 * Generated by:    CSC
 * Generated from:  NPSXTEA
 * 
 * Copyright 2010 CSC, all rights reserved.
 *
 * This software is the proprietary information of CSC.
 * Use is subject to license terms.
*/
 
package com.sears.processing.code.model;

import com.quipoz.framework.datatype.*;
import com.quipoz.COBOLFramework.datatype.ExternalData;
import static com.quipoz.COBOLFramework.COBOLFunctions.*;
import com.quipoz.COBOLFramework.COBOLFunctions;

/**
 * NPSEmergencyArea.
 *	
 * @author  CSC
 * @version $Revision: #1 $
 */
public class NPSEmergencyArea extends ExternalData {

    /**
     * serialVersionUID required as class is serializable.
     */
    private static final long serialVersionUID = 1L;

  //*******************************
  //Attribute Declarations
  //*******************************
  
  	public FixedLengthStringData dclnpsxtea = new FixedLengthStringData(34);
  	public FixedLengthStringData svcUnNo = new FixedLengthStringData(7).isAPartOf(dclnpsxtea, 0);
  	public FixedLengthStringData wrkAreCd = new FixedLengthStringData(3).isAPartOf(dclnpsxtea, 7);
  	public FixedLengthStringData emrCntAreNm = new FixedLengthStringData(7).isAPartOf(dclnpsxtea, 10);
  	public FixedLengthStringData emrCalHdlFl = new FixedLengthStringData(1).isAPartOf(dclnpsxtea, 17);
  	public FixedLengthStringData notOprFrmTm = new FixedLengthStringData(8).isAPartOf(dclnpsxtea, 18);
  	public FixedLengthStringData notOprToTm = new FixedLengthStringData(8).isAPartOf(dclnpsxtea, 26);


    /**
     * initialize all variables in the class.
     */
	public void initialize() {
		COBOLFunctions.initialize(dclnpsxtea);
	}	

	
    /**
     * Retrieves the entire copybook as if it was a single string.
     * @return single FixedLengthString
     */
	public FixedLengthStringData getBaseString() {
  		if (baseString == null) {
   			baseString = new FixedLengthStringData(dclnpsxtea.getLength());
    		dclnpsxtea.isAPartOf(baseString, true);
   			baseString.resetIsAPartOfOffset();
  		}
  		return baseString;
	}


}