/*
 * Generation Date: Fri, 11 Nov 2011 12:30:21
 * Generated by:    CSC
 * Generated from:  NPSXTSU
 * 
 * Copyright 2010 CSC, all rights reserved.
 *
 * This software is the proprietary information of CSC.
 * Use is subject to license terms.
*/
 
package com.sears.processing.code.model;

import com.quipoz.framework.datatype.*;
import com.quipoz.COBOLFramework.datatype.ExternalData;
import static com.quipoz.COBOLFramework.COBOLFunctions.*;
import com.quipoz.COBOLFramework.COBOLFunctions;

/**
 * NPSServiceUnits.
 *	
 * @author  CSC
 * @version $Revision: #1 $
 */
public class NPSServiceUnits extends ExternalData {

    /**
     * serialVersionUID required as class is serializable.
     */
    private static final long serialVersionUID = 1L;

  //*******************************
  //Attribute Declarations
  //*******************************
  
  	public FixedLengthStringData dclnpsxtsu = new FixedLengthStringData(281);
  	public FixedLengthStringData svcUnNo = new FixedLengthStringData(7).isAPartOf(dclnpsxtsu, 0);
  	public FixedLengthStringData svcUnPhnNo = new FixedLengthStringData(10).isAPartOf(dclnpsxtsu, 7);
  	public FixedLengthStringData ctrCalPhnNo = new FixedLengthStringData(10).isAPartOf(dclnpsxtsu, 17);
  	public FixedLengthStringData bscPhnNo = new FixedLengthStringData(10).isAPartOf(dclnpsxtsu, 27);
  	public FixedLengthStringData hipsPhnNo = new FixedLengthStringData(10).isAPartOf(dclnpsxtsu, 37);
  	public FixedLengthStringData ipocPhnNo = new FixedLengthStringData(10).isAPartOf(dclnpsxtsu, 47);
  	public FixedLengthStringData svcUnCloDt = new FixedLengthStringData(10).isAPartOf(dclnpsxtsu, 57);
  	public FixedLengthStringData svcUnCnvFl = new FixedLengthStringData(1).isAPartOf(dclnpsxtsu, 67);
  	public FixedLengthStringData svcUnTvlIstDs = new FixedLengthStringData(64).isAPartOf(dclnpsxtsu, 68);
  	public FixedLengthStringData steRegNo = new FixedLengthStringData(12).isAPartOf(dclnpsxtsu, 132);
  	public FixedLengthStringData sacFl = new FixedLengthStringData(1).isAPartOf(dclnpsxtsu, 144);
  	public FixedLengthStringData sacStatsFl = new FixedLengthStringData(1).isAPartOf(dclnpsxtsu, 145);
  	public FixedLengthStringData pntMtcCkFl = new FixedLengthStringData(1).isAPartOf(dclnpsxtsu, 146);
  	public FixedLengthStringData cpuAidRteFl = new FixedLengthStringData(1).isAPartOf(dclnpsxtsu, 147);
  	public FixedLengthStringData osSvcOrdPrnNo = new FixedLengthStringData(8).isAPartOf(dclnpsxtsu, 148);
  	public FixedLengthStringData isSvcOrdPrnNo = new FixedLengthStringData(8).isAPartOf(dclnpsxtsu, 156);
  	public FixedLengthStringData rptPrnNo = new FixedLengthStringData(8).isAPartOf(dclnpsxtsu, 164);
  	public FixedLengthStringData spdeSvcUnFl = new FixedLengthStringData(1).isAPartOf(dclnpsxtsu, 172);
  	public FixedLengthStringData aumDwdCd = new FixedLengthStringData(1).isAPartOf(dclnpsxtsu, 173);
  	public FixedLengthStringData aumUpdCd = new FixedLengthStringData(1).isAPartOf(dclnpsxtsu, 174);
  	public FixedLengthStringData rfStsCd = new FixedLengthStringData(1).isAPartOf(dclnpsxtsu, 175);
  	public FixedLengthStringData sigOnMsgNo = new FixedLengthStringData(2).isAPartOf(dclnpsxtsu, 176);
  	public FixedLengthStringData hosSvcUnNo = new FixedLengthStringData(7).isAPartOf(dclnpsxtsu, 178);
  	public FixedLengthStringData prnInd = new FixedLengthStringData(1).isAPartOf(dclnpsxtsu, 185);
  	public FixedLengthStringData posStaDt = new FixedLengthStringData(10).isAPartOf(dclnpsxtsu, 186);
  	public FixedLengthStringData posTrsNo = new FixedLengthStringData(4).isAPartOf(dclnpsxtsu, 196);
  	public FixedLengthStringData posRegNo = new FixedLengthStringData(3).isAPartOf(dclnpsxtsu, 200);
  	public FixedLengthStringData posSeqNo = new FixedLengthStringData(3).isAPartOf(dclnpsxtsu, 203);
  	public FixedLengthStringData posUnNo = new FixedLengthStringData(7).isAPartOf(dclnpsxtsu, 206);
  	public FixedLengthStringData prtShCd = new FixedLengthStringData(1).isAPartOf(dclnpsxtsu, 213);
  	public FixedLengthStringData isSvcOrdPr2No = new FixedLengthStringData(8).isAPartOf(dclnpsxtsu, 214);
  	public FixedLengthStringData svcPvdFl = new FixedLengthStringData(1).isAPartOf(dclnpsxtsu, 222);
  	public FixedLengthStringData mktAtvFl = new FixedLengthStringData(1).isAPartOf(dclnpsxtsu, 223);
  	public FixedLengthStringData unOpnDt = new FixedLengthStringData(10).isAPartOf(dclnpsxtsu, 224);
  	public FixedLengthStringData cnvSpdeDt = new FixedLengthStringData(10).isAPartOf(dclnpsxtsu, 234);
  	public FixedLengthStringData cnvNpnDt = new FixedLengthStringData(10).isAPartOf(dclnpsxtsu, 244);
  	public FixedLengthStringData cnvCarsDt = new FixedLengthStringData(10).isAPartOf(dclnpsxtsu, 254);
  	public PackedDecimalData fgnStrPrtMkuPc = new PackedDecimalData(4, 1).isAPartOf(dclnpsxtsu, 264);
  	public FixedLengthStringData prtInvCryFl = new FixedLengthStringData(1).isAPartOf(dclnpsxtsu, 267);
  	public PackedDecimalData prmShpPrtMkuPc = new PackedDecimalData(4, 1).isAPartOf(dclnpsxtsu, 268);
  	public PackedDecimalData prmSitPrtMkuPc = new PackedDecimalData(4, 1).isAPartOf(dclnpsxtsu, 271);
  	public FixedLengthStringData jvSvcUnNo = new FixedLengthStringData(7).isAPartOf(dclnpsxtsu, 274);


    /**
     * initialize all variables in the class.
     */
	public void initialize() {
		COBOLFunctions.initialize(dclnpsxtsu);
	}	

	
    /**
     * Retrieves the entire copybook as if it was a single string.
     * @return single FixedLengthString
     */
	public FixedLengthStringData getBaseString() {
  		if (baseString == null) {
   			baseString = new FixedLengthStringData(dclnpsxtsu.getLength());
    		dclnpsxtsu.isAPartOf(baseString, true);
   			baseString.resetIsAPartOfOffset();
  		}
  		return baseString;
	}


}