/*
 * Generation Date: Fri, 11 Nov 2011 12:30:21
 * Generated by:    CSC
 * Generated from:  NPSXTSC
 * 
 * Copyright 2010 CSC, all rights reserved.
 *
 * This software is the proprietary information of CSC.
 * Use is subject to license terms.
*/
 
package com.sears.processing.code.model;

import com.quipoz.framework.datatype.*;
import com.quipoz.COBOLFramework.datatype.ExternalData;
import static com.quipoz.COBOLFramework.COBOLFunctions.*;
import com.quipoz.COBOLFramework.COBOLFunctions;

/**
 * NPSServiceUnitCharges.
 *	
 * @author  CSC
 * @version $Revision: #1 $
 */
public class NPSServiceUnitCharges extends ExternalData {

    /**
     * serialVersionUID required as class is serializable.
     */
    private static final long serialVersionUID = 1L;

  //*******************************
  //Attribute Declarations
  //*******************************
  
  	public FixedLengthStringData dclnpsxtsc = new FixedLengthStringData(21);
  	public FixedLengthStringData svcUnNo = new FixedLengthStringData(7).isAPartOf(dclnpsxtsc, 0);
  	public PackedDecimalData avgTecHrsRt = new PackedDecimalData(5, 2).isAPartOf(dclnpsxtsc, 7);
  	public PackedDecimalData hmeSvcCrgAm = new PackedDecimalData(5, 2).isAPartOf(dclnpsxtsc, 10);
  	public PackedDecimalData altHmeSvcCrgAm = new PackedDecimalData(5, 2).isAPartOf(dclnpsxtsc, 13);
  	public PackedDecimalData shoSvcCrgAm = new PackedDecimalData(5, 2).isAPartOf(dclnpsxtsc, 16);
  	public FixedLengthStringData tirPrcSchNo = new FixedLengthStringData(2).isAPartOf(dclnpsxtsc, 19);


    /**
     * initialize all variables in the class.
     */
	public void initialize() {
		COBOLFunctions.initialize(dclnpsxtsc);
	}	

	
    /**
     * Retrieves the entire copybook as if it was a single string.
     * @return single FixedLengthString
     */
	public FixedLengthStringData getBaseString() {
  		if (baseString == null) {
   			baseString = new FixedLengthStringData(dclnpsxtsc.getLength());
    		dclnpsxtsc.isAPartOf(baseString, true);
   			baseString.resetIsAPartOfOffset();
  		}
  		return baseString;
	}


}