/*
 * Generation Date: Fri, 11 Nov 2011 12:30:21
 * Generated by:    CSC
 * Generated from:  NPSXTTP
 * 
 * Copyright 2010 CSC, all rights reserved.
 *
 * This software is the proprietary information of CSC.
 * Use is subject to license terms.
*/
 
package com.sears.processing.code.model;

import com.quipoz.framework.datatype.*;
import com.quipoz.COBOLFramework.datatype.ExternalData;
import static com.quipoz.COBOLFramework.COBOLFunctions.*;
import com.quipoz.COBOLFramework.COBOLFunctions;

/**
 * NPSTierPricingSchedule.
 *	
 * @author  CSC
 * @version $Revision: #1 $
 */
public class NPSTierPricingSchedule extends ExternalData {

    /**
     * serialVersionUID required as class is serializable.
     */
    private static final long serialVersionUID = 1L;

  //*******************************
  //Attribute Declarations
  //*******************************
  
  	public FixedLengthStringData dclnpsxttp = new FixedLengthStringData(10);
  	public FixedLengthStringData tirPrcSchNo = new FixedLengthStringData(2).isAPartOf(dclnpsxttp, 0);
  	public FixedLengthStringData mdsPrcTirCd = new FixedLengthStringData(1).isAPartOf(dclnpsxttp, 2);
  	public FixedLengthStringData jobCdCrgCd = new FixedLengthStringData(1).isAPartOf(dclnpsxttp, 3);
  	public PackedDecimalData crgCdAm = new PackedDecimalData(5, 2).isAPartOf(dclnpsxttp, 4);
  	public PackedDecimalData crgCdNrelAm = new PackedDecimalData(5, 2).isAPartOf(dclnpsxttp, 7);


    /**
     * initialize all variables in the class.
     */
	public void initialize() {
		COBOLFunctions.initialize(dclnpsxttp);
	}	

	
    /**
     * Retrieves the entire copybook as if it was a single string.
     * @return single FixedLengthString
     */
	public FixedLengthStringData getBaseString() {
  		if (baseString == null) {
   			baseString = new FixedLengthStringData(dclnpsxttp.getLength());
    		dclnpsxttp.isAPartOf(baseString, true);
   			baseString.resetIsAPartOfOffset();
  		}
  		return baseString;
	}


}