/*
 * Generation Date: Fri, 11 Nov 2011 12:30:21
 * Generated by:    CSC
 * Generated from:  NPSXTSS
 * 
 * Copyright 2010 CSC, all rights reserved.
 *
 * This software is the proprietary information of CSC.
 * Use is subject to license terms.
*/
 
package com.sears.processing.code.model;

import com.quipoz.framework.datatype.*;
import com.quipoz.COBOLFramework.datatype.ExternalData;
import static com.quipoz.COBOLFramework.COBOLFunctions.*;
import com.quipoz.COBOLFramework.COBOLFunctions;

/**
 * NPSUnitSchedule.
 *	
 * @author  CSC
 * @version $Revision: #1 $
 */
public class NPSUnitSchedule extends ExternalData {

    /**
     * serialVersionUID required as class is serializable.
     */
    private static final long serialVersionUID = 1L;

  //*******************************
  //Attribute Declarations
  //*******************************
  
  	public FixedLengthStringData dclnpsxtss = new FixedLengthStringData(16);
  	public FixedLengthStringData svcUnNo = new FixedLengthStringData(7).isAPartOf(dclnpsxtss, 0);
  	public FixedLengthStringData schTypCd = new FixedLengthStringData(2).isAPartOf(dclnpsxtss, 7);
  	public FixedLengthStringData oprDayCd = new FixedLengthStringData(1).isAPartOf(dclnpsxtss, 9);
  	public PackedDecimalData oprFrmTm = new PackedDecimalData(4, 0).isAPartOf(dclnpsxtss, 10);
  	public PackedDecimalData oprToTm = new PackedDecimalData(4, 0).isAPartOf(dclnpsxtss, 13);


    /**
     * initialize all variables in the class.
     */
	public void initialize() {
		COBOLFunctions.initialize(dclnpsxtss);
	}	

	
    /**
     * Retrieves the entire copybook as if it was a single string.
     * @return single FixedLengthString
     */
	public FixedLengthStringData getBaseString() {
  		if (baseString == null) {
   			baseString = new FixedLengthStringData(dclnpsxtss.getLength());
    		dclnpsxtss.isAPartOf(baseString, true);
   			baseString.resetIsAPartOfOffset();
  		}
  		return baseString;
	}


}