/*
 * Generation Date: Fri, 11 Nov 2011 12:30:21
 * Generated by:    CSC
 * Generated from:  NPSXTUP
 * 
 * Copyright 2010 CSC, all rights reserved.
 *
 * This software is the proprietary information of CSC.
 * Use is subject to license terms.
*/
 
package com.sears.processing.code.model;

import com.quipoz.framework.datatype.*;
import com.quipoz.COBOLFramework.datatype.ExternalData;
import static com.quipoz.COBOLFramework.COBOLFunctions.*;
import com.quipoz.COBOLFramework.COBOLFunctions;

/**
 * NPSUnitPrinter.
 *	
 * @author  CSC
 * @version $Revision: #1 $
 */
public class NPSUnitPrinter extends ExternalData {

    /**
     * serialVersionUID required as class is serializable.
     */
    private static final long serialVersionUID = 1L;

  //*******************************
  //Attribute Declarations
  //*******************************
  
  	public FixedLengthStringData dclnpsxtup = new FixedLengthStringData(61);
  	public FixedLengthStringData svcUnNo = new FixedLengthStringData(7).isAPartOf(dclnpsxtup, 0);
  	public FixedLengthStringData busOrgCd = new FixedLengthStringData(1).isAPartOf(dclnpsxtup, 7);
  	public FixedLengthStringData prnPusCd = new FixedLengthStringData(1).isAPartOf(dclnpsxtup, 8);
  	public BinaryData prnSeqNo = new BinaryData(9, 0).isAPartOf(dclnpsxtup, 9);
  	public FixedLengthStringData prnIdNo = new FixedLengthStringData(8).isAPartOf(dclnpsxtup, 13);
  	public FixedLengthStringData prnDs = new FixedLengthStringData(40).isAPartOf(dclnpsxtup, 21);


    /**
     * initialize all variables in the class.
     */
	public void initialize() {
		COBOLFunctions.initialize(dclnpsxtup);
	}	

	
    /**
     * Retrieves the entire copybook as if it was a single string.
     * @return single FixedLengthString
     */
	public FixedLengthStringData getBaseString() {
  		if (baseString == null) {
   			baseString = new FixedLengthStringData(dclnpsxtup.getLength());
    		dclnpsxtup.isAPartOf(baseString, true);
   			baseString.resetIsAPartOfOffset();
  		}
  		return baseString;
	}


}