/*
 * Generation Date: Fri, 11 Nov 2011 12:30:22
 * Generated by:    CSC
 * Generated from:  SPDESMSG
 * 
 * Copyright 2010 CSC, all rights reserved.
 *
 * This software is the proprietary information of CSC.
 * Use is subject to license terms.
*/
 
package com.sears.processing.code.model;

import com.quipoz.framework.datatype.*;
import com.quipoz.COBOLFramework.datatype.ExternalData;
import static com.quipoz.COBOLFramework.COBOLFunctions.*;
import com.quipoz.COBOLFramework.COBOLFunctions;

/**
 * SPDESignonMessages.
 *	
 * @author  CSC
 * @version $Revision: #1 $
 */
public class SPDESignonMessages extends ExternalData {

    /**
     * serialVersionUID required as class is serializable.
     */
    private static final long serialVersionUID = 1L;

  //*******************************
  //Attribute Declarations
  //*******************************
  
  	public FixedLengthStringData wsSignonMessages = new FixedLengthStringData(1133);
  	public FixedLengthStringData wsValidSignonMsgTable = new FixedLengthStringData(8).isAPartOf(wsSignonMessages, 0);
  	public FixedLengthStringData filler = new FixedLengthStringData(2).isAPartOf(wsValidSignonMsgTable, 0, FILLER).init("01");
  	public FixedLengthStringData filler1 = new FixedLengthStringData(2).isAPartOf(wsValidSignonMsgTable, 2, FILLER).init("02");
  	public FixedLengthStringData filler2 = new FixedLengthStringData(2).isAPartOf(wsValidSignonMsgTable, 4, FILLER).init("03");
  	public FixedLengthStringData filler3 = new FixedLengthStringData(2).isAPartOf(wsValidSignonMsgTable, 6, FILLER).init("04");
  	public FixedLengthStringData filler4 = new FixedLengthStringData(8).isAPartOf(wsValidSignonMsgTable, 0, FILLER_REDEFINE);
  	public FixedLengthStringData[] wsValidSignonMsgs = FLSArrayPartOfStructure(4, 2, filler4, 0);
  	public FixedLengthStringData[] wsValidMsg = FLSDArrayPartOfArrayStructure(2, wsValidSignonMsgs, 0);
  	public FixedLengthStringData wsSignonMsg = new FixedLengthStringData(377).isAPartOf(wsSignonMessages, 8);
  	public FixedLengthStringData wsSignonMsgPart1 = new FixedLengthStringData(73).isAPartOf(wsSignonMsg, 0);
  	public FixedLengthStringData filler5 = new FixedLengthStringData(18).isAPartOf(wsSignonMsgPart1, 0, FILLER).init(SPACES);
  	public FixedLengthStringData wsSmDate = new FixedLengthStringData(8).isAPartOf(wsSignonMsgPart1, 18);
  	public FixedLengthStringData wsSmMm = new FixedLengthStringData(2).isAPartOf(wsSmDate, 0).init(SPACES);
  	public FixedLengthStringData filler6 = new FixedLengthStringData(1).isAPartOf(wsSmDate, 2, FILLER).init("/");
  	public FixedLengthStringData wsSmDd = new FixedLengthStringData(2).isAPartOf(wsSmDate, 3).init(SPACES);
  	public FixedLengthStringData filler7 = new FixedLengthStringData(1).isAPartOf(wsSmDate, 5, FILLER).init("/");
  	public FixedLengthStringData wsSmYy = new FixedLengthStringData(2).isAPartOf(wsSmDate, 6).init(SPACES);
  	public FixedLengthStringData filler8 = new FixedLengthStringData(7).isAPartOf(wsSignonMsgPart1, 26, FILLER).init("   IN: ");
  	public FixedLengthStringData wsSmTimeIn = new FixedLengthStringData(5).isAPartOf(wsSignonMsgPart1, 33);
  	public FixedLengthStringData wsSmIhh = new FixedLengthStringData(2).isAPartOf(wsSmTimeIn, 0).init(SPACES);
  	public FixedLengthStringData filler9 = new FixedLengthStringData(1).isAPartOf(wsSmTimeIn, 2, FILLER).init(":");
  	public FixedLengthStringData wsSmImn = new FixedLengthStringData(2).isAPartOf(wsSmTimeIn, 3).init(SPACES);
  	public FixedLengthStringData filler10 = new FixedLengthStringData(8).isAPartOf(wsSignonMsgPart1, 38, FILLER).init("   OUT: ");
  	public FixedLengthStringData wsSmTimeOut = new FixedLengthStringData(5).isAPartOf(wsSignonMsgPart1, 46);
  	public FixedLengthStringData wsSmOhh = new FixedLengthStringData(2).isAPartOf(wsSmTimeOut, 0).init(SPACES);
  	public FixedLengthStringData filler11 = new FixedLengthStringData(1).isAPartOf(wsSmTimeOut, 2, FILLER).init(":");
  	public FixedLengthStringData wsSmOmn = new FixedLengthStringData(2).isAPartOf(wsSmTimeOut, 3).init(SPACES);
  	public FixedLengthStringData wsSmTrlr = new FixedLengthStringData(22).isAPartOf(wsSignonMsgPart1, 51).init(SPACES);
  	public FixedLengthStringData wsSignonMsgPart2 = new FixedLengthStringData(76).isAPartOf(wsSignonMsg, 73);
  	public FixedLengthStringData wsSignonMsgPart3 = new FixedLengthStringData(76).isAPartOf(wsSignonMsg, 149);
  	public FixedLengthStringData wsSignonMsgPart4 = new FixedLengthStringData(76).isAPartOf(wsSignonMsg, 225);
  	public FixedLengthStringData wsSignonMsgPart5 = new FixedLengthStringData(76).isAPartOf(wsSignonMsg, 301);
  	public FixedLengthStringData wsSignonMsgLines = new FixedLengthStringData(748).isAPartOf(wsSignonMessages, 385);
  	public FixedLengthStringData wsSmColHdr = new FixedLengthStringData(76).isAPartOf(wsSignonMsgLines, 0);
  	public FixedLengthStringData filler12 = new FixedLengthStringData(34).isAPartOf(wsSmColHdr, 0, FILLER).init(SPACES);
  	public FixedLengthStringData filler13 = new FixedLengthStringData(42).isAPartOf(wsSmColHdr, 34, FILLER).init("WTD         MTD         YTD               ");
  	public FixedLengthStringData wsSm1L2 = new FixedLengthStringData(76).isAPartOf(wsSignonMsgLines, 76);
  	public FixedLengthStringData filler14 = new FixedLengthStringData(35).isAPartOf(wsSm1L2, 0, FILLER).init("           REMEMBER, OUR GOAL IS TO");
  	public FixedLengthStringData filler15 = new FixedLengthStringData(41).isAPartOf(wsSm1L2, 35, FILLER).init(" 'FIX IT RIGHT THE FIRST TIME'           ");
  	public FixedLengthStringData wsSm1L4 = new FixedLengthStringData(75).isAPartOf(wsSignonMsgLines, 152);
  	public FixedLengthStringData filler16 = new FixedLengthStringData(31).isAPartOf(wsSm1L4, 0, FILLER).init("            % COMPL 1ST ATT    ");
  	public ZonedDecimalData wsSm1L4Wtd = new ZonedDecimalData(4, 1).isAPartOf(wsSm1L4, 31).setPattern("ZZ9.9");
  	public FixedLengthStringData filler17 = new FixedLengthStringData(7).isAPartOf(wsSm1L4, 36, FILLER).init("%      ");
  	public ZonedDecimalData wsSm1L4Mtd = new ZonedDecimalData(4, 1).isAPartOf(wsSm1L4, 43).setPattern("ZZ9.9");
  	public FixedLengthStringData filler18 = new FixedLengthStringData(7).isAPartOf(wsSm1L4, 48, FILLER).init("%      ");
  	public ZonedDecimalData wsSm1L4Ytd = new ZonedDecimalData(4, 1).isAPartOf(wsSm1L4, 55).setPattern("ZZ9.9");
  	public FixedLengthStringData filler19 = new FixedLengthStringData(1).isAPartOf(wsSm1L4, 60, FILLER).init("%");
  	public FixedLengthStringData filler20 = new FixedLengthStringData(14).isAPartOf(wsSm1L4, 61, FILLER).init(SPACES);
  	public FixedLengthStringData wsSm1L5 = new FixedLengthStringData(74).isAPartOf(wsSignonMsgLines, 227);
  	public FixedLengthStringData filler21 = new FixedLengthStringData(30).isAPartOf(wsSm1L5, 0, FILLER).init("           % COMPL            ");
  	public ZonedDecimalData wsSm1L5Wtd = new ZonedDecimalData(4, 1).isAPartOf(wsSm1L5, 30).setPattern("ZZ9.9");
  	public FixedLengthStringData filler22 = new FixedLengthStringData(7).isAPartOf(wsSm1L5, 35, FILLER).init("%      ");
  	public ZonedDecimalData wsSm1L5Mtd = new ZonedDecimalData(4, 1).isAPartOf(wsSm1L5, 42).setPattern("ZZ9.9");
  	public FixedLengthStringData filler23 = new FixedLengthStringData(7).isAPartOf(wsSm1L5, 47, FILLER).init("%      ");
  	public ZonedDecimalData wsSm1L5Ytd = new ZonedDecimalData(4, 1).isAPartOf(wsSm1L5, 54).setPattern("ZZ9.9");
  	public FixedLengthStringData filler24 = new FixedLengthStringData(1).isAPartOf(wsSm1L5, 59, FILLER).init("%");
  	public FixedLengthStringData wsSm1L5Trlr = new FixedLengthStringData(14).isAPartOf(wsSm1L5, 60).init(SPACES);
  	public FixedLengthStringData wsSm2L3 = new FixedLengthStringData(75).isAPartOf(wsSignonMsgLines, 301);
  	public FixedLengthStringData filler25 = new FixedLengthStringData(30).isAPartOf(wsSm2L3, 0, FILLER).init("            PAID LABOR/CALL   ");
  	public ZonedDecimalData wsSm2L3Wtd = new ZonedDecimalData(5, 2).isAPartOf(wsSm2L3, 30).setPattern("$ZZ9.99");
  	public FixedLengthStringData filler26 = new FixedLengthStringData(5).isAPartOf(wsSm2L3, 37, FILLER).init(SPACES);
  	public ZonedDecimalData wsSm2L3Mtd = new ZonedDecimalData(5, 2).isAPartOf(wsSm2L3, 42).setPattern("$ZZ9.99");
  	public FixedLengthStringData filler27 = new FixedLengthStringData(5).isAPartOf(wsSm2L3, 49, FILLER).init(SPACES);
  	public ZonedDecimalData wsSm2L3Ytd = new ZonedDecimalData(5, 2).isAPartOf(wsSm2L3, 54).setPattern("$ZZ9.99");
  	public FixedLengthStringData filler28 = new FixedLengthStringData(14).isAPartOf(wsSm2L3, 61, FILLER).init(SPACES);
  	public FixedLengthStringData wsSm2L4 = new FixedLengthStringData(74).isAPartOf(wsSignonMsgLines, 376);
  	public FixedLengthStringData filler29 = new FixedLengthStringData(29).isAPartOf(wsSm2L4, 0, FILLER).init("           PAID LABOR/HOUR   ");
  	public ZonedDecimalData wsSm2L4Wtd = new ZonedDecimalData(5, 2).isAPartOf(wsSm2L4, 29).setPattern("$ZZ9.99");
  	public FixedLengthStringData filler30 = new FixedLengthStringData(5).isAPartOf(wsSm2L4, 36, FILLER).init(SPACES);
  	public ZonedDecimalData wsSm2L4Mtd = new ZonedDecimalData(5, 2).isAPartOf(wsSm2L4, 41).setPattern("$ZZ9.99");
  	public FixedLengthStringData filler31 = new FixedLengthStringData(5).isAPartOf(wsSm2L4, 48, FILLER).init(SPACES);
  	public ZonedDecimalData wsSm2L4Ytd = new ZonedDecimalData(5, 2).isAPartOf(wsSm2L4, 53).setPattern("$ZZ9.99");
  	public FixedLengthStringData filler32 = new FixedLengthStringData(14).isAPartOf(wsSm2L4, 60, FILLER).init(SPACES);
  	public FixedLengthStringData wsSm2L5 = new FixedLengthStringData(73).isAPartOf(wsSignonMsgLines, 450);
  	public FixedLengthStringData filler33 = new FixedLengthStringData(28).isAPartOf(wsSm2L5, 0, FILLER).init("          MA $ PER CALL     ");
  	public ZonedDecimalData wsSm2L5Wtd = new ZonedDecimalData(5, 2).isAPartOf(wsSm2L5, 28).setPattern("$ZZ9.99");
  	public FixedLengthStringData filler34 = new FixedLengthStringData(5).isAPartOf(wsSm2L5, 35, FILLER).init(SPACES);
  	public ZonedDecimalData wsSm2L5Mtd = new ZonedDecimalData(5, 2).isAPartOf(wsSm2L5, 40).setPattern("$ZZ9.99");
  	public FixedLengthStringData filler35 = new FixedLengthStringData(5).isAPartOf(wsSm2L5, 47, FILLER).init(SPACES);
  	public ZonedDecimalData wsSm2L5Ytd = new ZonedDecimalData(5, 2).isAPartOf(wsSm2L5, 52).setPattern("$ZZ9.99");
  	public FixedLengthStringData wsSm2L5Trlr = new FixedLengthStringData(14).isAPartOf(wsSm2L5, 59).init(SPACES);
  	public FixedLengthStringData wsSm3L2 = new FixedLengthStringData(76).isAPartOf(wsSignonMsgLines, 523);
  	public FixedLengthStringData filler36 = new FixedLengthStringData(36).isAPartOf(wsSm3L2, 0, FILLER).init("     OUR GOAL FOR PROVIDING SERVICE ");
  	public FixedLengthStringData filler37 = new FixedLengthStringData(40).isAPartOf(wsSm3L2, 36, FILLER).init("WHEN THE CUSTOMER WANTS IT IS 100%      ");
  	public FixedLengthStringData wsSm3L4 = new FixedLengthStringData(75).isAPartOf(wsSignonMsgLines, 599);
  	public FixedLengthStringData filler38 = new FixedLengthStringData(31).isAPartOf(wsSm3L4, 0, FILLER).init("            INDIVIDUAL         ");
  	public ZonedDecimalData wsSm3L4Wtd = new ZonedDecimalData(4, 1).isAPartOf(wsSm3L4, 31).setPattern("ZZ9.9");
  	public FixedLengthStringData filler39 = new FixedLengthStringData(7).isAPartOf(wsSm3L4, 36, FILLER).init("%      ");
  	public ZonedDecimalData wsSm3L4Mtd = new ZonedDecimalData(4, 1).isAPartOf(wsSm3L4, 43).setPattern("ZZ9.9");
  	public FixedLengthStringData filler40 = new FixedLengthStringData(7).isAPartOf(wsSm3L4, 48, FILLER).init("%      ");
  	public ZonedDecimalData wsSm3L4Ytd = new ZonedDecimalData(4, 1).isAPartOf(wsSm3L4, 55).setPattern("ZZ9.9");
  	public FixedLengthStringData filler41 = new FixedLengthStringData(1).isAPartOf(wsSm3L4, 60, FILLER).init("%");
  	public FixedLengthStringData filler42 = new FixedLengthStringData(14).isAPartOf(wsSm3L4, 61, FILLER).init(SPACES);
  	public FixedLengthStringData wsSm3L5 = new FixedLengthStringData(74).isAPartOf(wsSignonMsgLines, 674);
  	public FixedLengthStringData filler43 = new FixedLengthStringData(30).isAPartOf(wsSm3L5, 0, FILLER).init("           UNIT               ");
  	public ZonedDecimalData wsSm3L5Wtd = new ZonedDecimalData(4, 1).isAPartOf(wsSm3L5, 30).setPattern("ZZ9.9");
  	public FixedLengthStringData filler44 = new FixedLengthStringData(7).isAPartOf(wsSm3L5, 35, FILLER).init("%      ");
  	public ZonedDecimalData wsSm3L5Mtd = new ZonedDecimalData(4, 1).isAPartOf(wsSm3L5, 42).setPattern("ZZ9.9");
  	public FixedLengthStringData filler45 = new FixedLengthStringData(7).isAPartOf(wsSm3L5, 47, FILLER).init("%      ");
  	public ZonedDecimalData wsSm3L5Ytd = new ZonedDecimalData(4, 1).isAPartOf(wsSm3L5, 54).setPattern("ZZ9.9");
  	public FixedLengthStringData filler46 = new FixedLengthStringData(1).isAPartOf(wsSm3L5, 59, FILLER).init("%");
  	public FixedLengthStringData wsSm3L5Trlr = new FixedLengthStringData(14).isAPartOf(wsSm3L5, 60).init(SPACES);
  	public IntegerData smsgIndex = new IntegerData();


    /**
     * initialize all variables in the class.
     */
	public void initialize() {
		COBOLFunctions.initialize(wsSignonMessages);
	}	

	
    /**
     * Retrieves the entire copybook as if it was a single string.
     * @return single FixedLengthString
     */
	public FixedLengthStringData getBaseString() {
  		if (baseString == null) {
   			baseString = new FixedLengthStringData(wsSignonMessages.getLength());
    		wsSignonMessages.isAPartOf(baseString, true);
   			baseString.resetIsAPartOfOffset();
  		}
  		return baseString;
	}


}