/*
 * Generation Date: Fri, 11 Nov 2011 12:30:21
 * Generated by:    CSC
 * Generated from:  PS221SS
 * 
 * Copyright 2010 CSC, all rights reserved.
 *
 * This software is the proprietary information of CSC.
 * Use is subject to license terms.
*/
 
package com.sears.processing.code.model;

import com.quipoz.framework.datatype.*;
import com.quipoz.COBOLFramework.datatype.ExternalData;
import static com.quipoz.COBOLFramework.COBOLFunctions.*;
import com.quipoz.COBOLFramework.COBOLFunctions;

/**
 * TempAreaForServiceUnitAdditionalDetails.
 *	
 * @author  CSC
 * @version $Revision: #1 $
 */
public class TempAreaForServiceUnitAdditionalDetails extends ExternalData {

    /**
     * serialVersionUID required as class is serializable.
     */
    private static final long serialVersionUID = 1L;

  //*******************************
  //Attribute Declarations
  //*******************************
  
  	public FixedLengthStringData ssNps221Record = new FixedLengthStringData(965);
  	public FixedLengthStringData filler = new FixedLengthStringData(12).isAPartOf(ssNps221Record, 0, FILLER);
  	public FixedLengthStringData scaSsNps221PgmLevel = new FixedLengthStringData(3).isAPartOf(ssNps221Record, 12);
  	public BinaryData ssNps221PgmLevelLength = new BinaryData(4, 0).isAPartOf(scaSsNps221PgmLevel, 0);
  	public FixedLengthStringData ssNps221PgmLevelAttr = new FixedLengthStringData(1).isAPartOf(scaSsNps221PgmLevel, 2);
  	public FixedLengthStringData ssNps221PgmLevel = new FixedLengthStringData(2).isAPartOf(ssNps221Record, 15);
  	public FixedLengthStringData scaSsNps221TdScrnDate = new FixedLengthStringData(3).isAPartOf(ssNps221Record, 17);
  	public BinaryData ssNps221TdScrnDateLength = new BinaryData(4, 0).isAPartOf(scaSsNps221TdScrnDate, 0);
  	public FixedLengthStringData ssNps221TdScrnDateAttr = new FixedLengthStringData(1).isAPartOf(scaSsNps221TdScrnDate, 2);
  	public FixedLengthStringData ssNps221TdScrnDate = new FixedLengthStringData(8).isAPartOf(ssNps221Record, 20);
  	public FixedLengthStringData scaSsNps221SuNo = new FixedLengthStringData(3).isAPartOf(ssNps221Record, 28);
  	public BinaryData ssNps221SuNoLength = new BinaryData(4, 0).isAPartOf(scaSsNps221SuNo, 0);
  	public FixedLengthStringData ssNps221SuNoAttr = new FixedLengthStringData(1).isAPartOf(scaSsNps221SuNo, 2);
  	public FixedLengthStringData ssNps221SuNo = new FixedLengthStringData(7).isAPartOf(ssNps221Record, 31);
  	public FixedLengthStringData scaSsNps221SuName = new FixedLengthStringData(3).isAPartOf(ssNps221Record, 38);
  	public BinaryData ssNps221SuNameLength = new BinaryData(4, 0).isAPartOf(scaSsNps221SuName, 0);
  	public FixedLengthStringData ssNps221SuNameAttr = new FixedLengthStringData(1).isAPartOf(scaSsNps221SuName, 2);
  	public FixedLengthStringData ssNps221SuName = new FixedLengthStringData(27).isAPartOf(ssNps221Record, 41);
  	public FixedLengthStringData scaSsNps221DrivInst = new FixedLengthStringData(3).isAPartOf(ssNps221Record, 68);
  	public BinaryData ssNps221DrivInstLength = new BinaryData(4, 0).isAPartOf(scaSsNps221DrivInst, 0);
  	public FixedLengthStringData ssNps221DrivInstAttr = new FixedLengthStringData(1).isAPartOf(scaSsNps221DrivInst, 2);
  	public FixedLengthStringData ssNps221DrivInst = new FixedLengthStringData(64).isAPartOf(ssNps221Record, 71);
  	public FixedLengthStringData scaSsNps221CustSvcAc = new FixedLengthStringData(3).isAPartOf(ssNps221Record, 135);
  	public BinaryData ssNps221CustSvcAcLength = new BinaryData(4, 0).isAPartOf(scaSsNps221CustSvcAc, 0);
  	public FixedLengthStringData ssNps221CustSvcAcAttr = new FixedLengthStringData(1).isAPartOf(scaSsNps221CustSvcAc, 2);
  	public FixedLengthStringData ssNps221CustSvcAc = new FixedLengthStringData(3).isAPartOf(ssNps221Record, 138);
  	public FixedLengthStringData scaSsNps221CustSvcPhn3 = new FixedLengthStringData(3).isAPartOf(ssNps221Record, 141);
  	public BinaryData ssNps221CustSvcPhn3Length = new BinaryData(4, 0).isAPartOf(scaSsNps221CustSvcPhn3, 0);
  	public FixedLengthStringData ssNps221CustSvcPhn3Attr = new FixedLengthStringData(1).isAPartOf(scaSsNps221CustSvcPhn3, 2);
  	public FixedLengthStringData ssNps221CustSvcPhn3 = new FixedLengthStringData(3).isAPartOf(ssNps221Record, 144);
  	public FixedLengthStringData scaSsNps221CustSvcPhn4 = new FixedLengthStringData(3).isAPartOf(ssNps221Record, 147);
  	public BinaryData ssNps221CustSvcPhn4Length = new BinaryData(4, 0).isAPartOf(scaSsNps221CustSvcPhn4, 0);
  	public FixedLengthStringData ssNps221CustSvcPhn4Attr = new FixedLengthStringData(1).isAPartOf(scaSsNps221CustSvcPhn4, 2);
  	public FixedLengthStringData ssNps221CustSvcPhn4 = new FixedLengthStringData(4).isAPartOf(ssNps221Record, 150);
  	public FixedLengthStringData scaSsNps221Remarks1 = new FixedLengthStringData(3).isAPartOf(ssNps221Record, 154);
  	public BinaryData ssNps221Remarks1Length = new BinaryData(4, 0).isAPartOf(scaSsNps221Remarks1, 0);
  	public FixedLengthStringData ssNps221Remarks1Attr = new FixedLengthStringData(1).isAPartOf(scaSsNps221Remarks1, 2);
  	public FixedLengthStringData ssNps221Remarks1 = new FixedLengthStringData(60).isAPartOf(ssNps221Record, 157);
  	public FixedLengthStringData scaSsNps221Remarks2 = new FixedLengthStringData(3).isAPartOf(ssNps221Record, 217);
  	public BinaryData ssNps221Remarks2Length = new BinaryData(4, 0).isAPartOf(scaSsNps221Remarks2, 0);
  	public FixedLengthStringData ssNps221Remarks2Attr = new FixedLengthStringData(1).isAPartOf(scaSsNps221Remarks2, 2);
  	public FixedLengthStringData ssNps221Remarks2 = new FixedLengthStringData(60).isAPartOf(ssNps221Record, 220);
  	public FixedLengthStringData scaSsNps221EffDateMm = new FixedLengthStringData(3).isAPartOf(ssNps221Record, 280);
  	public BinaryData ssNps221EffDateMmLen = new BinaryData(4, 0).isAPartOf(scaSsNps221EffDateMm, 0);
  	public FixedLengthStringData ssNps221EffDateMmAttr = new FixedLengthStringData(1).isAPartOf(scaSsNps221EffDateMm, 2);
  	public FixedLengthStringData ssNps221EffDateMm = new FixedLengthStringData(2).isAPartOf(ssNps221Record, 283);
  	public FixedLengthStringData scaSsNps221EffDateDd = new FixedLengthStringData(3).isAPartOf(ssNps221Record, 285);
  	public BinaryData ssNps221EffDateDdLen = new BinaryData(4, 0).isAPartOf(scaSsNps221EffDateDd, 0);
  	public FixedLengthStringData ssNps221EffDateDdAttr = new FixedLengthStringData(1).isAPartOf(scaSsNps221EffDateDd, 2);
  	public FixedLengthStringData ssNps221EffDateDd = new FixedLengthStringData(2).isAPartOf(ssNps221Record, 288);
  	public FixedLengthStringData scaSsNps221EffDateYy = new FixedLengthStringData(3).isAPartOf(ssNps221Record, 290);
  	public BinaryData ssNps221EffDateYyLen = new BinaryData(4, 0).isAPartOf(scaSsNps221EffDateYy, 0);
  	public FixedLengthStringData ssNps221EffDateYyAttr = new FixedLengthStringData(1).isAPartOf(scaSsNps221EffDateYy, 2);
  	public FixedLengthStringData ssNps221EffDateYy = new FixedLengthStringData(4).isAPartOf(ssNps221Record, 293);
  	public FixedLengthStringData scaSsNps221ExpDateMm = new FixedLengthStringData(3).isAPartOf(ssNps221Record, 297);
  	public BinaryData ssNps221ExpDateMmLen = new BinaryData(4, 0).isAPartOf(scaSsNps221ExpDateMm, 0);
  	public FixedLengthStringData ssNps221ExpDateMmAttr = new FixedLengthStringData(1).isAPartOf(scaSsNps221ExpDateMm, 2);
  	public FixedLengthStringData ssNps221ExpDateMm = new FixedLengthStringData(2).isAPartOf(ssNps221Record, 300);
  	public FixedLengthStringData scaSsNps221ExpDateDd = new FixedLengthStringData(3).isAPartOf(ssNps221Record, 302);
  	public BinaryData ssNps221ExpDateDdLen = new BinaryData(4, 0).isAPartOf(scaSsNps221ExpDateDd, 0);
  	public FixedLengthStringData ssNps221ExpDateDdAttr = new FixedLengthStringData(1).isAPartOf(scaSsNps221ExpDateDd, 2);
  	public FixedLengthStringData ssNps221ExpDateDd = new FixedLengthStringData(2).isAPartOf(ssNps221Record, 305);
  	public FixedLengthStringData scaSsNps221ExpDateYy = new FixedLengthStringData(3).isAPartOf(ssNps221Record, 307);
  	public BinaryData ssNps221ExpDateYyLen = new BinaryData(4, 0).isAPartOf(scaSsNps221ExpDateYy, 0);
  	public FixedLengthStringData ssNps221ExpDateYyAttr = new FixedLengthStringData(1).isAPartOf(scaSsNps221ExpDateYy, 2);
  	public FixedLengthStringData ssNps221ExpDateYy = new FixedLengthStringData(4).isAPartOf(ssNps221Record, 310);
  	public FixedLengthStringData scaSsNps221MrktZone1 = new FixedLengthStringData(3).isAPartOf(ssNps221Record, 314);
  	public BinaryData ssNps221MrktZone1Length = new BinaryData(4, 0).isAPartOf(scaSsNps221MrktZone1, 0);
  	public FixedLengthStringData ssNps221MrktZone1Attr = new FixedLengthStringData(1).isAPartOf(scaSsNps221MrktZone1, 2);
  	public FixedLengthStringData ssNps221MrktZone1 = new FixedLengthStringData(5).isAPartOf(ssNps221Record, 317);
  	public FixedLengthStringData scaSsNps221MrktZone2 = new FixedLengthStringData(3).isAPartOf(ssNps221Record, 322);
  	public BinaryData ssNps221MrktZone2Length = new BinaryData(4, 0).isAPartOf(scaSsNps221MrktZone2, 0);
  	public FixedLengthStringData ssNps221MrktZone2Attr = new FixedLengthStringData(1).isAPartOf(scaSsNps221MrktZone2, 2);
  	public FixedLengthStringData ssNps221MrktZone2 = new FixedLengthStringData(5).isAPartOf(ssNps221Record, 325);
  	public FixedLengthStringData scaSsNps221MrktZone3 = new FixedLengthStringData(3).isAPartOf(ssNps221Record, 330);
  	public BinaryData ssNps221MrktZone3Length = new BinaryData(4, 0).isAPartOf(scaSsNps221MrktZone3, 0);
  	public FixedLengthStringData ssNps221MrktZone3Attr = new FixedLengthStringData(1).isAPartOf(scaSsNps221MrktZone3, 2);
  	public FixedLengthStringData ssNps221MrktZone3 = new FixedLengthStringData(5).isAPartOf(ssNps221Record, 333);
  	public FixedLengthStringData scaSsNps221MrktZone4 = new FixedLengthStringData(3).isAPartOf(ssNps221Record, 338);
  	public BinaryData ssNps221MrktZone4Length = new BinaryData(4, 0).isAPartOf(scaSsNps221MrktZone4, 0);
  	public FixedLengthStringData ssNps221MrktZone4Attr = new FixedLengthStringData(1).isAPartOf(scaSsNps221MrktZone4, 2);
  	public FixedLengthStringData ssNps221MrktZone4 = new FixedLengthStringData(5).isAPartOf(ssNps221Record, 341);
  	public FixedLengthStringData scaSsNps221MrktZone5 = new FixedLengthStringData(3).isAPartOf(ssNps221Record, 346);
  	public BinaryData ssNps221MrktZone5Length = new BinaryData(4, 0).isAPartOf(scaSsNps221MrktZone5, 0);
  	public FixedLengthStringData ssNps221MrktZone5Attr = new FixedLengthStringData(1).isAPartOf(scaSsNps221MrktZone5, 2);
  	public FixedLengthStringData ssNps221MrktZone5 = new FixedLengthStringData(5).isAPartOf(ssNps221Record, 349);
  	public FixedLengthStringData scaSsNps221ScheduleNo = new FixedLengthStringData(3).isAPartOf(ssNps221Record, 354);
  	public BinaryData ssNps221ScheduleNoLength = new BinaryData(4, 0).isAPartOf(scaSsNps221ScheduleNo, 0);
  	public FixedLengthStringData ssNps221ScheduleNoAttr = new FixedLengthStringData(1).isAPartOf(scaSsNps221ScheduleNo, 2);
  	public FixedLengthStringData ssNps221ScheduleNo = new FixedLengthStringData(2).isAPartOf(ssNps221Record, 357);
  	public FixedLengthStringData scaSsNps221PrnInd = new FixedLengthStringData(3).isAPartOf(ssNps221Record, 359);
  	public BinaryData ssNps221PrnIndLength = new BinaryData(4, 0).isAPartOf(scaSsNps221PrnInd, 0);
  	public FixedLengthStringData ssNps221PrnIndAttr = new FixedLengthStringData(1).isAPartOf(scaSsNps221PrnInd, 2);
  	public FixedLengthStringData ssNps221PrnInd = new FixedLengthStringData(1).isAPartOf(ssNps221Record, 362);
  	public FixedLengthStringData ssNps221Table1 = new FixedLengthStringData(434).isAPartOf(ssNps221Record, 363);
  	public FixedLengthStringData[] ssNps221Table1Entry = FLSArrayPartOfStructure(7, 62, ssNps221Table1, 0);
  	public FixedLengthStringData[] scaSsNps221Days = FLSDArrayPartOfArrayStructure(3, ssNps221Table1Entry, 0);
  	public BinaryData[] ssNps221DaysLength = BDArrayPartOfArrayStructure(4, 0, scaSsNps221Days, 0);
  	public FixedLengthStringData[] ssNps221DaysAttr = FLSDArrayPartOfArrayStructure(1, scaSsNps221Days, 2);
  	public FixedLengthStringData[] ssNps221Days = FLSDArrayPartOfArrayStructure(3, ssNps221Table1Entry, 3);
  	public FixedLengthStringData[] scaSsNps221SiteFrHh = FLSDArrayPartOfArrayStructure(3, ssNps221Table1Entry, 6);
  	public BinaryData[] ssNps221SiteFrHhLength = BDArrayPartOfArrayStructure(4, 0, scaSsNps221SiteFrHh, 0);
  	public FixedLengthStringData[] ssNps221SiteFrHhAttr = FLSDArrayPartOfArrayStructure(1, scaSsNps221SiteFrHh, 2);
  	public FixedLengthStringData[] ssNps221SiteFrHh = FLSDArrayPartOfArrayStructure(2, ssNps221Table1Entry, 9);
  	public FixedLengthStringData[] scaSsNps221SiteFrMm = FLSDArrayPartOfArrayStructure(3, ssNps221Table1Entry, 11);
  	public BinaryData[] ssNps221SiteFrMmLength = BDArrayPartOfArrayStructure(4, 0, scaSsNps221SiteFrMm, 0);
  	public FixedLengthStringData[] ssNps221SiteFrMmAttr = FLSDArrayPartOfArrayStructure(1, scaSsNps221SiteFrMm, 2);
  	public FixedLengthStringData[] ssNps221SiteFrMm = FLSDArrayPartOfArrayStructure(2, ssNps221Table1Entry, 14);
  	public FixedLengthStringData[] scaSsNps221SiteFrAp = FLSDArrayPartOfArrayStructure(3, ssNps221Table1Entry, 16);
  	public BinaryData[] ssNps221SiteFrApLength = BDArrayPartOfArrayStructure(4, 0, scaSsNps221SiteFrAp, 0);
  	public FixedLengthStringData[] ssNps221SiteFrApAttr = FLSDArrayPartOfArrayStructure(1, scaSsNps221SiteFrAp, 2);
  	public FixedLengthStringData[] ssNps221SiteFrAp = FLSDArrayPartOfArrayStructure(1, ssNps221Table1Entry, 19);
  	public FixedLengthStringData[] scaSsNps221SiteToHh = FLSDArrayPartOfArrayStructure(3, ssNps221Table1Entry, 20);
  	public BinaryData[] ssNps221SiteToHhLength = BDArrayPartOfArrayStructure(4, 0, scaSsNps221SiteToHh, 0);
  	public FixedLengthStringData[] ssNps221SiteToHhAttr = FLSDArrayPartOfArrayStructure(1, scaSsNps221SiteToHh, 2);
  	public FixedLengthStringData[] ssNps221SiteToHh = FLSDArrayPartOfArrayStructure(2, ssNps221Table1Entry, 23);
  	public FixedLengthStringData[] scaSsNps221SiteToMm = FLSDArrayPartOfArrayStructure(3, ssNps221Table1Entry, 25);
  	public BinaryData[] ssNps221SiteToMmLength = BDArrayPartOfArrayStructure(4, 0, scaSsNps221SiteToMm, 0);
  	public FixedLengthStringData[] ssNps221SiteToMmAttr = FLSDArrayPartOfArrayStructure(1, scaSsNps221SiteToMm, 2);
  	public FixedLengthStringData[] ssNps221SiteToMm = FLSDArrayPartOfArrayStructure(2, ssNps221Table1Entry, 28);
  	public FixedLengthStringData[] scaSsNps221SiteToAp = FLSDArrayPartOfArrayStructure(3, ssNps221Table1Entry, 30);
  	public BinaryData[] ssNps221SiteToApLength = BDArrayPartOfArrayStructure(4, 0, scaSsNps221SiteToAp, 0);
  	public FixedLengthStringData[] ssNps221SiteToApAttr = FLSDArrayPartOfArrayStructure(1, scaSsNps221SiteToAp, 2);
  	public FixedLengthStringData[] ssNps221SiteToAp = FLSDArrayPartOfArrayStructure(1, ssNps221Table1Entry, 33);
  	public FixedLengthStringData[] scaSsNps221ShopFrHh = FLSDArrayPartOfArrayStructure(3, ssNps221Table1Entry, 34);
  	public BinaryData[] ssNps221ShopFrHhLength = BDArrayPartOfArrayStructure(4, 0, scaSsNps221ShopFrHh, 0);
  	public FixedLengthStringData[] ssNps221ShopFrHhAttr = FLSDArrayPartOfArrayStructure(1, scaSsNps221ShopFrHh, 2);
  	public FixedLengthStringData[] ssNps221ShopFrHh = FLSDArrayPartOfArrayStructure(2, ssNps221Table1Entry, 37);
  	public FixedLengthStringData[] scaSsNps221ShopFrMm = FLSDArrayPartOfArrayStructure(3, ssNps221Table1Entry, 39);
  	public BinaryData[] ssNps221ShopFrMmLength = BDArrayPartOfArrayStructure(4, 0, scaSsNps221ShopFrMm, 0);
  	public FixedLengthStringData[] ssNps221ShopFrMmAttr = FLSDArrayPartOfArrayStructure(1, scaSsNps221ShopFrMm, 2);
  	public FixedLengthStringData[] ssNps221ShopFrMm = FLSDArrayPartOfArrayStructure(2, ssNps221Table1Entry, 42);
  	public FixedLengthStringData[] scaSsNps221ShopFrAp = FLSDArrayPartOfArrayStructure(3, ssNps221Table1Entry, 44);
  	public BinaryData[] ssNps221ShopFrApLength = BDArrayPartOfArrayStructure(4, 0, scaSsNps221ShopFrAp, 0);
  	public FixedLengthStringData[] ssNps221ShopFrApAttr = FLSDArrayPartOfArrayStructure(1, scaSsNps221ShopFrAp, 2);
  	public FixedLengthStringData[] ssNps221ShopFrAp = FLSDArrayPartOfArrayStructure(1, ssNps221Table1Entry, 47);
  	public FixedLengthStringData[] scaSsNps221ShopToHh = FLSDArrayPartOfArrayStructure(3, ssNps221Table1Entry, 48);
  	public BinaryData[] ssNps221ShopToHhLength = BDArrayPartOfArrayStructure(4, 0, scaSsNps221ShopToHh, 0);
  	public FixedLengthStringData[] ssNps221ShopToHhAttr = FLSDArrayPartOfArrayStructure(1, scaSsNps221ShopToHh, 2);
  	public FixedLengthStringData[] ssNps221ShopToHh = FLSDArrayPartOfArrayStructure(2, ssNps221Table1Entry, 51);
  	public FixedLengthStringData[] scaSsNps221ShopToMm = FLSDArrayPartOfArrayStructure(3, ssNps221Table1Entry, 53);
  	public BinaryData[] ssNps221ShopToMmLength = BDArrayPartOfArrayStructure(4, 0, scaSsNps221ShopToMm, 0);
  	public FixedLengthStringData[] ssNps221ShopToMmAttr = FLSDArrayPartOfArrayStructure(1, scaSsNps221ShopToMm, 2);
  	public FixedLengthStringData[] ssNps221ShopToMm = FLSDArrayPartOfArrayStructure(2, ssNps221Table1Entry, 56);
  	public FixedLengthStringData[] scaSsNps221ShopToAp = FLSDArrayPartOfArrayStructure(3, ssNps221Table1Entry, 58);
  	public BinaryData[] ssNps221ShopToApLength = BDArrayPartOfArrayStructure(4, 0, scaSsNps221ShopToAp, 0);
  	public FixedLengthStringData[] ssNps221ShopToApAttr = FLSDArrayPartOfArrayStructure(1, scaSsNps221ShopToAp, 2);
  	public FixedLengthStringData[] ssNps221ShopToAp = FLSDArrayPartOfArrayStructure(1, ssNps221Table1Entry, 61);
  	public FixedLengthStringData scaSsNps221Msg = new FixedLengthStringData(3).isAPartOf(ssNps221Record, 797);
  	public BinaryData ssNps221MsgLength = new BinaryData(4, 0).isAPartOf(scaSsNps221Msg, 0);
  	public FixedLengthStringData ssNps221MsgAttr = new FixedLengthStringData(1).isAPartOf(scaSsNps221Msg, 2);
  	public FixedLengthStringData ssNps221Msg = new FixedLengthStringData(79).isAPartOf(ssNps221Record, 800);
  	public FixedLengthStringData scaSsNps221Msg2 = new FixedLengthStringData(3).isAPartOf(ssNps221Record, 879);
  	public BinaryData ssNps221Msg2Length = new BinaryData(4, 0).isAPartOf(scaSsNps221Msg2, 0);
  	public FixedLengthStringData ssNps221Msg2Attr = new FixedLengthStringData(1).isAPartOf(scaSsNps221Msg2, 2);
  	public FixedLengthStringData ssNps221Msg2 = new FixedLengthStringData(79).isAPartOf(ssNps221Record, 882);
  	public FixedLengthStringData scaSsNps221Command = new FixedLengthStringData(3).isAPartOf(ssNps221Record, 961);
  	public BinaryData ssNps221CommandLength = new BinaryData(4, 0).isAPartOf(scaSsNps221Command, 0);
  	public FixedLengthStringData ssNps221CommandAttr = new FixedLengthStringData(1).isAPartOf(scaSsNps221Command, 2);
  	public FixedLengthStringData ssNps221Command = new FixedLengthStringData(1).isAPartOf(ssNps221Record, 964);


    /**
     * initialize all variables in the class.
     */
	public void initialize() {
		COBOLFunctions.initialize(ssNps221Record);
	}	

	
    /**
     * Retrieves the entire copybook as if it was a single string.
     * @return single FixedLengthString
     */
	public FixedLengthStringData getBaseString() {
  		if (baseString == null) {
   			baseString = new FixedLengthStringData(ssNps221Record.getLength());
    		ssNps221Record.isAPartOf(baseString, true);
   			baseString.resetIsAPartOfOffset();
  		}
  		return baseString;
	}


}