/*
 * Generation Date: Fri, 11 Nov 2011 12:30:22
 * Generated by:    CSC
 * Generated from:  TRCCOBOL
 * 
 * Copyright 2010 CSC, all rights reserved.
 *
 * This software is the proprietary information of CSC.
 * Use is subject to license terms.
*/
 
package com.sears.processing.code.model;

import com.quipoz.framework.datatype.*;
import com.quipoz.COBOLFramework.datatype.ExternalData;
import static com.quipoz.COBOLFramework.COBOLFunctions.*;
import com.quipoz.COBOLFramework.COBOLFunctions;
import com.quipoz.COBOLFramework.datatype.Validator;
import com.quipoz.COBOLFramework.datatype.ValueRange;

/**
 * TranscenturyCalendarUtility.
 *	
 * @author  CSC
 * @version $Revision: #1 $
 */
public class TranscenturyCalendarUtility extends ExternalData {

    /**
     * serialVersionUID required as class is serializable.
     */
    private static final long serialVersionUID = 1L;

  //*******************************
  //Attribute Declarations
  //*******************************
  
  	public FixedLengthStringData trcConvrConversational = new FixedLengthStringData(1000);
  	public FixedLengthStringData trcConvrBusinessParameters = new FixedLengthStringData(89).isAPartOf(trcConvrConversational, 0);
  	public FixedLengthStringData trcConvrHolidayTbl = new FixedLengthStringData(2).isAPartOf(trcConvrBusinessParameters, 0).init("01");
  	public FixedLengthStringData trcConvrFiscyrStart = new FixedLengthStringData(2).isAPartOf(trcConvrBusinessParameters, 2).init("01");
  	public FixedLengthStringData trcConvrFiscmoStart = new FixedLengthStringData(2).isAPartOf(trcConvrBusinessParameters, 4).init("01");
  	public FixedLengthStringData trcConvrEndPntsDef = new FixedLengthStringData(1).isAPartOf(trcConvrBusinessParameters, 6).init("T");
  	public FixedLengthStringData trcConvrDowString = new FixedLengthStringData(7).isAPartOf(trcConvrBusinessParameters, 7).init("0123456");
  	public FixedLengthStringData trcConvrProcDayDef = new FixedLengthStringData(7).isAPartOf(trcConvrBusinessParameters, 14).init("NEEEEEN");
  	public FixedLengthStringData trcConvrCenturyBreak = new FixedLengthStringData(8).isAPartOf(trcConvrBusinessParameters, 21).init("19/20;40");
  	public FixedLengthStringData trcConvrFromDateMask = new FixedLengthStringData(8).isAPartOf(trcConvrBusinessParameters, 29).init("CCYYMMDD");
  	public FixedLengthStringData trcConvrToDateMask = new FixedLengthStringData(8).isAPartOf(trcConvrBusinessParameters, 37).init("CCYYMMDD");
  	public FixedLengthStringData trcConvrOut1DateMask = new FixedLengthStringData(8).isAPartOf(trcConvrBusinessParameters, 45).init("YYMMDD--");
  	public FixedLengthStringData trcConvrOut2DateMask = new FixedLengthStringData(8).isAPartOf(trcConvrBusinessParameters, 53).init("--YYMMDD");
  	public FixedLengthStringData trcConvrOut3DateMask = new FixedLengthStringData(8).isAPartOf(trcConvrBusinessParameters, 61).init("-CCYYDDD");
  	public FixedLengthStringData filler = new FixedLengthStringData(20).isAPartOf(trcConvrBusinessParameters, 69, FILLER).init(SPACES);
  	public FixedLengthStringData trcConvrInputParameters = new FixedLengthStringData(56).isAPartOf(trcConvrConversational, 89);
  	public FixedLengthStringData trcConvrFunctionCode = new FixedLengthStringData(4).isAPartOf(trcConvrInputParameters, 0);
  	public FixedLengthStringData trcConvrFunctionType = new FixedLengthStringData(1).isAPartOf(trcConvrFunctionCode, 0);
  	public FixedLengthStringData trcConvrFunctionNumber = new FixedLengthStringData(3).isAPartOf(trcConvrFunctionCode, 1);
  	public FixedLengthStringData trcConvrFromDateX = new FixedLengthStringData(8).isAPartOf(trcConvrInputParameters, 4);
  	public ZonedDecimalData trcConvrFromDate9 = new ZonedDecimalData(8, 0).isAPartOf(trcConvrFromDateX, 0, REDEFINE).setUnsigned();
  	public FixedLengthStringData trcConvrToDateX = new FixedLengthStringData(8).isAPartOf(trcConvrInputParameters, 12);
  	public ZonedDecimalData trcConvrToDate9 = new ZonedDecimalData(8, 0).isAPartOf(trcConvrToDateX, 0, REDEFINE).setUnsigned();
  	public ZonedDecimalData trcConvrInNumericParm = new ZonedDecimalData(9, 0).isAPartOf(trcConvrInputParameters, 20);
  	public FixedLengthStringData trcConvrInAlphaParm = new FixedLengthStringData(7).isAPartOf(trcConvrInputParameters, 29);
  	public FixedLengthStringData filler1 = new FixedLengthStringData(20).isAPartOf(trcConvrInputParameters, 36, FILLER).init(SPACES);
  	public FixedLengthStringData trcConvrOutputParameters = new FixedLengthStringData(144).isAPartOf(trcConvrConversational, 145);
  	public FixedLengthStringData trcConvrReturnCode = new FixedLengthStringData(83).isAPartOf(trcConvrOutputParameters, 0);
  	public ZonedDecimalData trcConvrReturnNum = new ZonedDecimalData(3, 0).isAPartOf(trcConvrReturnCode, 0).setUnsigned();
  	public Validator trcConvrReturnGood = new Validator(trcConvrReturnNum, 0);
  	public Validator trcConvrReturnBad = new Validator(trcConvrReturnNum, new ValueRange(001,999));
  	public FixedLengthStringData trcConvrReturnText = new FixedLengthStringData(80).isAPartOf(trcConvrReturnCode, 3);
  	public FixedLengthStringData trcConvrStdoutDateX = new FixedLengthStringData(8).isAPartOf(trcConvrOutputParameters, 83);
  	public ZonedDecimalData trcConvrStdoutDate9 = new ZonedDecimalData(8, 0).isAPartOf(trcConvrStdoutDateX, 0, REDEFINE).setUnsigned();
  	public FixedLengthStringData trcConvrOut1DateX = new FixedLengthStringData(8).isAPartOf(trcConvrOutputParameters, 91);
  	public ZonedDecimalData trcConvrOut1Date9 = new ZonedDecimalData(8, 0).isAPartOf(trcConvrOut1DateX, 0, REDEFINE).setUnsigned();
  	public FixedLengthStringData trcConvrOut2DateX = new FixedLengthStringData(8).isAPartOf(trcConvrOutputParameters, 99);
  	public ZonedDecimalData trcConvrOut2Date9 = new ZonedDecimalData(8, 0).isAPartOf(trcConvrOut2DateX, 0, REDEFINE).setUnsigned();
  	public FixedLengthStringData trcConvrOut3DateX = new FixedLengthStringData(8).isAPartOf(trcConvrOutputParameters, 107);
  	public ZonedDecimalData trcConvrOut3Date9 = new ZonedDecimalData(8, 0).isAPartOf(trcConvrOut3DateX, 0, REDEFINE).setUnsigned();
  	public ZonedDecimalData trcConvrOutNumericParm = new ZonedDecimalData(9, 0).isAPartOf(trcConvrOutputParameters, 115);
  	public FixedLengthStringData filler2 = new FixedLengthStringData(20).isAPartOf(trcConvrOutputParameters, 124, FILLER).init(SPACES);
  	public FixedLengthStringData trcConvrExtendedIoAreas = new FixedLengthStringData(250).isAPartOf(trcConvrConversational, 289);
  	public FixedLengthStringData trcConvrEditedIo = new FixedLengthStringData(250).isAPartOf(trcConvrExtendedIoAreas, 0);
  	public FixedLengthStringData trcConvrFromDateE = new FixedLengthStringData(50).isAPartOf(trcConvrEditedIo, 0);
  	public FixedLengthStringData trcConvrToDateE = new FixedLengthStringData(50).isAPartOf(trcConvrEditedIo, 50);
  	public FixedLengthStringData trcConvrOut1DateE = new FixedLengthStringData(50).isAPartOf(trcConvrEditedIo, 100);
  	public FixedLengthStringData trcConvrOut2DateE = new FixedLengthStringData(50).isAPartOf(trcConvrEditedIo, 150);
  	public FixedLengthStringData trcConvrOut3DateE = new FixedLengthStringData(50).isAPartOf(trcConvrEditedIo, 200);
  	public FixedLengthStringData trcConvrSerialIo = new FixedLengthStringData(250).isAPartOf(trcConvrEditedIo, 0, REDEFINE);
  	public ZonedDecimalData trcConvrFromDateS = new ZonedDecimalData(9, 0).isAPartOf(trcConvrSerialIo, 0);
  	public FixedLengthStringData filler3 = new FixedLengthStringData(41).isAPartOf(trcConvrSerialIo, 9, FILLER);
  	public ZonedDecimalData trcConvrToDateS = new ZonedDecimalData(9, 0).isAPartOf(trcConvrSerialIo, 50);
  	public FixedLengthStringData filler4 = new FixedLengthStringData(41).isAPartOf(trcConvrSerialIo, 59, FILLER);
  	public ZonedDecimalData trcConvrOut1DateS = new ZonedDecimalData(9, 0).isAPartOf(trcConvrSerialIo, 100);
  	public FixedLengthStringData filler5 = new FixedLengthStringData(41).isAPartOf(trcConvrSerialIo, 109, FILLER);
  	public ZonedDecimalData trcConvrOut2DateS = new ZonedDecimalData(9, 0).isAPartOf(trcConvrSerialIo, 150);
  	public FixedLengthStringData filler6 = new FixedLengthStringData(41).isAPartOf(trcConvrSerialIo, 159, FILLER);
  	public ZonedDecimalData trcConvrOut3DateS = new ZonedDecimalData(9, 0).isAPartOf(trcConvrSerialIo, 200);
  	public FixedLengthStringData filler7 = new FixedLengthStringData(41).isAPartOf(trcConvrSerialIo, 209, FILLER);
  	public FixedLengthStringData filler8 = new FixedLengthStringData(461).isAPartOf(trcConvrConversational, 539, FILLER).init(SPACES);


    /**
     * initialize all variables in the class.
     */
	public void initialize() {
		COBOLFunctions.initialize(trcConvrConversational);
	}	

	
    /**
     * Retrieves the entire copybook as if it was a single string.
     * @return single FixedLengthString
     */
	public FixedLengthStringData getBaseString() {
  		if (baseString == null) {
   			baseString = new FixedLengthStringData(trcConvrConversational.getLength());
    		trcConvrConversational.isAPartOf(baseString, true);
   			baseString.resetIsAPartOfOffset();
  		}
  		return baseString;
	}


}