/*
 * Generation Date: Fri, 11 Nov 2011 12:30:22
 * Generated by:    CSC
 * Generated from:  UPSMUIFL
 * 
 * Copyright 2010 CSC, all rights reserved.
 *
 * This software is the proprietary information of CSC.
 * Use is subject to license terms.
*/
 
package com.sears.processing.code.model;

import com.quipoz.framework.datatype.*;
import com.quipoz.COBOLFramework.datatype.ExternalData;
import static com.quipoz.COBOLFramework.COBOLFunctions.*;
import com.quipoz.COBOLFramework.COBOLFunctions;
import com.quipoz.COBOLFramework.datatype.Validator;
import com.quipoz.COBOLFramework.datatype.ValueRange;

/**
 * UnitAdditionalInformation.
 *	
 * @author  CSC
 * @version $Revision: #1 $
 */
public class UnitAdditionalInformation extends ExternalData {

    /**
     * serialVersionUID required as class is serializable.
     */
    private static final long serialVersionUID = 1L;

  //*******************************
  //Attribute Declarations
  //*******************************
  
  	public FixedLengthStringData upsmuiflRec = new FixedLengthStringData(100);
  	public FixedLengthStringData upsmuiflKey = new FixedLengthStringData(10).isAPartOf(upsmuiflRec, 0);
  	public FixedLengthStringData upsmuiflSvcUnNo = new FixedLengthStringData(7).isAPartOf(upsmuiflKey, 0);
  	public FixedLengthStringData upsmuiflRecType = new FixedLengthStringData(1).isAPartOf(upsmuiflKey, 7);
  	public Validator upsmuiflRemarkRec = new Validator(upsmuiflRecType, "R");
  	public Validator upsmuiflMkgZoneRec = new Validator(upsmuiflRecType, "M");
  	public Validator upsmuiflUnitTypeRec = new Validator(upsmuiflRecType, "U");
  	public ZonedDecimalData upsmuiflSeqNo = new ZonedDecimalData(2, 0).isAPartOf(upsmuiflKey, 8).setUnsigned();
  	public FixedLengthStringData upsmuiflFields = new FixedLengthStringData(90).isAPartOf(upsmuiflRec, 10);
  	public FixedLengthStringData upsmuiflRemarksLayout = new FixedLengthStringData(90).isAPartOf(upsmuiflFields, 0, REDEFINE);
  	public FixedLengthStringData upsmuiflRemarks = new FixedLengthStringData(60).isAPartOf(upsmuiflRemarksLayout, 0);
  	public FixedLengthStringData upsmuiflEffectDate = new FixedLengthStringData(10).isAPartOf(upsmuiflRemarksLayout, 60);
  	public FixedLengthStringData upsmuiflExpireDate = new FixedLengthStringData(10).isAPartOf(upsmuiflRemarksLayout, 70);
  	public FixedLengthStringData filler = new FixedLengthStringData(10).isAPartOf(upsmuiflRemarksLayout, 80, FILLER);
  	public FixedLengthStringData upsmuiflMkgLayout = new FixedLengthStringData(90).isAPartOf(upsmuiflFields, 0, REDEFINE);
  	public FixedLengthStringData upsmuiflMkgZone1 = new FixedLengthStringData(5).isAPartOf(upsmuiflMkgLayout, 0);
  	public FixedLengthStringData upsmuiflMkgZone2 = new FixedLengthStringData(5).isAPartOf(upsmuiflMkgLayout, 5);
  	public FixedLengthStringData upsmuiflMkgZone3 = new FixedLengthStringData(5).isAPartOf(upsmuiflMkgLayout, 10);
  	public FixedLengthStringData upsmuiflMkgZone4 = new FixedLengthStringData(5).isAPartOf(upsmuiflMkgLayout, 15);
  	public FixedLengthStringData upsmuiflMkgZone5 = new FixedLengthStringData(5).isAPartOf(upsmuiflMkgLayout, 20);
  	public FixedLengthStringData filler1 = new FixedLengthStringData(65).isAPartOf(upsmuiflMkgLayout, 25, FILLER);
  	public FixedLengthStringData upsmuiflUnitLayout = new FixedLengthStringData(90).isAPartOf(upsmuiflFields, 0, REDEFINE);
  	public FixedLengthStringData upsmuiflUnitType = new FixedLengthStringData(3).isAPartOf(upsmuiflUnitLayout, 0);
  	public FixedLengthStringData upsmuiflUnitDesc = new FixedLengthStringData(60).isAPartOf(upsmuiflUnitLayout, 3);
  	public FixedLengthStringData filler2 = new FixedLengthStringData(27).isAPartOf(upsmuiflUnitLayout, 63, FILLER);


    /**
     * initialize all variables in the class.
     */
	public void initialize() {
		COBOLFunctions.initialize(upsmuiflRec);
	}	

	
    /**
     * Retrieves the entire copybook as if it was a single string.
     * @return single FixedLengthString
     */
	public FixedLengthStringData getBaseString() {
  		if (baseString == null) {
   			baseString = new FixedLengthStringData(upsmuiflRec.getLength());
    		upsmuiflRec.isAPartOf(baseString, true);
   			baseString.resetIsAPartOfOffset();
  		}
  		return baseString;
	}


}