

<%@ page import="com.sears.processing.code.model.Nps220ScreenVars" %>


<%@ include file="/mainCommon1.jsp"%>


<%--                                                                --%>

<%-- Use is subject to license terms.                               --%>

<%-- This software is the proprietary information of CSC.           --%>

<%--                                                                --%>

<%-- Copyright 2011 CSC, all rights reserved.                       --%>

<%--                                                                --%>

<%-- Generation Date: Tue, 22 Nov 2011 16:10:01                     --%>

<%-- Generated from:  NPS220.BMS Record: NPS220                   --%>

<%-- Generated by:    CSC                                           --%>

<%--                                                                --%>

<%StringData ENTER_F1_HELP_F3_EXIT_F5_REFRESH_F9_COMMAND_F12_PREV_SCREEN = new StringData("ENTER_F1_HELP_F3_EXIT_F5_REFRESH_F9_COMMAND_F12_PREV_SCREEN");%>

<%StringData HHT_OPTIONS_2_ADDITIONAL_INFORMATION = new StringData("HHT_OPTIONS_2_ADDITIONAL_INFORMATION");%>

<%StringData COMMAND = new StringData("COMMAND");%>

<%StringData ACCESS_DOCK_UNIT = new StringData("ACCESS_DOCK_UNIT");%>

<%StringData ALL_DOT_LENGTH_1_3 = new StringData("ALL_DOT_LENGTH_1_3");%>

<%StringData ALL_DOT_LENGTH_1_2 = new StringData("ALL_DOT_LENGTH_1_2");%>

<%StringData ALL_DOT_LENGTH_1_1 = new StringData("ALL_DOT_LENGTH_1_1");%>

<%StringData ALL_SLASH_LENGTH_1 = new StringData("ALL_SLASH_LENGTH_1");%>

<%StringData PREMIUM = new StringData("PREMIUM");%>

<%StringData PARTS_SHIP_DEST_B_H_T = new StringData("PARTS_SHIP_DEST_B_H_T");%>

<%StringData PREMIUM_INHOME = new StringData("PREMIUM_INHOME");%>

<%StringData MISC_STATE_REG = new StringData("MISC_STATE_REG");%>

<%StringData PARTS_MARKUP_FOREIGN_STORE = new StringData("PARTS_MARKUP_FOREIGN_STORE");%>

<%StringData SAME_DAY_ROUTING = new StringData("SAME_DAY_ROUTING");%>

<%StringData ROUTING_DATE = new StringData("ROUTING_DATE");%>

<%StringData POS_START_DATE = new StringData("POS_START_DATE");%>

<%StringData NPN_DATE = new StringData("NPN_DATE");%>

<%StringData CLOSED_DATE = new StringData("CLOSED_DATE");%>

<%StringData HHT_DATE = new StringData("HHT_DATE");%>

<%StringData UNIT_DATES_OPEN_DATE = new StringData("UNIT_DATES_OPEN_DATE");%>

<%StringData REGION_ROUTING = new StringData("REGION_ROUTING");%>

<%StringData CREATE_DRC_ORDER_FLAG = new StringData("CREATE_DRC_ORDER_FLAG");%>

<%StringData RFS_ACCT = new StringData("RFS_ACCT");%>

<%StringData CARRY_INVENTORY_FLAG = new StringData("CARRY_INVENTORY_FLAG");%>

<%StringData POS_UNIT = new StringData("POS_UNIT");%>

<%StringData CONVERTED_TO_NPS_FLAG = new StringData("CONVERTED_TO_NPS_FLAG");%>

<%StringData DISTRICT = new StringData("DISTRICT");%>

<%StringData PROVIDE_MARKETING_FLAG = new StringData("PROVIDE_MARKETING_FLAG");%>

<%StringData REPORTING = new StringData("REPORTING");%>

<%StringData FLAGS_PROVIDE_SERVICE_FLAG = new StringData("FLAGS_PROVIDE_SERVICE_FLAG");%>

<%StringData RELATED_UNITS_REGION = new StringData("RELATED_UNITS_REGION");%>

<%StringData MESSAGING_PERMITTED_TO = new StringData("MESSAGING_PERMITTED_TO");%>

<%StringData MESSAGE_CODE = new StringData("MESSAGE_CODE");%>

<%StringData UNIT_TYPE = new StringData("UNIT_TYPE");%>

<%StringData ALL_DASH_LENGTH_1 = new StringData("ALL_DASH_LENGTH_1");%>

<%StringData ZIP = new StringData("ZIP");%>

<%StringData SHOP = new StringData("SHOP");%>

<%StringData STATE = new StringData("STATE");%>

<%StringData CITY = new StringData("CITY");%>

<%StringData ADDRESS = new StringData("ADDRESS");%>

<%StringData UNIT_NAME = new StringData("UNIT_NAME");%>

<%StringData UNIT = new StringData("UNIT");%>

<%StringData NPS_UNIT_INFORMATION = new StringData("NPS_UNIT_INFORMATION");%>

<%StringData NPS22017 = new StringData("NPS22017");%>

<% Nps220ScreenVars sv = (Nps220ScreenVars) screenModel.getVariables();%>


<div class='outerDiv'>
<br/><br/>
<table>

<tr style='height:22px;'><td></td><td>


<%if ((new Byte((sv.nps2151).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>
	
  		
		<%					
		if(!((sv.nps2151.getFormData()).toString()).trim().equalsIgnoreCase("")) { 	
					
							if(longValue == null || longValue.equalsIgnoreCase("")) {
								formatValue = formatValue( (sv.nps2151.getFormData()).toString()); 
							} else {
								formatValue = formatValue( longValue);
							}
							
							
					} else  {
								
					if(longValue == null || longValue.equalsIgnoreCase("")) {
								formatValue = formatValue( (sv.nps2151.getFormData()).toString()); 
							} else {
								formatValue = formatValue( longValue);
							}
					
					}
					%>			
				<div class='<%= ((formatValue == null)||("".equals(formatValue.trim()))) ? 
						"blank_cell" : "output_cell" %>'>
				<%=formatValue%>
			</div>	
		<%
		longValue = null;
		formatValue = null;
		%>
  <%}%>
	






<%if ((new Byte((sv.nps2152).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>
	
  		
		<%					
		if(!((sv.nps2152.getFormData()).toString()).trim().equalsIgnoreCase("")) { 	
					
							if(longValue == null || longValue.equalsIgnoreCase("")) {
								formatValue = formatValue( (sv.nps2152.getFormData()).toString()); 
							} else {
								formatValue = formatValue( longValue);
							}
							
							
					} else  {
								
					if(longValue == null || longValue.equalsIgnoreCase("")) {
								formatValue = formatValue( (sv.nps2152.getFormData()).toString()); 
							} else {
								formatValue = formatValue( longValue);
							}
					
					}
					%>			
				<div class='<%= ((formatValue == null)||("".equals(formatValue.trim()))) ? 
						"blank_cell" : "output_cell" %>'>
				<%=formatValue%>
			</div>	
		<%
		longValue = null;
		formatValue = null;
		%>
  <%}%>
	

</td></tr></table><br/><br/>
<fieldset class="fieldsetUIG">
<legend class="legendUIG">
<%=resourceBundleHandler.gettingValueFromBundle("Unit Information")%>
</legend>
<table width='100%' align ='center' class ='tableFormat' cellspacing="5px">


<tr style='height:22px;'><td>

<%if ((new Byte((UNIT).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("UNIT")%>
</div>
<%}%>
</td>

<td>


<%if ((new Byte((sv.nps2103).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>
	
  		
		<%					
		if(!((sv.nps2103.getFormData()).toString()).trim().equalsIgnoreCase("")) { 	
					
							if(longValue == null || longValue.equalsIgnoreCase("")) {
								formatValue = formatValue( (sv.nps2103.getFormData()).toString()); 
							} else {
								formatValue = formatValue( longValue);
							}
							
							
					} else  {
								
					if(longValue == null || longValue.equalsIgnoreCase("")) {
								formatValue = formatValue( (sv.nps2103.getFormData()).toString()); 
							} else {
								formatValue = formatValue( longValue);
							}
					
					}
					%>			
				<div class='<%= ((formatValue == null)||("".equals(formatValue.trim()))) ? 
						"blank_cell" : "output_cell" %>'>
				<%=formatValue%>
			</div>	
		<%
		longValue = null;
		formatValue = null;
		%>
  <%}%>
	

</td>

<td>

<%if ((new Byte((UNIT_NAME).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("UNIT_NAME")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2104).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2104' 
type='text'

<%if((sv.nps2104).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2104.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2104.getLength()%>'
maxLength='<%=sv.nps2104.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2104).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2104).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2104).getColor()== null  ? 
			"input_cell" :  (sv.nps2104).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td></tr>

<tr style='height:22px;'><td>

<%if ((new Byte((ADDRESS).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("ADDRESS")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2105).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2105' 
type='text'

<%if((sv.nps2105).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2105.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2105.getLength()%>'
maxLength='<%=sv.nps2105.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2105).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2105).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2105).getColor()== null  ? 
			"input_cell" :  (sv.nps2105).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>





<%if ((new Byte((sv.nps2106).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2106' 
type='text'

<%if((sv.nps2106).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2106.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2106.getLength()%>'
maxLength='<%=sv.nps2106.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2106).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2106).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2106).getColor()== null  ? 
			"input_cell" :  (sv.nps2106).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td>

<td>

<%if ((new Byte((CITY).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("CITY")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2107).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2107' 
type='text'

<%if((sv.nps2107).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2107.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2107.getLength()%>'
maxLength='<%=sv.nps2107.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2107).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2107).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2107).getColor()== null  ? 
			"input_cell" :  (sv.nps2107).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td></tr>

<tr style='height:22px;'><td>

<%if ((new Byte((STATE).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("STATE")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2108).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2108' 
type='text'

<%if((sv.nps2108).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2108.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2108.getLength()%>'
maxLength='<%=sv.nps2108.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2108).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2108).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2108).getColor()== null  ? 
			"input_cell" :  (sv.nps2108).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td>

<td>

<%if ((new Byte((ZIP).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("ZIP")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2109).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2109' 
type='text'

<%if((sv.nps2109).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2109.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2109.getLength()%>'
maxLength='<%=sv.nps2109.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2109).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2109).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2109).getColor()== null  ? 
			"input_cell" :  (sv.nps2109).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
<%if ((new Byte((ALL_DASH_LENGTH_1).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("ALL_DASH_LENGTH_1")%>
</div>
<%}%>
<%if ((new Byte((sv.nps2110).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2110' 
type='text'

<%if((sv.nps2110).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2110.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2110.getLength()%>'
maxLength='<%=sv.nps2110.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2110).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2110).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2110).getColor()== null  ? 
			"input_cell" :  (sv.nps2110).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td></tr>

<tr style='height:22px;'><td>

<%if ((new Byte((UNIT_TYPE).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("UNIT_TYPE")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2111).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2111' 
type='text'

<%if((sv.nps2111).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2111.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2111.getLength()%>'
maxLength='<%=sv.nps2111.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2111).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2111).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2111).getColor()== null  ? 
			"input_cell" :  (sv.nps2111).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>





<%if ((new Byte((sv.nps2112).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>
	
  		
		<%					
		if(!((sv.nps2112.getFormData()).toString()).trim().equalsIgnoreCase("")) { 	
					
							if(longValue == null || longValue.equalsIgnoreCase("")) {
								formatValue = formatValue( (sv.nps2112.getFormData()).toString()); 
							} else {
								formatValue = formatValue( longValue);
							}
							
							
					} else  {
								
					if(longValue == null || longValue.equalsIgnoreCase("")) {
								formatValue = formatValue( (sv.nps2112.getFormData()).toString()); 
							} else {
								formatValue = formatValue( longValue);
							}
					
					}
					%>			
				<div class='<%= ((formatValue == null)||("".equals(formatValue.trim()))) ? 
						"blank_cell" : "output_cell" %>'>
				<%=formatValue%>
			</div>	
		<%
		longValue = null;
		formatValue = null;
		%>
  <%}%>
	

</td>

</tr><tr style='height:22px;'><td>

<%if ((new Byte((MESSAGE_CODE).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("MESSAGE_CODE")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2113).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2113' 
type='text'

<%if((sv.nps2113).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2113.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2113.getLength()%>'
maxLength='<%=sv.nps2113.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2113).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2113).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2113).getColor()== null  ? 
			"input_cell" :  (sv.nps2113).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td>

<td>

<%if ((new Byte((MESSAGING_PERMITTED_TO).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("MESSAGING_PERMITTED_TO")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2114).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2114' 
type='text'

<%if((sv.nps2114).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2114.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2114.getLength()%>'
maxLength='<%=sv.nps2114.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2114).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2114).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2114).getColor()== null  ? 
			"input_cell" :  (sv.nps2114).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td></tr></table></fieldset>

<br/><br/>

<!-- tab div -->
<div class="tabblock" id="navbar">
   <div id="header" class="tabheader"  style="margin-left=15px;">
       <table><tr>
   	   	   		   	     		   	     		   		  	   	        <td><div id="current1" class="tabcurrent">
   	      	<p><a href="javascript:;" onClick="change_option(5,1);">
	      	<%=resourceBundleHandler.gettingValueFromBundle("Related Units")%>	
	      	</a></p>
	      	</div></td>		  		  
	      	   		   	     		   		  		      	<td><div id="current2" class="tab">
		    <p><a href="javascript:;" onClick="change_option(5,2);">
		    <%=resourceBundleHandler.gettingValueFromBundle("Flags")%>
		    </a></p>
	      	</div></td>
	   		   		   	     		   		  		      	<td><div id="current3" class="tab">
		    <p><a href="javascript:;" onClick="change_option(5,3);">
		    <%=resourceBundleHandler.gettingValueFromBundle("Unit Dates")%>
		    </a></p>
	      	</div></td>
	   		   		   	     		   		  		      	<td><div id="current4" class="tab">
		    <p><a href="javascript:;" onClick="change_option(5,4);">
		    <%=resourceBundleHandler.gettingValueFromBundle("Parts Markup %")%>
		    </a></p>
	      	</div></td>
	   		   		   	     		   		  		      	<td><div id="current5" class="tab">
		    <p><a href="javascript:;" onClick="change_option(5,5);">
		    <%=resourceBundleHandler.gettingValueFromBundle("Misc")%>
		    </a></p>
	      	</div></td>
	   		   		   	     		   	          </tr></table></div>
<div >
<div id="content1" >
  
 	
	<table class="tabcontent_table">

<tr style='height:22px;'><td width='140px'>

<%if ((new Byte((RELATED_UNITS_REGION).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("RELATED_UNITS_REGION")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2115).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2115' 
type='text'

<%if((sv.nps2115).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2115.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2115.getLength()%>'
maxLength='<%=sv.nps2115.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2115).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2115).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2115).getColor()== null  ? 
			"input_cell" :  (sv.nps2115).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td></tr>

<tr style='height:22px;'><td width='140px'>

<%if ((new Byte((REPORTING).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("REPORTING")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2117).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2117' 
type='text'

<%if((sv.nps2117).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2117.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2117.getLength()%>'
maxLength='<%=sv.nps2117.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2117).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2117).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2117).getColor()== null  ? 
			"input_cell" :  (sv.nps2117).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td></tr>

<tr style='height:22px;'><td width='140px'>

<%if ((new Byte((DISTRICT).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("DISTRICT")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2119).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2119' 
type='text'

<%if((sv.nps2119).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2119.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2119.getLength()%>'
maxLength='<%=sv.nps2119.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2119).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2119).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2119).getColor()== null  ? 
			"input_cell" :  (sv.nps2119).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td></tr>

<tr style='height:22px;'><td width='140px'>

<%if ((new Byte((POS_UNIT).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("POS_UNIT")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2121).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2121' 
type='text'

<%if((sv.nps2121).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2121.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2121.getLength()%>'
maxLength='<%=sv.nps2121.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2121).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2121).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2121).getColor()== null  ? 
			"input_cell" :  (sv.nps2121).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td></tr>

<tr style='height:22px;'><td width='140px'>

<%if ((new Byte((RFS_ACCT).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("RFS_ACCT")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2123).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2123' 
type='text'

<%if((sv.nps2123).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2123.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2123.getLength()%>'
maxLength='<%=sv.nps2123.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2123).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2123).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2123).getColor()== null  ? 
			"input_cell" :  (sv.nps2123).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td></tr>

<tr style='height:22px;'><td width='140px'>

<%if ((new Byte((REGION_ROUTING).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("REGION_ROUTING")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2125).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2125' 
type='text'

<%if((sv.nps2125).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2125.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2125.getLength()%>'
maxLength='<%=sv.nps2125.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2125).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2125).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2125).getColor()== null  ? 
			"input_cell" :  (sv.nps2125).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td></tr></table></div><div id='content2'  style='display:none;'><table  class="tabcontent_table">

<tr style='height:22px;'><td width='140px'>

<%if ((new Byte((FLAGS_PROVIDE_SERVICE_FLAG).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("FLAGS_PROVIDE_SERVICE_FLAG")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2116).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2116' 
type='text'

<%if((sv.nps2116).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2116.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2116.getLength()%>'
maxLength='<%=sv.nps2116.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2116).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2116).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2116).getColor()== null  ? 
			"input_cell" :  (sv.nps2116).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td></tr>

<tr style='height:22px;'><td width='140px'>

<%if ((new Byte((PROVIDE_MARKETING_FLAG).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("PROVIDE_MARKETING_FLAG")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2118).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2118' 
type='text'

<%if((sv.nps2118).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2118.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2118.getLength()%>'
maxLength='<%=sv.nps2118.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2118).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2118).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2118).getColor()== null  ? 
			"input_cell" :  (sv.nps2118).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td></tr>

<tr style='height:22px;'><td width='140px'>

<%if ((new Byte((CONVERTED_TO_NPS_FLAG).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("CONVERTED_TO_NPS_FLAG")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2120).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2120' 
type='text'

<%if((sv.nps2120).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2120.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2120.getLength()%>'
maxLength='<%=sv.nps2120.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2120).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2120).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2120).getColor()== null  ? 
			"input_cell" :  (sv.nps2120).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td></tr>

<tr style='height:22px;'><td width='140px'>

<%if ((new Byte((CARRY_INVENTORY_FLAG).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("CARRY_INVENTORY_FLAG")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2122).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2122' 
type='text'

<%if((sv.nps2122).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2122.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2122.getLength()%>'
maxLength='<%=sv.nps2122.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2122).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2122).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2122).getColor()== null  ? 
			"input_cell" :  (sv.nps2122).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td></tr>

<tr style='height:22px;'><td width='140px'>

<%if ((new Byte((CREATE_DRC_ORDER_FLAG).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("CREATE_DRC_ORDER_FLAG")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2124).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2124' 
type='text'

<%if((sv.nps2124).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2124.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2124.getLength()%>'
maxLength='<%=sv.nps2124.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2124).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2124).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2124).getColor()== null  ? 
			"input_cell" :  (sv.nps2124).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td></tr></table></div><div id='content3'   style='display:none;'><table  class="tabcontent_table">

<tr style='height:22px;'><td width='140px'>

<%if ((new Byte((UNIT_DATES_OPEN_DATE).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("UNIT_DATES_OPEN_DATE")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2126).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2126' 
type='text'

<%if((sv.nps2126).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2126.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2126.getLength()%>'
maxLength='<%=sv.nps2126.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2126).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2126).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2126).getColor()== null  ? 
			"input_cell" :  (sv.nps2126).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>





<%if ((new Byte((sv.nps2127).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2127' 
type='text'

<%if((sv.nps2127).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2127.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2127.getLength()%>'
maxLength='<%=sv.nps2127.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2127).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2127).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2127).getColor()== null  ? 
			"input_cell" :  (sv.nps2127).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>





<%if ((new Byte((sv.nps2128).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2128' 
type='text'

<%if((sv.nps2128).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2128.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2128.getLength()%>'
maxLength='<%=sv.nps2128.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2128).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2128).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2128).getColor()== null  ? 
			"input_cell" :  (sv.nps2128).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td></tr>

<tr style='height:22px;'><td width='140px'>

<%if ((new Byte((HHT_DATE).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("HHT_DATE")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2129).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2129' 
type='text'

<%if((sv.nps2129).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2129.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2129.getLength()%>'
maxLength='<%=sv.nps2129.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2129).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2129).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2129).getColor()== null  ? 
			"input_cell" :  (sv.nps2129).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>





<%if ((new Byte((sv.nps2130).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2130' 
type='text'

<%if((sv.nps2130).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2130.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2130.getLength()%>'
maxLength='<%=sv.nps2130.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2130).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2130).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2130).getColor()== null  ? 
			"input_cell" :  (sv.nps2130).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>





<%if ((new Byte((sv.nps2131).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2131' 
type='text'

<%if((sv.nps2131).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2131.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2131.getLength()%>'
maxLength='<%=sv.nps2131.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2131).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2131).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2131).getColor()== null  ? 
			"input_cell" :  (sv.nps2131).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td></tr>

<tr style='height:22px;'><td width='140px'>

<%if ((new Byte((CLOSED_DATE).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("CLOSED_DATE")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2132).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2132' 
type='text'

<%if((sv.nps2132).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2132.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2132.getLength()%>'
maxLength='<%=sv.nps2132.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2132).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2132).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2132).getColor()== null  ? 
			"input_cell" :  (sv.nps2132).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>





<%if ((new Byte((sv.nps2133).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2133' 
type='text'

<%if((sv.nps2133).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2133.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2133.getLength()%>'
maxLength='<%=sv.nps2133.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2133).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2133).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2133).getColor()== null  ? 
			"input_cell" :  (sv.nps2133).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>





<%if ((new Byte((sv.nps2134).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2134' 
type='text'

<%if((sv.nps2134).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2134.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2134.getLength()%>'
maxLength='<%=sv.nps2134.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2134).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2134).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2134).getColor()== null  ? 
			"input_cell" :  (sv.nps2134).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td></tr>

<tr style='height:22px;'><td width='140px'>

<%if ((new Byte((NPN_DATE).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("NPN_DATE")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2135).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2135' 
type='text'

<%if((sv.nps2135).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2135.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2135.getLength()%>'
maxLength='<%=sv.nps2135.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2135).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2135).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2135).getColor()== null  ? 
			"input_cell" :  (sv.nps2135).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>





<%if ((new Byte((sv.nps2136).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2136' 
type='text'

<%if((sv.nps2136).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2136.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2136.getLength()%>'
maxLength='<%=sv.nps2136.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2136).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2136).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2136).getColor()== null  ? 
			"input_cell" :  (sv.nps2136).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>





<%if ((new Byte((sv.nps2137).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2137' 
type='text'

<%if((sv.nps2137).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2137.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2137.getLength()%>'
maxLength='<%=sv.nps2137.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2137).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2137).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2137).getColor()== null  ? 
			"input_cell" :  (sv.nps2137).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td></tr>

<tr style='height:22px;'><td width='140px'>

<%if ((new Byte((POS_START_DATE).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("POS_START_DATE")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2138).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2138' 
type='text'

<%if((sv.nps2138).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2138.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2138.getLength()%>'
maxLength='<%=sv.nps2138.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2138).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2138).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2138).getColor()== null  ? 
			"input_cell" :  (sv.nps2138).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>





<%if ((new Byte((sv.nps2139).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2139' 
type='text'

<%if((sv.nps2139).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2139.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2139.getLength()%>'
maxLength='<%=sv.nps2139.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2139).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2139).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2139).getColor()== null  ? 
			"input_cell" :  (sv.nps2139).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>





<%if ((new Byte((sv.nps2140).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2140' 
type='text'

<%if((sv.nps2140).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2140.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2140.getLength()%>'
maxLength='<%=sv.nps2140.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2140).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2140).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2140).getColor()== null  ? 
			"input_cell" :  (sv.nps2140).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td></tr>

<tr style='height:22px;'><td width='140px'>

<%if ((new Byte((ROUTING_DATE).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("ROUTING_DATE")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2141).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2141' 
type='text'

<%if((sv.nps2141).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2141.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2141.getLength()%>'
maxLength='<%=sv.nps2141.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2141).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2141).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2141).getColor()== null  ? 
			"input_cell" :  (sv.nps2141).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>





<%if ((new Byte((sv.nps2142).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2142' 
type='text'

<%if((sv.nps2142).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2142.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2142.getLength()%>'
maxLength='<%=sv.nps2142.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2142).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2142).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2142).getColor()== null  ? 
			"input_cell" :  (sv.nps2142).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>





<%if ((new Byte((sv.nps2143).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2143' 
type='text'

<%if((sv.nps2143).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2143.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2143.getLength()%>'
maxLength='<%=sv.nps2143.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2143).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2143).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2143).getColor()== null  ? 
			"input_cell" :  (sv.nps2143).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td></tr>

<tr style='height:22px;'><td width='140px'>

<%if ((new Byte((SAME_DAY_ROUTING).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("SAME_DAY_ROUTING")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2144).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2144' 
type='text'

<%if((sv.nps2144).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2144.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2144.getLength()%>'
maxLength='<%=sv.nps2144.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2144).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2144).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2144).getColor()== null  ? 
			"input_cell" :  (sv.nps2144).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td></tr></table></div><div id='content4'   style='display:none;'><table  class="tabcontent_table">

<tr style='height:22px;'><td width='140px'>

<%if ((new Byte((PARTS_MARKUP_FOREIGN_STORE).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("PARTS_MARKUP_FOREIGN_STORE")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2145).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2145' 
type='text'

<%if((sv.nps2145).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2145.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2145.getLength()%>'
maxLength='<%=sv.nps2145.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2145).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2145).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2145).getColor()== null  ? 
			"input_cell" :  (sv.nps2145).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td></tr>

<tr style='height:22px;'><td width='140px'>

<%if ((new Byte((PREMIUM_INHOME).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("PREMIUM_INHOME")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2147).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2147' 
type='text'

<%if((sv.nps2147).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2147.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2147.getLength()%>'
maxLength='<%=sv.nps2147.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2147).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2147).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2147).getColor()== null  ? 
			"input_cell" :  (sv.nps2147).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td></tr>

<tr style='height:22px;'><td width='140px'>

<%if ((new Byte((PREMIUM).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("PREMIUM")%>
</div>
<%}%>




<%if ((new Byte((ALL_SLASH_LENGTH_1).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("ALL_SLASH_LENGTH_1")%>
</div>
<%}%>




<%if ((new Byte((SHOP).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("SHOP")%>
</div>
<%}%>




<%if ((new Byte((ALL_DOT_LENGTH_1_1).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("ALL_DOT_LENGTH_1")%>
</div>
<%}%>




<%if ((new Byte((ALL_DOT_LENGTH_1_2).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("ALL_DOT_LENGTH_1")%>
</div>
<%}%>




<%if ((new Byte((ALL_DOT_LENGTH_1_3).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("ALL_DOT_LENGTH_1")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2149).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2149' 
type='text'

<%if((sv.nps2149).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2149.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2149.getLength()%>'
maxLength='<%=sv.nps2149.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2149).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2149).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2149).getColor()== null  ? 
			"input_cell" :  (sv.nps2149).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td></tr></table></div><div id='content5' style='display:none;'><table  class="tabcontent_table">

<tr style='height:22px;'><td width='140px'>

<%if ((new Byte((MISC_STATE_REG).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("MISC_STATE_REG")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2146).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2146' 
type='text'

<%if((sv.nps2146).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2146.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2146.getLength()%>'
maxLength='<%=sv.nps2146.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2146).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2146).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2146).getColor()== null  ? 
			"input_cell" :  (sv.nps2146).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td></tr>

<tr style='height:22px;'><td width='140px'>

<%if ((new Byte((PARTS_SHIP_DEST_B_H_T).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("PARTS_SHIP_DEST_B_H_T")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2148).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2148' 
type='text'

<%if((sv.nps2148).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2148.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2148.getLength()%>'
maxLength='<%=sv.nps2148.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2148).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2148).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2148).getColor()== null  ? 
			"input_cell" :  (sv.nps2148).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td></tr>

<tr style='height:22px;'><td width='140px'>

<%if ((new Byte((ACCESS_DOCK_UNIT).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("ACCESS_DOCK_UNIT")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2150).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2150' 
type='text'

<%if((sv.nps2150).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2150.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2150.getLength()%>'
maxLength='<%=sv.nps2150.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2150).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2150).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2150).getColor()== null  ? 
			"input_cell" :  (sv.nps2150).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>



</td></tr></table></div></div></div>
</br></br>

<fieldset class="fieldsetUIG">
<legend class="legendUIG">
<%=resourceBundleHandler.gettingValueFromBundle("Command")%>
</legend>
<table width='100%' align ='center' class ='tableFormat' cellspacing="5px">


<tr style='height:22px;'><td>

<%if ((new Byte((COMMAND).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("COMMAND")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps2153).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2153' 
type='text'

<%if((sv.nps2153).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2153.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2153.getLength()%>'
maxLength='<%=sv.nps2153.getLength()%>' 
onFocus='doFocus(this)' 


<% 
	if((new Byte((sv.nps2153).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2153).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2153).getColor()== null  ? 
			"input_cell" :  (sv.nps2153).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td>
<!-- Added manully -->
<td>

<%if ((new Byte((HHT_OPTIONS_2_ADDITIONAL_INFORMATION).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("1_HHT_OPTIONS_2_ADDITIONAL_INFORMATION")%>
</div>
<%}%>
</td>
<!-- End : Added manully -->
</tr></table></fieldset>

<%if ((new Byte((ENTER_F1_HELP_F3_EXIT_F5_REFRESH_F9_COMMAND_F12_PREV_SCREEN).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("ENTER_F1_HELP_F3_EXIT_F5_REFRESH_F9_COMMAND_F12_PREV_SCREEN")%>
</div>
<%}%>


</div><br/>


<div style='visibility:hidden;'><table>
<tr style='height:22px;'><td width='140px'>
<%if ((new Byte((NPS22017).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("NPS22017")%>
</div>
<%}%>
</td>

<td width='280px'>

<%if ((new Byte((sv.nps2101).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>
	
  		
		<%					
		if(!((sv.nps2101.getFormData()).toString()).trim().equalsIgnoreCase("")) { 	
					
							if(longValue == null || longValue.equalsIgnoreCase("")) {
								formatValue = formatValue( (sv.nps2101.getFormData()).toString()); 
							} else {
								formatValue = formatValue( longValue);
							}
							
							
					} else  {
								
					if(longValue == null || longValue.equalsIgnoreCase("")) {
								formatValue = formatValue( (sv.nps2101.getFormData()).toString()); 
							} else {
								formatValue = formatValue( longValue);
							}
					
					}
					%>			
				<div class='<%= ((formatValue == null)||("".equals(formatValue.trim()))) ? 
						"blank_cell" : "output_cell" %>'>
				<%=formatValue%>
			</div>	
		<%
		longValue = null;
		formatValue = null;
		%>
  <%}%>
	

</td>

<td width='140px'>
<%if ((new Byte((NPS_UNIT_INFORMATION).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("NPS_UNIT_INFORMATION")%>
</div>
<%}%>
</td>

<td>

<%if ((new Byte((sv.nps2102).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>
	
  		
		<%					
		if(!((sv.nps2102.getFormData()).toString()).trim().equalsIgnoreCase("")) { 	
					
							if(longValue == null || longValue.equalsIgnoreCase("")) {
								formatValue = formatValue( (sv.nps2102.getFormData()).toString()); 
							} else {
								formatValue = formatValue( longValue);
							}
							
							
					} else  {
								
					if(longValue == null || longValue.equalsIgnoreCase("")) {
								formatValue = formatValue( (sv.nps2102.getFormData()).toString()); 
							} else {
								formatValue = formatValue( longValue);
							}
					
					}
					%>			
				<div class='<%= ((formatValue == null)||("".equals(formatValue.trim()))) ? 
						"blank_cell" : "output_cell" %>'>
				<%=formatValue%>
			</div>	
		<%
		longValue = null;
		formatValue = null;
		%>
  <%}%>
	

</td></tr>
<tr style='height:22px;'><td width='140px'>
<%if ((new Byte((ALL_DASH_LENGTH_1).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("ALL_DASH_LENGTH_1")%>
</div>
<%}%>
</td>

<%--
<td width='280px'>
<%if ((new Byte((sv.nps2110).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS2110' 
type='text'

<%if((sv.nps2110).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps2110.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps2110.getLength()%>'
maxLength='<%=sv.nps2110.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps2110).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps2110).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps2110).getColor()== null  ? 
			"input_cell" :  (sv.nps2110).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td>
--%>
<td width='140px'>
<%if ((new Byte((HHT_OPTIONS_2_ADDITIONAL_INFORMATION).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("1_HHT_OPTIONS_2_ADDITIONAL_INFORMATION")%>
</div>
<%}%>
</td>

<td>
<%if ((new Byte((ENTER_F1_HELP_F3_EXIT_F5_REFRESH_F9_COMMAND_F12_PREV_SCREEN).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("ENTER_F1_HELP_F3_EXIT_F5_REFRESH_F9_COMMAND_F12_PREV_SCREEN")%>
</div>
<%}%>
</td></tr>
</table></div><br/></div>

<%@ include file="/mainCommon2.jsp"%>



