

<%@ page import="com.sears.processing.code.model.Nps302ScreenVars" %>


<%@ include file="/mainCommon1.jsp"%>


<%--                                                                --%>

<%-- Use is subject to license terms.                               --%>

<%-- This software is the proprietary information of CSC.           --%>

<%--                                                                --%>

<%-- Copyright 2011 CSC, all rights reserved.                       --%>

<%--                                                                --%>

<%-- Generation Date: Tue, 22 Nov 2011 16:10:01                     --%>

<%-- Generated from:  NPS302.BMS Record: NPS302                   --%>

<%-- Generated by:    CSC                                           --%>

<%--                                                                --%>

<%StringData ENTER_F1_HELP_F3_EXIT_F5_REFRESH_F12_PREV_SCREEN = new StringData("ENTER_F1_HELP_F3_EXIT_F5_REFRESH_F12_PREV_SCREEN");%>

<%StringData UNIT_NUMBER = new StringData("UNIT_NUMBER");%>

<%StringData THEN_PRESS_ENTER = new StringData("THEN_PRESS_ENTER");%>

<%StringData TO_VIEW_DATA_FOR_A_SPECIFIC_UNIT_TYPE_THE_INFORMATION_BELOW = new StringData("TO_VIEW_DATA_FOR_A_SPECIFIC_UNIT_TYPE_THE_INFORMATION_BELOW");%>

<%StringData NPS_UNIT_SELECTION_MENU = new StringData("NPS_UNIT_SELECTION_MENU");%>

<%StringData NPS30202 = new StringData("NPS30202");%>

<% Nps302ScreenVars sv = (Nps302ScreenVars) screenModel.getVariables();%>

<br/><br/>
<div class='outerDiv'>
<br/><br/>
<table>

<tr style='height:22px;'><td width='140px'>


<%if ((new Byte((sv.nps3104).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>
	
  		
		<%					
		if(!((sv.nps3104.getFormData()).toString()).trim().equalsIgnoreCase("")) { 	
					
							if(longValue == null || longValue.equalsIgnoreCase("")) {
								formatValue = formatValue( (sv.nps3104.getFormData()).toString()); 
							} else {
								formatValue = formatValue( longValue);
							}
							
							
					} else  {
								
					if(longValue == null || longValue.equalsIgnoreCase("")) {
								formatValue = formatValue( (sv.nps3104.getFormData()).toString()); 
							} else {
								formatValue = formatValue( longValue);
							}
					
					}
					%>			
				<div class='<%= ((formatValue == null)||("".equals(formatValue.trim()))) ? 
						"blank_cell" : "output_cell" %>'>
				<%=formatValue%>
			</div>	
		<%
		longValue = null;
		formatValue = null;
		%>
  <%}%>
	

</td>

<td>


<%if ((new Byte((sv.nps3105).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>
	
  		
		<%					
		if(!((sv.nps3105.getFormData()).toString()).trim().equalsIgnoreCase("")) { 	
					
							if(longValue == null || longValue.equalsIgnoreCase("")) {
								formatValue = formatValue( (sv.nps3105.getFormData()).toString()); 
							} else {
								formatValue = formatValue( longValue);
							}
							
							
					} else  {
								
					if(longValue == null || longValue.equalsIgnoreCase("")) {
								formatValue = formatValue( (sv.nps3105.getFormData()).toString()); 
							} else {
								formatValue = formatValue( longValue);
							}
					
					}
					%>			
				<div class='<%= ((formatValue == null)||("".equals(formatValue.trim()))) ? 
						"blank_cell" : "output_cell" %>'>
				<%=formatValue%>
			</div>	
		<%
		longValue = null;
		formatValue = null;
		%>
  <%}%>
	

</td></tr></table><br/><br/>
<fieldset class="fieldsetUIG">
<legend class="legendUIG">
<%=resourceBundleHandler.gettingValueFromBundle("Unit Selection")%>
</legend>
<table width='100%' align ='center' class ='tableFormat' cellspacing="5px">


<tr style='height:22px;'><td>

<%if ((new Byte((UNIT_NUMBER).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("UNIT_NUMBER")%>
</div>
<%}%>
</td>


<td>

<%if ((new Byte((sv.nps3103).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>

<input name='NPS3103' 
type='text'

<%if((sv.nps3103).getClass().getSimpleName().equals("ZonedDecimalData")) {%>style="text-align: right"<% }%>

<%

		formatValue = (sv.nps3103.getFormData()).toString();

%>
	value='<%=formatValue%>' <%if(formatValue!=null && formatValue.trim().length()>0) {%> title='<%=formatValue%>' <%}%>

size='<%=sv.nps3103.getLength()%>'
maxLength='<%=sv.nps3103.getLength()%>' 
onFocus='doFocus(this)' onHelp='return fieldHelp(action)' onKeyUp='return checkMaxLength(this)'  


<% 
	if((new Byte((sv.nps3103).getEnabled()))
	.compareTo(new Byte(BaseScreenData.DISABLED)) == 0 || screenModel.getVariables().isScreenProtected()){ 
%>  
	readonly="true"
	class="output_cell"
<%
	}else if((new Byte((sv.nps3103).getHighLight())).
		compareTo(new Byte(BaseScreenData.BOLD)) == 0){
%>	
		class="bold_cell" 

<%
	}else { 
%>

	class = ' <%=(sv.nps3103).getColor()== null  ? 
			"input_cell" :  (sv.nps3103).getColor().equals("red") ? 
			"input_cell red reverse" : "input_cell" %>'
 
<%
	} 
%>
>
<%}%>
</td></tr></table></fieldset><br/>
<%if ((new Byte((ENTER_F1_HELP_F3_EXIT_F5_REFRESH_F12_PREV_SCREEN).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("ENTER_F1_HELP_F3_EXIT_F5_REFRESH_F12_PREV_SCREEN")%>
</div>
<%}%>
<div style='visibility:hidden;'><table>
<tr style='height:22px;'><td width='140px'>
<%if ((new Byte((NPS30202).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("NPS30202")%>
</div>
<%}%>
</td>

<td width='280px'>

<%if ((new Byte((sv.nps3101).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>
	
  		
		<%					
		if(!((sv.nps3101.getFormData()).toString()).trim().equalsIgnoreCase("")) { 	
					
							if(longValue == null || longValue.equalsIgnoreCase("")) {
								formatValue = formatValue( (sv.nps3101.getFormData()).toString()); 
							} else {
								formatValue = formatValue( longValue);
							}
							
							
					} else  {
								
					if(longValue == null || longValue.equalsIgnoreCase("")) {
								formatValue = formatValue( (sv.nps3101.getFormData()).toString()); 
							} else {
								formatValue = formatValue( longValue);
							}
					
					}
					%>			
				<div class='<%= ((formatValue == null)||("".equals(formatValue.trim()))) ? 
						"blank_cell" : "output_cell" %>'>
				<%=formatValue%>
			</div>	
		<%
		longValue = null;
		formatValue = null;
		%>
  <%}%>
	

</td>

<td width='140px'>
<%if ((new Byte((NPS_UNIT_SELECTION_MENU).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("NPS_UNIT_SELECTION_MENU")%>
</div>
<%}%>
</td>

<td>

<%if ((new Byte((sv.nps3102).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) {%>
	
  		
		<%					
		if(!((sv.nps3102.getFormData()).toString()).trim().equalsIgnoreCase("")) { 	
					
							if(longValue == null || longValue.equalsIgnoreCase("")) {
								formatValue = formatValue( (sv.nps3102.getFormData()).toString()); 
							} else {
								formatValue = formatValue( longValue);
							}
							
							
					} else  {
								
					if(longValue == null || longValue.equalsIgnoreCase("")) {
								formatValue = formatValue( (sv.nps3102.getFormData()).toString()); 
							} else {
								formatValue = formatValue( longValue);
							}
					
					}
					%>			
				<div class='<%= ((formatValue == null)||("".equals(formatValue.trim()))) ? 
						"blank_cell" : "output_cell" %>'>
				<%=formatValue%>
			</div>	
		<%
		longValue = null;
		formatValue = null;
		%>
  <%}%>
	

</td></tr>

<tr style='height:22px;'><td width='140px'>
<%if ((new Byte((TO_VIEW_DATA_FOR_A_SPECIFIC_UNIT_TYPE_THE_INFORMATION_BELOW).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("TO_VIEW_DATA_FOR_A_SPECIFIC_UNIT_TYPE_THE_INFORMATION_BELOW")%>
</div>
<%}%>
</td>

<td width='280px'>
<%if ((new Byte((THEN_PRESS_ENTER).getInvisible())).compareTo(new Byte(
								BaseScreenData.INVISIBLE)) != 0) { %>
<div class="label_txt">
<%=resourceBundleHandler.gettingValueFromBundle("THEN_PRESS_ENTER")%>
</div>
<%}%>
</td>
</tr></table></div><br/></div>

<%@ include file="/mainCommon2.jsp"%>



