<%--------------------------------------------------------------------%>
<%--                                                                --%>
<%-- Generated by:    CSC                                           --%>
<%-- Generated from:  NPS220.BMS Record: NPS220                   --%>
<%-- Generation Date: Tue, 22 Nov 2011 16:10:01                     --%>
<%--                                                                --%>
<%-- Copyright 2011 CSC, all rights reserved.                       --%>
<%--                                                                --%>
<%-- This software is the proprietary information of CSC.           --%>
<%-- Use is subject to license terms.                               --%>
<%--                                                                --%>
<%--------------------------------------------------------------------%>



<%@ include file="/mainCommon1.jsp"%>

<%@ page import="com.sears.processing.code.model.Nps220ScreenVars" %>

<% Nps220ScreenVars sv = (Nps220ScreenVars) screenModel.getVariables();%>

<%= htmlFormatter.getLit(1, 1, 10, "${NPS22017}")%>
<%= htmlFormatter.getHTMLVar(1, 12, screenModel, sv, sv.nps2101)%>
<%= htmlFormatter.getLit(1, 25, 30, "${NPS_UNIT_INFORMATION}", true)%>
<%= htmlFormatter.getHTMLVar(1, 72, screenModel, sv, sv.nps2102)%>
<%= htmlFormatter.getLit(2, 1, 14, "${UNIT}")%>
<%= htmlFormatter.getHTMLVar(2, 16, screenModel, sv, sv.nps2103)%>
<%= htmlFormatter.getLit(2, 37, 14, "${UNIT_NAME}")%>
<%= htmlFormatter.getHTMLVar(2, 52, screenModel, sv, sv.nps2104)%>
<%= htmlFormatter.getLit(3, 1, 14, "${ADDRESS}")%>
<%= htmlFormatter.getHTMLVar(3, 16, screenModel, sv, sv.nps2105)%>
<%= htmlFormatter.getHTMLVar(3, 47, screenModel, sv, sv.nps2106)%>
<%= htmlFormatter.getLit(4, 1, 14, "${CITY}")%>
<%= htmlFormatter.getHTMLVar(4, 16, screenModel, sv, sv.nps2107)%>
<%= htmlFormatter.getLit(4, 42, 9, "${STATE}")%>
<%= htmlFormatter.getHTMLVar(4, 52, screenModel, sv, sv.nps2108)%>
<%= htmlFormatter.getLit(4, 59, 7, "${ZIP}")%>
<%= htmlFormatter.getHTMLVar(4, 67, screenModel, sv, sv.nps2109)%>
<%= htmlFormatter.getLit(4, 73, 1, "${ALL_DASH_LENGTH_1}")%>
<%= htmlFormatter.getHTMLVar(4, 75, screenModel, sv, sv.nps2110)%>
<%= htmlFormatter.getLit(6, 1, 14, "${UNIT_TYPE}")%>
<%= htmlFormatter.getHTMLVar(6, 16, screenModel, sv, sv.nps2111)%>
<%= htmlFormatter.getHTMLVar(6, 20, screenModel, sv, sv.nps2112)%>
<%= htmlFormatter.getLit(7, 1, 16, "${MESSAGE_CODE}")%>
<%= htmlFormatter.getHTMLVar(7, 18, screenModel, sv, sv.nps2113)%>
<%= htmlFormatter.getLit(7, 36, 26, "${MESSAGING_PERMITTED_TO}")%>
<%= htmlFormatter.getHTMLVar(7, 63, screenModel, sv, sv.nps2114)%>
<%= htmlFormatter.getLit(8, 1, 31, "${RELATED_UNITS_REGION}")%>
<%= htmlFormatter.getHTMLVar(8, 33, screenModel, sv, sv.nps2115)%>
<%= htmlFormatter.getLit(8, 44, 33, "${FLAGS_PROVIDE_SERVICE_FLAG}")%>
<%= htmlFormatter.getHTMLVar(8, 78, screenModel, sv, sv.nps2116)%>
<%= htmlFormatter.getLit(9, 16, 16, "${REPORTING}")%>
<%= htmlFormatter.getHTMLVar(9, 33, screenModel, sv, sv.nps2117)%>
<%= htmlFormatter.getLit(9, 51, 26, "${PROVIDE_MARKETING_FLAG}")%>
<%= htmlFormatter.getHTMLVar(9, 78, screenModel, sv, sv.nps2118)%>
<%= htmlFormatter.getLit(10, 16, 16, "${DISTRICT}")%>
<%= htmlFormatter.getHTMLVar(10, 33, screenModel, sv, sv.nps2119)%>
<%= htmlFormatter.getLit(10, 51, 26, "${CONVERTED_TO_NPS_FLAG}")%>
<%= htmlFormatter.getHTMLVar(10, 78, screenModel, sv, sv.nps2120)%>
<%= htmlFormatter.getLit(11, 16, 16, "${POS_UNIT}")%>
<%= htmlFormatter.getHTMLVar(11, 33, screenModel, sv, sv.nps2121)%>
<%= htmlFormatter.getLit(11, 51, 26, "${CARRY_INVENTORY_FLAG}")%>
<%= htmlFormatter.getHTMLVar(11, 78, screenModel, sv, sv.nps2122)%>
<%= htmlFormatter.getLit(12, 16, 16, "${RFS_ACCT}")%>
<%= htmlFormatter.getHTMLVar(12, 33, screenModel, sv, sv.nps2123)%>
<%= htmlFormatter.getLit(12, 51, 26, "${CREATE_DRC_ORDER_FLAG}")%>
<%= htmlFormatter.getHTMLVar(12, 78, screenModel, sv, sv.nps2124)%>
<%= htmlFormatter.getLit(13, 16, 16, "${REGION_ROUTING}")%>
<%= htmlFormatter.getHTMLVar(13, 33, screenModel, sv, sv.nps2125)%>
<%= htmlFormatter.getLit(14, 1, 30, "${UNIT_DATES_OPEN_DATE}")%>
<%= htmlFormatter.getHTMLVar(14, 32, screenModel, sv, sv.nps2126)%>
<%= htmlFormatter.getHTMLVar(14, 35, screenModel, sv, sv.nps2127)%>
<%= htmlFormatter.getHTMLVar(14, 38, screenModel, sv, sv.nps2128)%>
<%= htmlFormatter.getLit(14, 51, 19, "${HHT_DATE}")%>
<%= htmlFormatter.getHTMLVar(14, 71, screenModel, sv, sv.nps2129)%>
<%= htmlFormatter.getHTMLVar(14, 74, screenModel, sv, sv.nps2130)%>
<%= htmlFormatter.getHTMLVar(14, 77, screenModel, sv, sv.nps2131)%>
<%= htmlFormatter.getLit(15, 16, 15, "${CLOSED_DATE}")%>
<%= htmlFormatter.getHTMLVar(15, 32, screenModel, sv, sv.nps2132)%>
<%= htmlFormatter.getHTMLVar(15, 35, screenModel, sv, sv.nps2133)%>
<%= htmlFormatter.getHTMLVar(15, 38, screenModel, sv, sv.nps2134)%>
<%= htmlFormatter.getLit(15, 51, 19, "${NPN_DATE}")%>
<%= htmlFormatter.getHTMLVar(15, 71, screenModel, sv, sv.nps2135)%>
<%= htmlFormatter.getHTMLVar(15, 74, screenModel, sv, sv.nps2136)%>
<%= htmlFormatter.getHTMLVar(15, 77, screenModel, sv, sv.nps2137)%>
<%= htmlFormatter.getLit(16, 16, 14, "${POS_START_DATE}")%>
<%= htmlFormatter.getHTMLVar(16, 32, screenModel, sv, sv.nps2138)%>
<%= htmlFormatter.getHTMLVar(16, 35, screenModel, sv, sv.nps2139)%>
<%= htmlFormatter.getHTMLVar(16, 38, screenModel, sv, sv.nps2140)%>
<%= htmlFormatter.getLit(16, 51, 19, "${ROUTING_DATE}")%>
<%= htmlFormatter.getHTMLVar(16, 71, screenModel, sv, sv.nps2141)%>
<%= htmlFormatter.getHTMLVar(16, 74, screenModel, sv, sv.nps2142)%>
<%= htmlFormatter.getHTMLVar(16, 77, screenModel, sv, sv.nps2143)%>
<%= htmlFormatter.getLit(17, 51, 19, "${SAME_DAY_ROUTING}")%>
<%= htmlFormatter.getHTMLVar(17, 71, screenModel, sv, sv.nps2144)%>
<%= htmlFormatter.getLit(18, 1, 36, "${PARTS_MARKUP_FOREIGN_STORE}")%>
<%= htmlFormatter.getHTMLVar(18, 38, screenModel, sv, sv.nps2145)%>
<%= htmlFormatter.getLit(18, 44, 22, "${MISC_STATE_REG}")%>
<%= htmlFormatter.getHTMLVar(18, 67, screenModel, sv, sv.nps2146)%>
<%= htmlFormatter.getLit(19, 17, 20, "${PREMIUM_INHOME}")%>
<%= htmlFormatter.getHTMLVar(19, 38, screenModel, sv, sv.nps2147)%>
<%= htmlFormatter.getLit(19, 51, 26, "${PARTS_SHIP_DEST_B_H_T}")%>
<%= htmlFormatter.getHTMLVar(19, 78, screenModel, sv, sv.nps2148)%>
<%= htmlFormatter.getLit(20, 17, 7, "${PREMIUM}")%>
<%= htmlFormatter.getLit(20, 25, 1, "${ALL_SLASH_LENGTH_1}")%>
<%= htmlFormatter.getLit(20, 27, 4, "${SHOP}")%>
<%= htmlFormatter.getLit(20, 32, 1, "${ALL_DOT_LENGTH_1}")%>
<%= htmlFormatter.getLit(20, 34, 1, "${ALL_DOT_LENGTH_1}")%>
<%= htmlFormatter.getLit(20, 36, 1, "${ALL_DOT_LENGTH_1}")%>
<%= htmlFormatter.getHTMLVar(20, 38, screenModel, sv, sv.nps2149)%>
<%= htmlFormatter.getLit(20, 51, 20, "${ACCESS_DOCK_UNIT}")%>
<%= htmlFormatter.getHTMLVar(20, 72, screenModel, sv, sv.nps2150)%>
<%= htmlFormatter.getHTMLVar(21, 1, screenModel, sv, sv.nps2151)%>
<%= htmlFormatter.getHTMLVar(22, 1, screenModel, sv, sv.nps2152)%>
<%= htmlFormatter.getLit(23, 1, 12, "${COMMAND}")%>
<%= htmlFormatter.getHTMLVar(23, 15, screenModel, sv, sv.nps2153)%>
<%= htmlFormatter.getLit(23, 18, 41, "${1_HHT_OPTIONS_2_ADDITIONAL_INFORMATION}")%>
<%= htmlFormatter.getLit(24, 1, 64, "${ENTER_F1_HELP_F3_EXIT_F5_REFRESH_F9_COMMAND_F12_PREV_SCREEN}")%>


<%@ include file="/mainCommon2.jsp"%>


